/**
 * Exercise Image Mapping - Auto-generated
 * Maps exercise names to free-exercise-db image folder names.
 * Generated on 2026-03-17
 * Coverage: 1378/1302 exercises (105.8%)
 */

// Maps exercise name → image folder name in assets/exercises/
export const EXERCISE_IMAGE_MAP: Record<string, string> = {
  'Incline Push-up': 'Incline_Push-Up',
  'Single-leg Glute Bridge': 'Single_Leg_Glute_Bridge',
  'Dead-bug': 'Dead_Bug',
  'Star Jump': 'Star_Jump',
  Plank: 'Plank',
  'Pull-up': 'Pullups',
  'Hanging Leg Raise (bent)': 'Hanging_Leg_Raise',
  'Cobra Pose': 'Cobra_Pose',
  'Push-up': 'Pushups',
  'Decline Push-up': 'Decline_Push-Up',
  'Scapular Pull': 'Scapular_Pull-Up',
  'Inverted Row': 'Bodyweight_Mid_Row',
  'Chin-up': 'Chin-Up',
  'Muscle-up': 'Muscle_Up',
  'Bodyweight Squat': 'Bodyweight_Squat',
  'Split Squat': 'Split_Squats',
  'Dead Bug': 'Dead_Bug',
  Crunch: 'Crunches',
  'Mountain Climber': 'Mountain_Climbers',
  'Russian Twist': 'Russian_Twist',
  'Hanging Leg Raise': 'Hanging_Leg_Raise',
  'Pigeon Pose': 'Groiners',
  'Ankle Circles': 'Ankle_Circles',
  'Band Pull-Apart': 'Band_Pull_Apart',
  'Mountain Climbers': 'Mountain_Climbers',
  'Scissor Kicks': 'Scissor_Kick',
  'Split Jump': 'Split_Jump',
  'Shoulder Circles': 'Shoulder_Circles',
  'Arm Circles': 'Arm_Circles',
  'Knee Circles': 'Knee_Circles',
  Inchworm: 'Inchworm',
  'Plyo Push-up': 'Plyo_Push-up',
  'Tree Pose': 'Tree_Pose',
  'Half Moon Pose': 'Half_Moon_Pose',
  'Happy Baby Pose': 'Butterfly',
  'Pallof Press': 'Pallof_Press',
  'Goblet Squat': 'Goblet_Squat',
  'Lateral Bound': 'Lateral_Bound',
  'Acceleration Wall Drill': 'Linear_Acceleration_Wall_Drill',
  'Single Leg Hop Progression': 'Single-Leg_Hop_Progression',
  'Prone Shoulder Circles': 'Shoulder_Circles',
  'Standing Hip Flexor Stretch': 'Standing_Hip_Flexors',
  'Flutter Kick': 'Flutter_Kicks',
  Windmill: 'Windmills',
  'Weighted Squat': 'Weighted_Squat',
  'Ring Dip': 'Ring_Dips',
  'Weighted Pull-up': 'Weighted_Pull_Ups',
  'Handstand Push-up': 'Handstand_Push-Ups',
  'Glute Ham Raise': 'Glute_Ham_Raise',
  'Mountain Pose': 'Mountain_Pose',
  'Chair Pose': 'Chair_Pose',
  'Warrior I Pose': 'Warrior_I_Pose',
  'Warrior II Pose': 'Warrior_II_Pose',
  'Extended Triangle Pose': 'Extended_Triangle_Pose',
  'Extended Side Angle Pose': 'Extended_Side_Angle_Pose',
  'Revolved Triangle Pose': 'Revolved_Triangle_Pose',
  'Garland Pose': 'Garland_Pose',
  'Eagle Pose': 'Eagle_Pose',
  'Lord of the Dance Pose': 'Lord_of_the_Dance_Pose',
  'Staff Pose': 'Staff_Pose',
  'Boat Pose': 'Boat_Pose',
  'Head-to-Knee Forward Bend': 'Head-to-Knee_Forward_Bend',
  'Half Lord of the Fishes Pose': 'Half_Lord_of_the_Fishes_Pose',
  'Lotus Pose': 'Lotus_Pose',
  'Scale Pose': 'Scale_Pose',
  'Upward-Facing Dog Pose': 'Upward-Facing_Dog_Pose',
  'Camel Pose': 'Camel_Pose',
  'Bow Pose': 'Bow_Pose',
  'Bridge Pose': 'Bridge_Pose',
  'Upward Bow (Wheel) Pose': 'Upward_Bow_Wheel_Pose',
  'Sphinx Pose': 'Sphinx_Pose',
  'Crane (Crow) Pose': 'Crane_Crow_Pose',
  'Dolphin Pose': 'Dolphin_Pose',
  'Supported Headstand': 'Supported_Headstand',
  'Supported Shoulderstand': 'Supported_Shoulderstand',
  'Plow Pose': 'Plow_Pose',
  'Corpse Pose': 'Corpse_Pose',
  'Reclining Bound Angle Pose': 'Reclining_Bound_Angle_Pose',
  'Crocodile Pose': 'Crocodile_Pose',
  'Big Toe Pose': 'Big_Toe_Pose',
  'Wide-Legged Forward Bend': 'Wide-Legged_Forward_Bend',
  'Extended Hand-To-Big-Toe Pose': 'Extended_Hand-To-Big-Toe_Pose',
  'Four-Limbed Staff Pose': 'Four-Limbed_Staff_Pose',
  'Upward Plank Pose': 'Upward_Plank_Pose',
  'Locust Pose': 'Locust_Pose',
  '3/4 Sit-Up': '3_4_Sit-Up',
  '90/90 Hamstring': '90_90_Hamstring',
  'Ab Crunch Machine': 'Ab_Crunch_Machine',
  'Ab Roller': 'Ab_Roller',
  Adductor: 'Adductor',
  'Adductor/Groin': 'Adductor_Groin',
  'Advanced Kettlebell Windmill': 'Advanced_Kettlebell_Windmill',
  'Air Bike': 'Air_Bike',
  'All Fours Quad Stretch': 'All_Fours_Quad_Stretch',
  'Alternate Hammer Curl': 'Alternate_Hammer_Curl',
  'Alternate Heel Touchers': 'Alternate_Heel_Touchers',
  'Alternate Incline Dumbbell Curl': 'Alternate_Incline_Dumbbell_Curl',
  'Alternate Leg Diagonal Bound': 'Alternate_Leg_Diagonal_Bound',
  'Alternating Cable Shoulder Press': 'Alternating_Cable_Shoulder_Press',
  'Alternating Deltoid Raise': 'Alternating_Deltoid_Raise',
  'Alternating Floor Press': 'Alternating_Floor_Press',
  'Alternating Hang Clean': 'Alternating_Hang_Clean',
  'Alternating Kettlebell Press': 'Alternating_Kettlebell_Press',
  'Alternating Kettlebell Row': 'Alternating_Kettlebell_Row',
  'Alternating Renegade Row': 'Alternating_Renegade_Row',
  'Ankle On The Knee': 'Ankle_On_The_Knee',
  'Anterior Tibialis-SMR': 'Anterior_Tibialis-SMR',
  'Anti-Gravity Press': 'Anti-Gravity_Press',
  'Arnold Dumbbell Press': 'Arnold_Dumbbell_Press',
  'Around The Worlds': 'Around_The_Worlds',
  'Atlas Stone Trainer': 'Atlas_Stone_Trainer',
  'Atlas Stones': 'Atlas_Stones',
  'Axle Deadlift': 'Axle_Deadlift',
  'Back Flyes - With Bands': 'Back_Flyes_-_With_Bands',
  'Backward Drag': 'Backward_Drag',
  'Backward Medicine Ball Throw': 'Backward_Medicine_Ball_Throw',
  'Balance Board': 'Balance_Board',
  'Ball Leg Curl': 'Ball_Leg_Curl',
  'Band Assisted Pull-Up': 'Band_Assisted_Pull-Up',
  'Band Good Morning': 'Band_Good_Morning',
  'Band Good Morning (Pull Through)': 'Band_Good_Morning_Pull_Through',
  'Band Hip Adductions': 'Band_Hip_Adductions',
  'Band Pull Apart': 'Band_Pull_Apart',
  'Band Skull Crusher': 'Band_Skull_Crusher',
  'Barbell Ab Rollout': 'Barbell_Ab_Rollout',
  'Barbell Ab Rollout - On Knees': 'Barbell_Ab_Rollout_-_On_Knees',
  'Barbell Bench Press - Medium Grip': 'Barbell_Bench_Press_-_Medium_Grip',
  'Barbell Curl': 'Barbell_Curl',
  'Barbell Curls Lying Against An Incline': 'Barbell_Curls_Lying_Against_An_Incline',
  'Barbell Deadlift': 'Barbell_Deadlift',
  'Barbell Full Squat': 'Barbell_Full_Squat',
  'Barbell Glute Bridge': 'Barbell_Glute_Bridge',
  'Barbell Guillotine Bench Press': 'Barbell_Guillotine_Bench_Press',
  'Barbell Hack Squat': 'Barbell_Hack_Squat',
  'Barbell Hip Thrust': 'Barbell_Hip_Thrust',
  'Barbell Incline Bench Press - Medium Grip': 'Barbell_Incline_Bench_Press_-_Medium_Grip',
  'Barbell Incline Shoulder Raise': 'Barbell_Incline_Shoulder_Raise',
  'Barbell Lunge': 'Barbell_Lunge',
  'Barbell Rear Delt Row': 'Barbell_Rear_Delt_Row',
  'Barbell Rollout from Bench': 'Barbell_Rollout_from_Bench',
  'Barbell Seated Calf Raise': 'Barbell_Seated_Calf_Raise',
  'Barbell Shoulder Press': 'Barbell_Shoulder_Press',
  'Barbell Shrug': 'Barbell_Shrug',
  'Barbell Shrug Behind The Back': 'Barbell_Shrug_Behind_The_Back',
  'Barbell Side Bend': 'Barbell_Side_Bend',
  'Barbell Side Split Squat': 'Barbell_Side_Split_Squat',
  'Barbell Squat': 'Barbell_Squat',
  'Barbell Squat To A Bench': 'Barbell_Squat_To_A_Bench',
  'Barbell Step Ups': 'Barbell_Step_Ups',
  'Barbell Walking Lunge': 'Barbell_Walking_Lunge',
  'Battling Ropes': 'Battling_Ropes',
  'Bear Crawl Sled Drags': 'Bear_Crawl_Sled_Drags',
  'Behind Head Chest Stretch': 'Behind_Head_Chest_Stretch',
  'Bench Dips': 'Bench_Dips',
  'Bench Jump': 'Bench_Jump',
  'Bench Press - Powerlifting': 'Bench_Press_-_Powerlifting',
  'Bench Press - With Bands': 'Bench_Press_-_With_Bands',
  'Bench Press with Chains': 'Bench_Press_with_Chains',
  'Bench Sprint': 'Bench_Sprint',
  'Bent-Arm Barbell Pullover': 'Bent-Arm_Barbell_Pullover',
  'Bent-Arm Dumbbell Pullover': 'Bent-Arm_Dumbbell_Pullover',
  'Bent-Knee Hip Raise': 'Bent-Knee_Hip_Raise',
  'Bent Over Barbell Row': 'Bent_Over_Barbell_Row',
  'Bent Over Dumbbell Rear Delt Raise With Head On Bench': 'Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench',
  'Bent Over Low-Pulley Side Lateral': 'Bent_Over_Low-Pulley_Side_Lateral',
  'Bent Over One-Arm Long Bar Row': 'Bent_Over_One-Arm_Long_Bar_Row',
  'Bent Over Two-Arm Long Bar Row': 'Bent_Over_Two-Arm_Long_Bar_Row',
  'Bent Over Two-Dumbbell Row': 'Bent_Over_Two-Dumbbell_Row',
  'Bent Over Two-Dumbbell Row With Palms In': 'Bent_Over_Two-Dumbbell_Row_With_Palms_In',
  'Bent Press': 'Bent_Press',
  Bicycling: 'Bicycling',
  'Bicycling, Stationary': 'Bicycling_Stationary',
  'Board Press': 'Board_Press',
  'Body-Up': 'Body-Up',
  'Body Tricep Press': 'Body_Tricep_Press',
  'Bodyweight Flyes': 'Bodyweight_Flyes',
  'Bodyweight Mid Row': 'Bodyweight_Mid_Row',
  'Bodyweight Walking Lunge': 'Bodyweight_Walking_Lunge',
  'Bosu Ball Cable Crunch With Side Bends': 'Bosu_Ball_Cable_Crunch_With_Side_Bends',
  'Bottoms-Up Clean From The Hang Position': 'Bottoms-Up_Clean_From_The_Hang_Position',
  'Bottoms Up': 'Bottoms_Up',
  'Box Jump (Multiple Response)': 'Box_Jump_Multiple_Response',
  'Box Skip': 'Box_Skip',
  'Box Squat': 'Box_Squat',
  'Box Squat with Bands': 'Box_Squat_with_Bands',
  'Box Squat with Chains': 'Box_Squat_with_Chains',
  'Brachialis-SMR': 'Brachialis-SMR',
  'Bradford/Rocky Presses': 'Bradford_Rocky_Presses',
  'Butt-Ups': 'Butt-Ups',
  'Butt Lift (Bridge)': 'Butt_Lift_Bridge',
  Butterfly: 'Butterfly',
  'Cable Chest Press': 'Cable_Chest_Press',
  'Cable Crossover': 'Cable_Crossover',
  'Cable Crunch': 'Cable_Crunch',
  'Cable Deadlifts': 'Cable_Deadlifts',
  'Cable Hammer Curls - Rope Attachment': 'Cable_Hammer_Curls_-_Rope_Attachment',
  'Cable Hip Adduction': 'Cable_Hip_Adduction',
  'Cable Incline Pushdown': 'Cable_Incline_Pushdown',
  'Cable Incline Triceps Extension': 'Cable_Incline_Triceps_Extension',
  'Cable Internal Rotation': 'Cable_Internal_Rotation',
  'Cable Iron Cross': 'Cable_Iron_Cross',
  'Cable Judo Flip': 'Cable_Judo_Flip',
  'Cable Lying Triceps Extension': 'Cable_Lying_Triceps_Extension',
  'Cable One Arm Tricep Extension': 'Cable_One_Arm_Tricep_Extension',
  'Cable Preacher Curl': 'Cable_Preacher_Curl',
  'Cable Rear Delt Fly': 'Cable_Rear_Delt_Fly',
  'Cable Reverse Crunch': 'Cable_Reverse_Crunch',
  'Cable Rope Overhead Triceps Extension': 'Cable_Rope_Overhead_Triceps_Extension',
  'Cable Rope Rear-Delt Rows': 'Cable_Rope_Rear-Delt_Rows',
  'Cable Russian Twists': 'Cable_Russian_Twists',
  'Cable Seated Crunch': 'Cable_Seated_Crunch',
  'Cable Seated Lateral Raise': 'Cable_Seated_Lateral_Raise',
  'Cable Shoulder Press': 'Cable_Shoulder_Press',
  'Cable Shrugs': 'Cable_Shrugs',
  'Cable Wrist Curl': 'Cable_Wrist_Curl',
  'Calf-Machine Shoulder Shrug': 'Calf-Machine_Shoulder_Shrug',
  'Calf Press': 'Calf_Press',
  'Calf Press On The Leg Press Machine': 'Calf_Press_On_The_Leg_Press_Machine',
  'Calf Raise On A Dumbbell': 'Calf_Raise_On_A_Dumbbell',
  'Calf Raises - With Bands': 'Calf_Raises_-_With_Bands',
  'Calf Stretch Elbows Against Wall': 'Calf_Stretch_Elbows_Against_Wall',
  'Calf Stretch Hands Against Wall': 'Calf_Stretch_Hands_Against_Wall',
  'Calves-SMR': 'Calves-SMR',
  'Car Deadlift': 'Car_Deadlift',
  'Car Drivers': 'Car_Drivers',
  'Carioca Quick Step': 'Carioca_Quick_Step',
  'Cat Stretch': 'Cat_Stretch',
  'Catch and Overhead Throw': 'Catch_and_Overhead_Throw',
  'Chain Handle Extension': 'Chain_Handle_Extension',
  'Chain Press': 'Chain_Press',
  'Chair Leg Extended Stretch': 'Chair_Leg_Extended_Stretch',
  'Chair Lower Back Stretch': 'Chair_Lower_Back_Stretch',
  'Chair Squat': 'Chair_Squat',
  'Chair Upper Body Stretch': 'Chair_Upper_Body_Stretch',
  'Chest And Front Of Shoulder Stretch': 'Chest_And_Front_Of_Shoulder_Stretch',
  'Chest Push from 3 point stance': 'Chest_Push_from_3_point_stance',
  'Chest Push (multiple response)': 'Chest_Push_multiple_response',
  'Chest Push (single response)': 'Chest_Push_single_response',
  'Chest Push with Run Release': 'Chest_Push_with_Run_Release',
  'Chest Stretch on Stability Ball': 'Chest_Stretch_on_Stability_Ball',
  "Child's Pose": 'Childs_Pose',
  'Chin-Up': 'Chin-Up',
  'Chin To Chest Stretch': 'Chin_To_Chest_Stretch',
  'Circus Bell': 'Circus_Bell',
  Clean: 'Clean',
  'Clean Deadlift': 'Clean_Deadlift',
  'Clean Pull': 'Clean_Pull',
  'Clean Shrug': 'Clean_Shrug',
  'Clean and Jerk': 'Clean_and_Jerk',
  'Clean and Press': 'Clean_and_Press',
  'Clean from Blocks': 'Clean_from_Blocks',
  'Clock Push-Up': 'Clock_Push-Up',
  'Close-Grip Barbell Bench Press': 'Close-Grip_Barbell_Bench_Press',
  'Close-Grip Dumbbell Press': 'Close-Grip_Dumbbell_Press',
  'Close-Grip EZ-Bar Curl with Band': 'Close-Grip_EZ-Bar_Curl_with_Band',
  'Close-Grip EZ-Bar Press': 'Close-Grip_EZ-Bar_Press',
  'Close-Grip EZ Bar Curl': 'Close-Grip_EZ_Bar_Curl',
  'Close-Grip Front Lat Pulldown': 'Close-Grip_Front_Lat_Pulldown',
  'Close-Grip Push-Up off of a Dumbbell': 'Close-Grip_Push-Up_off_of_a_Dumbbell',
  'Close-Grip Standing Barbell Curl': 'Close-Grip_Standing_Barbell_Curl',
  Cocoons: 'Cocoons',
  "Conan's Wheel": 'Conans_Wheel',
  'Concentration Curls': 'Concentration_Curls',
  'Cross-Body Crunch': 'Cross-Body_Crunch',
  'Cross Body Hammer Curl': 'Cross_Body_Hammer_Curl',
  'Cross Over - With Bands': 'Cross_Over_-_With_Bands',
  'Crossover Reverse Lunge': 'Crossover_Reverse_Lunge',
  Crucifix: 'Crucifix',
  'Crunch - Hands Overhead': 'Crunch_-_Hands_Overhead',
  'Crunch - Legs On Exercise Ball': 'Crunch_-_Legs_On_Exercise_Ball',
  Crunches: 'Crunches',
  'Cuban Press': 'Cuban_Press',
  "Dancer's Stretch": 'Dancers_Stretch',
  'Deadlift with Bands': 'Deadlift_with_Bands',
  'Deadlift with Chains': 'Deadlift_with_Chains',
  'Decline Barbell Bench Press': 'Decline_Barbell_Bench_Press',
  'Decline Close-Grip Bench To Skull Crusher': 'Decline_Close-Grip_Bench_To_Skull_Crusher',
  'Decline Crunch': 'Decline_Crunch',
  'Decline Dumbbell Bench Press': 'Decline_Dumbbell_Bench_Press',
  'Decline Dumbbell Flyes': 'Decline_Dumbbell_Flyes',
  'Decline Dumbbell Triceps Extension': 'Decline_Dumbbell_Triceps_Extension',
  'Decline EZ Bar Triceps Extension': 'Decline_EZ_Bar_Triceps_Extension',
  'Decline Oblique Crunch': 'Decline_Oblique_Crunch',
  'Decline Push-Up': 'Decline_Push-Up',
  'Decline Reverse Crunch': 'Decline_Reverse_Crunch',
  'Decline Smith Press': 'Decline_Smith_Press',
  'Deficit Deadlift': 'Deficit_Deadlift',
  'Depth Jump Leap': 'Depth_Jump_Leap',
  'Dip Machine': 'Dip_Machine',
  'Dips - Chest Version': 'Dips_-_Chest_Version',
  'Dips - Triceps Version': 'Dips_-_Triceps_Version',
  'Donkey Calf Raises': 'Donkey_Calf_Raises',
  'Double Kettlebell Alternating Hang Clean': 'Double_Kettlebell_Alternating_Hang_Clean',
  'Double Kettlebell Jerk': 'Double_Kettlebell_Jerk',
  'Double Kettlebell Push Press': 'Double_Kettlebell_Push_Press',
  'Double Kettlebell Snatch': 'Double_Kettlebell_Snatch',
  'Double Kettlebell Windmill': 'Double_Kettlebell_Windmill',
  'Double Leg Butt Kick': 'Double_Leg_Butt_Kick',
  'Downward Facing Balance': 'Downward_Facing_Balance',
  'Drag Curl': 'Drag_Curl',
  'Drop Push': 'Drop_Push',
  'Dumbbell Alternate Bicep Curl': 'Dumbbell_Alternate_Bicep_Curl',
  'Dumbbell Bench Press': 'Dumbbell_Bench_Press',
  'Dumbbell Bench Press with Neutral Grip': 'Dumbbell_Bench_Press_with_Neutral_Grip',
  'Dumbbell Bicep Curl': 'Dumbbell_Bicep_Curl',
  'Dumbbell Clean': 'Dumbbell_Clean',
  'Dumbbell Floor Press': 'Dumbbell_Floor_Press',
  'Dumbbell Flyes': 'Dumbbell_Flyes',
  'Dumbbell Incline Row': 'Dumbbell_Incline_Row',
  'Dumbbell Incline Shoulder Raise': 'Dumbbell_Incline_Shoulder_Raise',
  'Dumbbell Lunges': 'Dumbbell_Lunges',
  'Dumbbell Lying One-Arm Rear Lateral Raise': 'Dumbbell_Lying_One-Arm_Rear_Lateral_Raise',
  'Dumbbell Lying Pronation': 'Dumbbell_Lying_Pronation',
  'Dumbbell Lying Rear Lateral Raise': 'Dumbbell_Lying_Rear_Lateral_Raise',
  'Dumbbell Lying Supination': 'Dumbbell_Lying_Supination',
  'Dumbbell One-Arm Shoulder Press': 'Dumbbell_One-Arm_Shoulder_Press',
  'Dumbbell One-Arm Triceps Extension': 'Dumbbell_One-Arm_Triceps_Extension',
  'Dumbbell One-Arm Upright Row': 'Dumbbell_One-Arm_Upright_Row',
  'Dumbbell Prone Incline Curl': 'Dumbbell_Prone_Incline_Curl',
  'Dumbbell Raise': 'Dumbbell_Raise',
  'Dumbbell Rear Lunge': 'Dumbbell_Rear_Lunge',
  'Dumbbell Scaption': 'Dumbbell_Scaption',
  'Dumbbell Seated Box Jump': 'Dumbbell_Seated_Box_Jump',
  'Dumbbell Seated One-Leg Calf Raise': 'Dumbbell_Seated_One-Leg_Calf_Raise',
  'Dumbbell Shoulder Press': 'Dumbbell_Shoulder_Press',
  'Dumbbell Shrug': 'Dumbbell_Shrug',
  'Dumbbell Side Bend': 'Dumbbell_Side_Bend',
  'Dumbbell Squat': 'Dumbbell_Squat',
  'Dumbbell Squat To A Bench': 'Dumbbell_Squat_To_A_Bench',
  'Dumbbell Step Ups': 'Dumbbell_Step_Ups',
  'Dumbbell Tricep Extension -Pronated Grip': 'Dumbbell_Tricep_Extension_-Pronated_Grip',
  'Dynamic Back Stretch': 'Dynamic_Back_Stretch',
  'Dynamic Chest Stretch': 'Dynamic_Chest_Stretch',
  'EZ-Bar Curl': 'EZ-Bar_Curl',
  'EZ-Bar Skullcrusher': 'EZ-Bar_Skullcrusher',
  'Elbow Circles': 'Elbow_Circles',
  'Elbow to Knee': 'Elbow_to_Knee',
  'Elbows Back': 'Elbows_Back',
  'Elevated Back Lunge': 'Elevated_Back_Lunge',
  'Elevated Cable Rows': 'Elevated_Cable_Rows',
  'Elliptical Trainer': 'Elliptical_Trainer',
  'Exercise Ball Crunch': 'Exercise_Ball_Crunch',
  'Exercise Ball Pull-In': 'Exercise_Ball_Pull-In',
  'Extended Range One-Arm Kettlebell Floor Press': 'Extended_Range_One-Arm_Kettlebell_Floor_Press',
  'External Rotation': 'External_Rotation',
  'External Rotation with Band': 'External_Rotation_with_Band',
  'External Rotation with Cable': 'External_Rotation_with_Cable',
  'Face Pull': 'Face_Pull',
  "Farmer's Walk": 'Farmers_Walk',
  'Fast Skipping': 'Fast_Skipping',
  'Finger Curls': 'Finger_Curls',
  'Flat Bench Cable Flyes': 'Flat_Bench_Cable_Flyes',
  'Flat Bench Leg Pull-In': 'Flat_Bench_Leg_Pull-In',
  'Flat Bench Lying Leg Raise': 'Flat_Bench_Lying_Leg_Raise',
  'Flexor Incline Dumbbell Curls': 'Flexor_Incline_Dumbbell_Curls',
  'Floor Glute-Ham Raise': 'Floor_Glute-Ham_Raise',
  'Floor Press': 'Floor_Press',
  'Floor Press with Chains': 'Floor_Press_with_Chains',
  'Flutter Kicks': 'Flutter_Kicks',
  'Foot-SMR': 'Foot-SMR',
  'Forward Drag with Press': 'Forward_Drag_with_Press',
  'Frankenstein Squat': 'Frankenstein_Squat',
  'Freehand Jump Squat': 'Freehand_Jump_Squat',
  'Frog Hops': 'Frog_Hops',
  'Frog Sit-Ups': 'Frog_Sit-Ups',
  'Front Barbell Squat': 'Front_Barbell_Squat',
  'Front Barbell Squat To A Bench': 'Front_Barbell_Squat_To_A_Bench',
  'Front Box Jump': 'Front_Box_Jump',
  'Front Cable Raise': 'Front_Cable_Raise',
  'Front Cone Hops (or hurdle hops)': 'Front_Cone_Hops_or_hurdle_hops',
  'Front Dumbbell Raise': 'Front_Dumbbell_Raise',
  'Front Incline Dumbbell Raise': 'Front_Incline_Dumbbell_Raise',
  'Front Leg Raises': 'Front_Leg_Raises',
  'Front Plate Raise': 'Front_Plate_Raise',
  'Front Raise And Pullover': 'Front_Raise_And_Pullover',
  'Front Squat (Clean Grip)': 'Front_Squat_Clean_Grip',
  'Front Squats With Two Kettlebells': 'Front_Squats_With_Two_Kettlebells',
  'Front Two-Dumbbell Raise': 'Front_Two-Dumbbell_Raise',
  'Full Range-Of-Motion Lat Pulldown': 'Full_Range-Of-Motion_Lat_Pulldown',
  'Gironda Sternum Chins': 'Gironda_Sternum_Chins',
  'Glute Kickback': 'Glute_Kickback',
  'Good Morning': 'Good_Morning',
  'Good Morning off Pins': 'Good_Morning_off_Pins',
  'Gorilla Chin/Crunch': 'Gorilla_Chin_Crunch',
  'Groin and Back Stretch': 'Groin_and_Back_Stretch',
  Groiners: 'Groiners',
  'Hack Squat': 'Hack_Squat',
  'Hammer Curls': 'Hammer_Curls',
  'Hammer Grip Incline DB Bench Press': 'Hammer_Grip_Incline_DB_Bench_Press',
  'Hamstring-SMR': 'Hamstring-SMR',
  'Hamstring Stretch': 'Seated_Floor_Hamstring_Stretch',
  'Handstand Push-Ups': 'Handstand_Push-Ups',
  'Hang Clean': 'Hang_Clean',
  'Hang Clean - Below the Knees': 'Hang_Clean_-_Below_the_Knees',
  'Hang Snatch': 'Hang_Snatch',
  'Hang Snatch - Below Knees': 'Hang_Snatch_-_Below_Knees',
  'Hanging Bar Good Morning': 'Hanging_Bar_Good_Morning',
  'Hanging Pike': 'Hanging_Pike',
  'Heaving Snatch Balance': 'Heaving_Snatch_Balance',
  'Heavy Bag Thrust': 'Heavy_Bag_Thrust',
  'High Cable Curls': 'High_Cable_Curls',
  'Hip Circles (prone)': 'Hip_Circles_prone',
  'Hip Extension with Bands': 'Hip_Extension_with_Bands',
  'Hip Flexion with Band': 'Hip_Flexion_with_Band',
  'Hip Lift with Band': 'Hip_Lift_with_Band',
  'Hug A Ball': 'Hug_A_Ball',
  'Hug Knees To Chest': 'Hug_Knees_To_Chest',
  'Hurdle Hops': 'Hurdle_Hops',
  'Hyperextensions (Back Extensions)': 'Hyperextensions_Back_Extensions',
  'Hyperextensions With No Hyperextension Bench': 'Hyperextensions_With_No_Hyperextension_Bench',
  'IT Band and Glute Stretch': 'IT_Band_and_Glute_Stretch',
  'Iliotibial Tract-SMR': 'Iliotibial_Tract-SMR',
  'Incline Barbell Triceps Extension': 'Incline_Barbell_Triceps_Extension',
  'Incline Bench Pull': 'Incline_Bench_Pull',
  'Incline Cable Chest Press': 'Incline_Cable_Chest_Press',
  'Incline Cable Flye': 'Incline_Cable_Flye',
  'Incline Dumbbell Bench With Palms Facing In': 'Incline_Dumbbell_Bench_With_Palms_Facing_In',
  'Incline Dumbbell Curl': 'Incline_Dumbbell_Curl',
  'Incline Dumbbell Flyes': 'Incline_Dumbbell_Flyes',
  'Incline Dumbbell Flyes - With A Twist': 'Incline_Dumbbell_Flyes_-_With_A_Twist',
  'Incline Dumbbell Press': 'Incline_Dumbbell_Press',
  'Incline Hammer Curls': 'Incline_Hammer_Curls',
  'Incline Inner Biceps Curl': 'Incline_Inner_Biceps_Curl',
  'Incline Push-Up': 'Incline_Push-Up',
  'Incline Push-Up Close-Grip': 'Incline_Push-Up_Close-Grip',
  'Incline Push-Up Depth Jump': 'Incline_Push-Up_Depth_Jump',
  'Incline Push-Up Medium': 'Incline_Push-Up_Medium',
  'Incline Push-Up Reverse Grip': 'Incline_Push-Up_Reverse_Grip',
  'Incline Push-Up Wide': 'Incline_Push-Up_Wide',
  'Intermediate Groin Stretch': 'Intermediate_Groin_Stretch',
  'Intermediate Hip Flexor and Quad Stretch': 'Intermediate_Hip_Flexor_and_Quad_Stretch',
  'Internal Rotation with Band': 'Internal_Rotation_with_Band',
  'Inverted Row with Straps': 'Inverted_Row_with_Straps',
  'Iron Cross': 'Iron_Cross',
  'Iron Crosses (stretch)': 'Iron_Crosses_stretch',
  'Isometric Chest Squeezes': 'Isometric_Chest_Squeezes',
  'Isometric Neck Exercise - Front And Back': 'Isometric_Neck_Exercise_-_Front_And_Back',
  'Isometric Neck Exercise - Sides': 'Isometric_Neck_Exercise_-_Sides',
  'Isometric Wipers': 'Isometric_Wipers',
  'JM Press': 'JM_Press',
  'Jackknife Sit-Up': 'Jackknife_Sit-Up',
  'Janda Sit-Up': 'Janda_Sit-Up',
  'Jefferson Squats': 'Jefferson_Squats',
  'Jerk Balance': 'Jerk_Balance',
  'Jerk Dip Squat': 'Jerk_Dip_Squat',
  'Jogging, Treadmill': 'Jogging_Treadmill',
  'Keg Load': 'Keg_Load',
  'Kettlebell Arnold Press': 'Kettlebell_Arnold_Press',
  'Kettlebell Dead Clean': 'Kettlebell_Dead_Clean',
  'Kettlebell Figure 8': 'Kettlebell_Figure_8',
  'Kettlebell Hang Clean': 'Kettlebell_Hang_Clean',
  'Kettlebell One-Legged Deadlift': 'Kettlebell_One-Legged_Deadlift',
  'Kettlebell Pass Between The Legs': 'Kettlebell_Pass_Between_The_Legs',
  'Kettlebell Pirate Ships': 'Kettlebell_Pirate_Ships',
  'Kettlebell Pistol Squat': 'Kettlebell_Pistol_Squat',
  'Kettlebell Seated Press': 'Kettlebell_Seated_Press',
  'Kettlebell Seesaw Press': 'Kettlebell_Seesaw_Press',
  'Kettlebell Sumo High Pull': 'Kettlebell_Sumo_High_Pull',
  'Kettlebell Thruster': 'Kettlebell_Thruster',
  'Kettlebell Turkish Get-Up (Lunge style)': 'Kettlebell_Turkish_Get-Up_Lunge_style',
  'Kettlebell Turkish Get-Up (Squat style)': 'Kettlebell_Turkish_Get-Up_Squat_style',
  'Kettlebell Windmill': 'Kettlebell_Windmill',
  'Kipping Muscle Up': 'Kipping_Muscle_Up',
  'Knee Across The Body': 'Knee_Across_The_Body',
  'Knee/Hip Raise On Parallel Bars': 'Knee_Hip_Raise_On_Parallel_Bars',
  'Knee Tuck Jump': 'Knee_Tuck_Jump',
  'Kneeling Arm Drill': 'Kneeling_Arm_Drill',
  'Kneeling Cable Crunch With Alternating Oblique Twists': 'Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists',
  'Kneeling Cable Triceps Extension': 'Kneeling_Cable_Triceps_Extension',
  'Kneeling Forearm Stretch': 'Kneeling_Forearm_Stretch',
  'Kneeling High Pulley Row': 'Kneeling_High_Pulley_Row',
  'Kneeling Hip Flexor': 'Kneeling_Hip_Flexor',
  'Kneeling Jump Squat': 'Kneeling_Jump_Squat',
  'Kneeling Single-Arm High Pulley Row': 'Kneeling_Single-Arm_High_Pulley_Row',
  'Kneeling Squat': 'Kneeling_Squat',
  "Landmine 180's": 'Landmine_180s',
  'Landmine Linear Jammer': 'Landmine_Linear_Jammer',
  'Lateral Box Jump': 'Lateral_Box_Jump',
  'Lateral Cone Hops': 'Lateral_Cone_Hops',
  'Lateral Raise - With Bands': 'Lateral_Raise_-_With_Bands',
  'Latissimus Dorsi-SMR': 'Latissimus_Dorsi-SMR',
  'Leg-Over Floor Press': 'Leg-Over_Floor_Press',
  'Leg-Up Hamstring Stretch': 'Leg-Up_Hamstring_Stretch',
  'Leg Extensions': 'Leg_Extensions',
  'Leg Lift': 'Leg_Lift',
  'Leg Press': 'Leg_Press',
  'Leg Pull-In': 'Leg_Pull-In',
  'Leverage Chest Press': 'Leverage_Chest_Press',
  'Leverage Deadlift': 'Leverage_Deadlift',
  'Leverage Decline Chest Press': 'Leverage_Decline_Chest_Press',
  'Leverage High Row': 'Leverage_High_Row',
  'Leverage Incline Chest Press': 'Leverage_Incline_Chest_Press',
  'Leverage Iso Row': 'Leverage_Iso_Row',
  'Leverage Shoulder Press': 'Leverage_Shoulder_Press',
  'Leverage Shrug': 'Leverage_Shrug',
  'Linear 3-Part Start Technique': 'Linear_3-Part_Start_Technique',
  'Linear Acceleration Wall Drill': 'Linear_Acceleration_Wall_Drill',
  'Linear Depth Jump': 'Linear_Depth_Jump',
  'Log Lift': 'Log_Lift',
  'London Bridges': 'London_Bridges',
  'Looking At Ceiling': 'Looking_At_Ceiling',
  'Low Cable Crossover': 'Low_Cable_Crossover',
  'Low Cable Triceps Extension': 'Low_Cable_Triceps_Extension',
  'Low Pulley Row To Neck': 'Low_Pulley_Row_To_Neck',
  'Lower Back-SMR': 'Lower_Back-SMR',
  'Lower Back Curl': 'Lower_Back_Curl',
  'Lunge Pass Through': 'Lunge_Pass_Through',
  'Lunge Sprint': 'Lunge_Sprint',
  'Lying Bent Leg Groin': 'Lying_Bent_Leg_Groin',
  'Lying Cable Curl': 'Lying_Cable_Curl',
  'Lying Cambered Barbell Row': 'Lying_Cambered_Barbell_Row',
  'Lying Close-Grip Bar Curl On High Pulley': 'Lying_Close-Grip_Bar_Curl_On_High_Pulley',
  'Lying Close-Grip Barbell Triceps Extension Behind The Head':
    'Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head',
  'Lying Close-Grip Barbell Triceps Press To Chin': 'Lying_Close-Grip_Barbell_Triceps_Press_To_Chin',
  'Lying Crossover': 'Lying_Crossover',
  'Lying Dumbbell Tricep Extension': 'Lying_Dumbbell_Tricep_Extension',
  'Lying Face Down Plate Neck Resistance': 'Lying_Face_Down_Plate_Neck_Resistance',
  'Lying Face Up Plate Neck Resistance': 'Lying_Face_Up_Plate_Neck_Resistance',
  'Lying Glute': 'Lying_Glute',
  'Lying Hamstring': 'Lying_Hamstring',
  'Lying High Bench Barbell Curl': 'Lying_High_Bench_Barbell_Curl',
  'Lying Leg Curls': 'Lying_Leg_Curls',
  'Lying Machine Squat': 'Lying_Machine_Squat',
  'Lying One-Arm Lateral Raise': 'Lying_One-Arm_Lateral_Raise',
  'Lying Prone Quadriceps': 'Lying_Prone_Quadriceps',
  'Lying Rear Delt Raise': 'Lying_Rear_Delt_Raise',
  'Lying Supine Dumbbell Curl': 'Lying_Supine_Dumbbell_Curl',
  'Lying T-Bar Row': 'Lying_T-Bar_Row',
  'Lying Triceps Press': 'Lying_Triceps_Press',
  'Machine Bench Press': 'Machine_Bench_Press',
  'Machine Bicep Curl': 'Machine_Bicep_Curl',
  'Machine Preacher Curls': 'Machine_Preacher_Curls',
  'Machine Shoulder (Military) Press': 'Machine_Shoulder_Military_Press',
  'Machine Triceps Extension': 'Machine_Triceps_Extension',
  'Medicine Ball Chest Pass': 'Medicine_Ball_Chest_Pass',
  'Medicine Ball Full Twist': 'Medicine_Ball_Full_Twist',
  'Medicine Ball Scoop Throw': 'Medicine_Ball_Scoop_Throw',
  'Middle Back Shrug': 'Middle_Back_Shrug',
  'Middle Back Stretch': 'Middle_Back_Stretch',
  'Mixed Grip Chin': 'Mixed_Grip_Chin',
  'Monster Walk': 'Monster_Walk',
  'Moving Claw Series': 'Moving_Claw_Series',
  'Muscle Snatch': 'Muscle_Snatch',
  'Muscle Up': 'Muscle_Up',
  'Narrow Stance Hack Squats': 'Narrow_Stance_Hack_Squats',
  'Narrow Stance Leg Press': 'Narrow_Stance_Leg_Press',
  'Narrow Stance Squats': 'Narrow_Stance_Squats',
  'Natural Glute Ham Raise': 'Natural_Glute_Ham_Raise',
  'Neck-SMR': 'Neck-SMR',
  'Neck Press': 'Neck_Press',
  'Oblique Crunches': 'Oblique_Crunches',
  'Oblique Crunches - On The Floor': 'Oblique_Crunches_-_On_The_Floor',
  'Olympic Squat': 'Olympic_Squat',
  'On-Your-Back Quad Stretch': 'On-Your-Back_Quad_Stretch',
  'On Your Side Quad Stretch': 'On_Your_Side_Quad_Stretch',
  'One-Arm Dumbbell Row': 'One-Arm_Dumbbell_Row',
  'One-Arm Flat Bench Dumbbell Flye': 'One-Arm_Flat_Bench_Dumbbell_Flye',
  'One-Arm High-Pulley Cable Side Bends': 'One-Arm_High-Pulley_Cable_Side_Bends',
  'One-Arm Incline Lateral Raise': 'One-Arm_Incline_Lateral_Raise',
  'One-Arm Kettlebell Clean': 'One-Arm_Kettlebell_Clean',
  'One-Arm Kettlebell Clean and Jerk': 'One-Arm_Kettlebell_Clean_and_Jerk',
  'One-Arm Kettlebell Floor Press': 'One-Arm_Kettlebell_Floor_Press',
  'One-Arm Kettlebell Jerk': 'One-Arm_Kettlebell_Jerk',
  'One-Arm Kettlebell Military Press To The Side': 'One-Arm_Kettlebell_Military_Press_To_The_Side',
  'One-Arm Kettlebell Para Press': 'One-Arm_Kettlebell_Para_Press',
  'One-Arm Kettlebell Push Press': 'One-Arm_Kettlebell_Push_Press',
  'One-Arm Kettlebell Row': 'One-Arm_Kettlebell_Row',
  'One-Arm Kettlebell Snatch': 'One-Arm_Kettlebell_Snatch',
  'One-Arm Kettlebell Split Jerk': 'One-Arm_Kettlebell_Split_Jerk',
  'One-Arm Kettlebell Split Snatch': 'One-Arm_Kettlebell_Split_Snatch',
  'One-Arm Kettlebell Swings': 'One-Arm_Kettlebell_Swings',
  'One-Arm Long Bar Row': 'One-Arm_Long_Bar_Row',
  'One-Arm Medicine Ball Slam': 'One-Arm_Medicine_Ball_Slam',
  'One-Arm Open Palm Kettlebell Clean': 'One-Arm_Open_Palm_Kettlebell_Clean',
  'One-Arm Overhead Kettlebell Squats': 'One-Arm_Overhead_Kettlebell_Squats',
  'One-Arm Side Deadlift': 'One-Arm_Side_Deadlift',
  'One-Arm Side Laterals': 'One-Arm_Side_Laterals',
  'One-Legged Cable Kickback': 'One-Legged_Cable_Kickback',
  'One Arm Against Wall': 'One_Arm_Against_Wall',
  'One Arm Chin-Up': 'One_Arm_Chin-Up',
  'One Arm Dumbbell Bench Press': 'One_Arm_Dumbbell_Bench_Press',
  'One Arm Dumbbell Preacher Curl': 'One_Arm_Dumbbell_Preacher_Curl',
  'One Arm Floor Press': 'One_Arm_Floor_Press',
  'One Arm Lat Pulldown': 'One_Arm_Lat_Pulldown',
  'One Arm Pronated Dumbbell Triceps Extension': 'One_Arm_Pronated_Dumbbell_Triceps_Extension',
  'One Arm Supinated Dumbbell Triceps Extension': 'One_Arm_Supinated_Dumbbell_Triceps_Extension',
  'One Half Locust': 'One_Half_Locust',
  'One Handed Hang': 'One_Handed_Hang',
  'One Knee To Chest': 'One_Knee_To_Chest',
  'One Leg Barbell Squat': 'One_Leg_Barbell_Squat',
  'Open Palm Kettlebell Clean': 'Open_Palm_Kettlebell_Clean',
  'Otis-Up': 'Otis-Up',
  'Overhead Cable Curl': 'Overhead_Cable_Curl',
  'Overhead Lat': 'Overhead_Lat',
  'Overhead Slam': 'Overhead_Slam',
  'Overhead Squat': 'Overhead_Squat',
  'Overhead Stretch': 'Overhead_Stretch',
  'Overhead Triceps': 'Overhead_Triceps',
  'Pallof Press With Rotation': 'Pallof_Press_With_Rotation',
  'Palms-Down Dumbbell Wrist Curl Over A Bench': 'Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench',
  'Palms-Down Wrist Curl Over A Bench': 'Palms-Down_Wrist_Curl_Over_A_Bench',
  'Palms-Up Barbell Wrist Curl Over A Bench': 'Palms-Up_Barbell_Wrist_Curl_Over_A_Bench',
  'Palms-Up Dumbbell Wrist Curl Over A Bench': 'Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench',
  'Parallel Bar Dip': 'Parallel_Bar_Dip',
  'Pelvic Tilt Into Bridge': 'Pelvic_Tilt_Into_Bridge',
  'Peroneals-SMR': 'Peroneals-SMR',
  'Peroneals Stretch': 'Peroneals_Stretch',
  'Physioball Hip Bridge': 'Physioball_Hip_Bridge',
  'Pin Presses': 'Pin_Presses',
  'Piriformis-SMR': 'Piriformis-SMR',
  'Plate Pinch': 'Plate_Pinch',
  'Plate Twist': 'Plate_Twist',
  'Platform Hamstring Slides': 'Platform_Hamstring_Slides',
  'Plie Dumbbell Squat': 'Plie_Dumbbell_Squat',
  'Plyo Kettlebell Pushups': 'Plyo_Kettlebell_Pushups',
  'Posterior Tibialis Stretch': 'Posterior_Tibialis_Stretch',
  'Power Clean': 'Power_Clean',
  'Power Clean from Blocks': 'Power_Clean_from_Blocks',
  'Power Jerk': 'Power_Jerk',
  'Power Partials': 'Power_Partials',
  'Power Snatch': 'Power_Snatch',
  'Power Snatch from Blocks': 'Power_Snatch_from_Blocks',
  'Power Stairs': 'Power_Stairs',
  'Preacher Curl': 'Preacher_Curl',
  'Preacher Hammer Dumbbell Curl': 'Preacher_Hammer_Dumbbell_Curl',
  'Press Sit-Up': 'Press_Sit-Up',
  'Prone Manual Hamstring': 'Prone_Manual_Hamstring',
  'Prowler Sprint': 'Prowler_Sprint',
  'Pull Through': 'Pull_Through',
  Pullups: 'Pullups',
  'Push-Up Wide': 'Push-Up_Wide',
  'Push-Ups - Close Triceps Position': 'Push-Ups_-_Close_Triceps_Position',
  'Push-Ups With Feet Elevated': 'Push-Ups_With_Feet_Elevated',
  'Push-Ups With Feet On An Exercise Ball': 'Push-Ups_With_Feet_On_An_Exercise_Ball',
  'Push Press': 'Push_Press',
  'Push Press - Behind the Neck': 'Push_Press_-_Behind_the_Neck',
  'Push Up to Side Plank': 'Push_Up_to_Side_Plank',
  Pushups: 'Pushups',
  'Pushups (Close and Wide Hand Positions)': 'Pushups_Close_and_Wide_Hand_Positions',
  Pyramid: 'Pyramid',
  'Quad Stretch': 'Quad_Stretch',
  'Quadriceps-SMR': 'Quadriceps-SMR',
  'Quick Leap': 'Quick_Leap',
  'Rack Delivery': 'Rack_Delivery',
  'Rack Pull with Bands': 'Rack_Pull_with_Bands',
  'Rack Pulls': 'Rack_Pulls',
  'Rear Leg Raises': 'Rear_Leg_Raises',
  'Recumbent Bike': 'Recumbent_Bike',
  'Return Push from Stance': 'Return_Push_from_Stance',
  'Reverse Band Bench Press': 'Reverse_Band_Bench_Press',
  'Reverse Band Box Squat': 'Reverse_Band_Box_Squat',
  'Reverse Band Deadlift': 'Reverse_Band_Deadlift',
  'Reverse Band Power Squat': 'Reverse_Band_Power_Squat',
  'Reverse Band Sumo Deadlift': 'Reverse_Band_Sumo_Deadlift',
  'Reverse Barbell Curl': 'Reverse_Barbell_Curl',
  'Reverse Barbell Preacher Curls': 'Reverse_Barbell_Preacher_Curls',
  'Reverse Cable Curl': 'Reverse_Cable_Curl',
  'Reverse Crunch': 'Reverse_Crunch',
  'Reverse Flyes': 'Reverse_Flyes',
  'Reverse Flyes With External Rotation': 'Reverse_Flyes_With_External_Rotation',
  'Reverse Grip Bent-Over Rows': 'Reverse_Grip_Bent-Over_Rows',
  'Reverse Grip Triceps Pushdown': 'Reverse_Grip_Triceps_Pushdown',
  'Reverse Hyperextension': 'Reverse_Hyperextension',
  'Reverse Machine Flyes': 'Reverse_Machine_Flyes',
  'Reverse Plate Curls': 'Reverse_Plate_Curls',
  'Reverse Triceps Bench Press': 'Reverse_Triceps_Bench_Press',
  'Rhomboids-SMR': 'Rhomboids-SMR',
  'Rickshaw Carry': 'Rickshaw_Carry',
  'Rickshaw Deadlift': 'Rickshaw_Deadlift',
  'Ring Dips': 'Ring_Dips',
  'Rocket Jump': 'Rocket_Jump',
  'Rocking Standing Calf Raise': 'Rocking_Standing_Calf_Raise',
  'Rocky Pull-Ups/Pulldowns': 'Rocky_Pull-Ups_Pulldowns',
  'Romanian Deadlift': 'Romanian_Deadlift',
  'Romanian Deadlift from Deficit': 'Romanian_Deadlift_from_Deficit',
  'Rope Climb': 'Rope_Climb',
  'Rope Crunch': 'Rope_Crunch',
  'Rope Jumping': 'Rope_Jumping',
  'Rope Straight-Arm Pulldown': 'Rope_Straight-Arm_Pulldown',
  'Round The World Shoulder Stretch': 'Round_The_World_Shoulder_Stretch',
  'Rowing, Stationary': 'Rowing_Stationary',
  "Runner's Stretch": 'Runners_Stretch',
  'Running, Treadmill': 'Running_Treadmill',
  'Sandbag Load': 'Sandbag_Load',
  'Scapular Pull-Up': 'Scapular_Pull-Up',
  'Scissor Kick': 'Scissor_Kick',
  'Scissors Jump': 'Scissors_Jump',
  'Seated Band Hamstring Curl': 'Seated_Band_Hamstring_Curl',
  'Seated Barbell Military Press': 'Seated_Barbell_Military_Press',
  'Seated Barbell Twist': 'Seated_Barbell_Twist',
  'Seated Bent-Over One-Arm Dumbbell Triceps Extension': 'Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension',
  'Seated Bent-Over Rear Delt Raise': 'Seated_Bent-Over_Rear_Delt_Raise',
  'Seated Bent-Over Two-Arm Dumbbell Triceps Extension': 'Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension',
  'Seated Biceps': 'Seated_Biceps',
  'Seated Cable Rows': 'Seated_Cable_Rows',
  'Seated Cable Shoulder Press': 'Seated_Cable_Shoulder_Press',
  'Seated Calf Raise': 'Seated_Calf_Raise',
  'Seated Calf Stretch': 'Seated_Calf_Stretch',
  'Seated Close-Grip Concentration Barbell Curl': 'Seated_Close-Grip_Concentration_Barbell_Curl',
  'Seated Dumbbell Curl': 'Seated_Dumbbell_Curl',
  'Seated Dumbbell Inner Biceps Curl': 'Seated_Dumbbell_Inner_Biceps_Curl',
  'Seated Dumbbell Palms-Down Wrist Curl': 'Seated_Dumbbell_Palms-Down_Wrist_Curl',
  'Seated Dumbbell Palms-Up Wrist Curl': 'Seated_Dumbbell_Palms-Up_Wrist_Curl',
  'Seated Dumbbell Press': 'Seated_Dumbbell_Press',
  'Seated Flat Bench Leg Pull-In': 'Seated_Flat_Bench_Leg_Pull-In',
  'Seated Floor Hamstring Stretch': 'Seated_Floor_Hamstring_Stretch',
  'Seated Front Deltoid': 'Seated_Front_Deltoid',
  'Seated Glute': 'Seated_Glute',
  'Seated Good Mornings': 'Seated_Good_Mornings',
  'Seated Hamstring': 'Seated_Hamstring',
  'Seated Hamstring and Calf Stretch': 'Seated_Hamstring_and_Calf_Stretch',
  'Seated Head Harness Neck Resistance': 'Seated_Head_Harness_Neck_Resistance',
  'Seated Leg Curl': 'Seated_Leg_Curl',
  'Seated Leg Tucks': 'Seated_Leg_Tucks',
  'Seated One-Arm Dumbbell Palms-Down Wrist Curl': 'Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl',
  'Seated One-Arm Dumbbell Palms-Up Wrist Curl': 'Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl',
  'Seated One-arm Cable Pulley Rows': 'Seated_One-arm_Cable_Pulley_Rows',
  'Seated Overhead Stretch': 'Seated_Overhead_Stretch',
  'Seated Palm-Up Barbell Wrist Curl': 'Seated_Palm-Up_Barbell_Wrist_Curl',
  'Seated Palms-Down Barbell Wrist Curl': 'Seated_Palms-Down_Barbell_Wrist_Curl',
  'Seated Side Lateral Raise': 'Seated_Side_Lateral_Raise',
  'Seated Triceps Press': 'Seated_Triceps_Press',
  'Seated Two-Arm Palms-Up Low-Pulley Wrist Curl': 'Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl',
  'See-Saw Press (Alternating Side Press)': 'See-Saw_Press_Alternating_Side_Press',
  'Shotgun Row': 'Shotgun_Row',
  'Shoulder Press - With Bands': 'Shoulder_Press_-_With_Bands',
  'Shoulder Raise': 'Shoulder_Raise',
  'Shoulder Stretch': 'Shoulder_Stretch',
  'Side-Lying Floor Stretch': 'Side-Lying_Floor_Stretch',
  'Side Bridge': 'Side_Bridge',
  'Side Hop-Sprint': 'Side_Hop-Sprint',
  'Side Jackknife': 'Side_Jackknife',
  'Side Lateral Raise': 'Side_Lateral_Raise',
  'Side Laterals to Front Raise': 'Side_Laterals_to_Front_Raise',
  'Side Leg Raises': 'Side_Leg_Raises',
  'Side Lying Groin Stretch': 'Side_Lying_Groin_Stretch',
  'Side Neck Stretch': 'Side_Neck_Stretch',
  'Side Standing Long Jump': 'Side_Standing_Long_Jump',
  'Side To Side Chins': 'Side_To_Side_Chins',
  'Side Wrist Pull': 'Side_Wrist_Pull',
  'Side to Side Box Shuffle': 'Side_to_Side_Box_Shuffle',
  'Single-Arm Cable Crossover': 'Single-Arm_Cable_Crossover',
  'Single-Arm Linear Jammer': 'Single-Arm_Linear_Jammer',
  'Single-Arm Push-Up': 'Single-Arm_Push-Up',
  'Single-Cone Sprint Drill': 'Single-Cone_Sprint_Drill',
  'Single-Leg High Box Squat': 'Single-Leg_High_Box_Squat',
  'Single-Leg Hop Progression': 'Single-Leg_Hop_Progression',
  'Single-Leg Lateral Hop': 'Single-Leg_Lateral_Hop',
  'Single-Leg Leg Extension': 'Single-Leg_Leg_Extension',
  'Single-Leg Stride Jump': 'Single-Leg_Stride_Jump',
  'Single Dumbbell Raise': 'Single_Dumbbell_Raise',
  'Single Leg Butt Kick': 'Single_Leg_Butt_Kick',
  'Single Leg Glute Bridge': 'Single_Leg_Glute_Bridge',
  'Single Leg Push-off': 'Single_Leg_Push-off',
  'Sit-Up': 'Sit-Up',
  'Sit Squats': 'Sit_Squats',
  Skating: 'Skating',
  'Sled Drag - Harness': 'Sled_Drag_-_Harness',
  'Sled Overhead Backward Walk': 'Sled_Overhead_Backward_Walk',
  'Sled Overhead Triceps Extension': 'Sled_Overhead_Triceps_Extension',
  'Sled Push': 'Sled_Push',
  'Sled Reverse Flye': 'Sled_Reverse_Flye',
  'Sled Row': 'Sled_Row',
  'Sledgehammer Swings': 'Sledgehammer_Swings',
  'Smith Incline Shoulder Raise': 'Smith_Incline_Shoulder_Raise',
  'Smith Machine Behind the Back Shrug': 'Smith_Machine_Behind_the_Back_Shrug',
  'Smith Machine Bench Press': 'Smith_Machine_Bench_Press',
  'Smith Machine Bent Over Row': 'Smith_Machine_Bent_Over_Row',
  'Smith Machine Calf Raise': 'Smith_Machine_Calf_Raise',
  'Smith Machine Close-Grip Bench Press': 'Smith_Machine_Close-Grip_Bench_Press',
  'Smith Machine Decline Press': 'Smith_Machine_Decline_Press',
  'Smith Machine Hang Power Clean': 'Smith_Machine_Hang_Power_Clean',
  'Smith Machine Hip Raise': 'Smith_Machine_Hip_Raise',
  'Smith Machine Incline Bench Press': 'Smith_Machine_Incline_Bench_Press',
  'Smith Machine Leg Press': 'Smith_Machine_Leg_Press',
  'Smith Machine One-Arm Upright Row': 'Smith_Machine_One-Arm_Upright_Row',
  'Smith Machine Overhead Shoulder Press': 'Smith_Machine_Overhead_Shoulder_Press',
  'Smith Machine Pistol Squat': 'Smith_Machine_Pistol_Squat',
  'Smith Machine Reverse Calf Raises': 'Smith_Machine_Reverse_Calf_Raises',
  'Smith Machine Squat': 'Smith_Machine_Squat',
  'Smith Machine Stiff-Legged Deadlift': 'Smith_Machine_Stiff-Legged_Deadlift',
  'Smith Machine Upright Row': 'Smith_Machine_Upright_Row',
  'Smith Single-Leg Split Squat': 'Smith_Single-Leg_Split_Squat',
  Snatch: 'Snatch',
  'Snatch Balance': 'Snatch_Balance',
  'Snatch Deadlift': 'Snatch_Deadlift',
  'Snatch Pull': 'Snatch_Pull',
  'Snatch Shrug': 'Snatch_Shrug',
  'Snatch from Blocks': 'Snatch_from_Blocks',
  'Speed Band Overhead Triceps': 'Speed_Band_Overhead_Triceps',
  'Speed Box Squat': 'Speed_Box_Squat',
  'Speed Squats': 'Speed_Squats',
  'Spell Caster': 'Spell_Caster',
  'Spider Crawl': 'Spider_Crawl',
  'Spider Curl': 'Spider_Curl',
  'Spinal Stretch': 'Spinal_Stretch',
  'Split Clean': 'Split_Clean',
  'Split Jerk': 'Split_Jerk',
  'Split Snatch': 'Split_Snatch',
  'Split Squat with Dumbbells': 'Split_Squat_with_Dumbbells',
  'Split Squats': 'Split_Squats',
  'Squat Jerk': 'Squat_Jerk',
  'Squat with Bands': 'Squat_with_Bands',
  'Squat with Chains': 'Squat_with_Chains',
  'Squat with Plate Movers': 'Squat_with_Plate_Movers',
  'Squats - With Bands': 'Squats_-_With_Bands',
  Stairmaster: 'Stairmaster',
  'Standing Alternating Dumbbell Press': 'Standing_Alternating_Dumbbell_Press',
  'Standing Barbell Calf Raise': 'Standing_Barbell_Calf_Raise',
  'Standing Barbell Press Behind Neck': 'Standing_Barbell_Press_Behind_Neck',
  'Standing Bent-Over One-Arm Dumbbell Triceps Extension': 'Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension',
  'Standing Bent-Over Two-Arm Dumbbell Triceps Extension': 'Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension',
  'Standing Biceps Cable Curl': 'Standing_Biceps_Cable_Curl',
  'Standing Biceps Stretch': 'Standing_Biceps_Stretch',
  'Standing Bradford Press': 'Standing_Bradford_Press',
  'Standing Cable Chest Press': 'Standing_Cable_Chest_Press',
  'Standing Cable Lift': 'Standing_Cable_Lift',
  'Standing Cable Wood Chop': 'Standing_Cable_Wood_Chop',
  'Standing Calf Raises': 'Standing_Calf_Raises',
  'Standing Concentration Curl': 'Standing_Concentration_Curl',
  'Standing Dumbbell Calf Raise': 'Standing_Dumbbell_Calf_Raise',
  'Standing Dumbbell Press': 'Standing_Dumbbell_Press',
  'Standing Dumbbell Reverse Curl': 'Standing_Dumbbell_Reverse_Curl',
  'Standing Dumbbell Straight-Arm Front Delt Raise Above Head':
    'Standing_Dumbbell_Straight-Arm_Front_Delt_Raise_Above_Head',
  'Standing Dumbbell Triceps Extension': 'Standing_Dumbbell_Triceps_Extension',
  'Standing Dumbbell Upright Row': 'Standing_Dumbbell_Upright_Row',
  'Standing Elevated Quad Stretch': 'Standing_Elevated_Quad_Stretch',
  'Standing Front Barbell Raise Over Head': 'Standing_Front_Barbell_Raise_Over_Head',
  'Standing Gastrocnemius Calf Stretch': 'Standing_Gastrocnemius_Calf_Stretch',
  'Standing Hamstring and Calf Stretch': 'Standing_Hamstring_and_Calf_Stretch',
  'Standing Hip Circles': 'Standing_Hip_Circles',
  'Standing Hip Flexors': 'Standing_Hip_Flexors',
  'Standing Inner-Biceps Curl': 'Standing_Inner-Biceps_Curl',
  'Standing Lateral Stretch': 'Standing_Lateral_Stretch',
  'Standing Leg Curl': 'Standing_Leg_Curl',
  'Standing Long Jump': 'Standing_Long_Jump',
  'Standing Low-Pulley Deltoid Raise': 'Standing_Low-Pulley_Deltoid_Raise',
  'Standing Low-Pulley One-Arm Triceps Extension': 'Standing_Low-Pulley_One-Arm_Triceps_Extension',
  'Standing Military Press': 'Standing_Military_Press',
  'Standing Olympic Plate Hand Squeeze': 'Standing_Olympic_Plate_Hand_Squeeze',
  'Standing One-Arm Cable Curl': 'Standing_One-Arm_Cable_Curl',
  'Standing One-Arm Dumbbell Curl Over Incline Bench': 'Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench',
  'Standing One-Arm Dumbbell Triceps Extension': 'Standing_One-Arm_Dumbbell_Triceps_Extension',
  'Standing Overhead Barbell Triceps Extension': 'Standing_Overhead_Barbell_Triceps_Extension',
  'Standing Palm-In One-Arm Dumbbell Press': 'Standing_Palm-In_One-Arm_Dumbbell_Press',
  'Standing Palms-In Dumbbell Press': 'Standing_Palms-In_Dumbbell_Press',
  'Standing Palms-Up Barbell Behind The Back Wrist Curl': 'Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl',
  'Standing Pelvic Tilt': 'Standing_Pelvic_Tilt',
  'Standing Rope Crunch': 'Standing_Rope_Crunch',
  'Standing Soleus And Achilles Stretch': 'Standing_Soleus_And_Achilles_Stretch',
  'Standing Toe Touches': 'Standing_Toe_Touches',
  'Standing Towel Triceps Extension': 'Standing_Towel_Triceps_Extension',
  'Standing Two-Arm Overhead Throw': 'Standing_Two-Arm_Overhead_Throw',
  'Step-up with Knee Raise': 'Step-up_with_Knee_Raise',
  'Step Mill': 'Step_Mill',
  'Stiff-Legged Barbell Deadlift': 'Stiff-Legged_Barbell_Deadlift',
  'Stiff-Legged Dumbbell Deadlift': 'Stiff-Legged_Dumbbell_Deadlift',
  'Stiff Leg Barbell Good Morning': 'Stiff_Leg_Barbell_Good_Morning',
  'Stomach Vacuum': 'Stomach_Vacuum',
  'Straight-Arm Dumbbell Pullover': 'Straight-Arm_Dumbbell_Pullover',
  'Straight-Arm Pulldown': 'Straight-Arm_Pulldown',
  'Straight Bar Bench Mid Rows': 'Straight_Bar_Bench_Mid_Rows',
  'Straight Raises on Incline Bench': 'Straight_Raises_on_Incline_Bench',
  'Stride Jump Crossover': 'Stride_Jump_Crossover',
  'Sumo Deadlift': 'Sumo_Deadlift',
  'Sumo Deadlift with Bands': 'Sumo_Deadlift_with_Bands',
  'Sumo Deadlift with Chains': 'Sumo_Deadlift_with_Chains',
  Superman: 'Superman',
  'Supine Chest Throw': 'Supine_Chest_Throw',
  'Supine One-Arm Overhead Throw': 'Supine_One-Arm_Overhead_Throw',
  'Supine Two-Arm Overhead Throw': 'Supine_Two-Arm_Overhead_Throw',
  'Suspended Fallout': 'Suspended_Fallout',
  'Suspended Push-Up': 'Suspended_Push-Up',
  'Suspended Reverse Crunch': 'Suspended_Reverse_Crunch',
  'Suspended Row': 'Suspended_Row',
  'Suspended Split Squat': 'Suspended_Split_Squat',
  'Svend Press': 'Svend_Press',
  'T-Bar Row with Handle': 'T-Bar_Row_with_Handle',
  'Tate Press': 'Tate_Press',
  'The Straddle': 'The_Straddle',
  'Thigh Abductor': 'Thigh_Abductor',
  'Thigh Adductor': 'Thigh_Adductor',
  'Tire Flip': 'Tire_Flip',
  'Toe Touchers': 'Toe_Touchers',
  'Torso Rotation': 'Torso_Rotation',
  'Trail Running/Walking': 'Trail_Running_Walking',
  'Trap Bar Deadlift': 'Trap_Bar_Deadlift',
  'Tricep Dumbbell Kickback': 'Tricep_Dumbbell_Kickback',
  'Tricep Side Stretch': 'Tricep_Side_Stretch',
  'Triceps Overhead Extension with Rope': 'Triceps_Overhead_Extension_with_Rope',
  'Triceps Pushdown': 'Triceps_Pushdown',
  'Triceps Pushdown - Rope Attachment': 'Triceps_Pushdown_-_Rope_Attachment',
  'Triceps Pushdown - V-Bar Attachment': 'Triceps_Pushdown_-_V-Bar_Attachment',
  'Triceps Stretch': 'Triceps_Stretch',
  'Tuck Crunch': 'Tuck_Crunch',
  'Two-Arm Dumbbell Preacher Curl': 'Two-Arm_Dumbbell_Preacher_Curl',
  'Two-Arm Kettlebell Clean': 'Two-Arm_Kettlebell_Clean',
  'Two-Arm Kettlebell Jerk': 'Two-Arm_Kettlebell_Jerk',
  'Two-Arm Kettlebell Military Press': 'Two-Arm_Kettlebell_Military_Press',
  'Two-Arm Kettlebell Row': 'Two-Arm_Kettlebell_Row',
  'Underhand Cable Pulldowns': 'Underhand_Cable_Pulldowns',
  'Upper Back-Leg Grab': 'Upper_Back-Leg_Grab',
  'Upper Back Stretch': 'Upper_Back_Stretch',
  'Upright Barbell Row': 'Upright_Barbell_Row',
  'Upright Cable Row': 'Upright_Cable_Row',
  'Upright Row - With Bands': 'Upright_Row_-_With_Bands',
  'Upward Stretch': 'Upward_Stretch',
  'V-Bar Pulldown': 'V-Bar_Pulldown',
  'V-Bar Pullup': 'V-Bar_Pullup',
  'Vertical Swing': 'Vertical_Swing',
  'Walking, Treadmill': 'Walking_Treadmill',
  'Weighted Ball Hyperextension': 'Weighted_Ball_Hyperextension',
  'Weighted Ball Side Bend': 'Weighted_Ball_Side_Bend',
  'Weighted Bench Dip': 'Weighted_Bench_Dip',
  'Weighted Crunches': 'Weighted_Crunches',
  'Weighted Jump Squat': 'Weighted_Jump_Squat',
  'Weighted Pull Ups': 'Weighted_Pull_Ups',
  'Weighted Sissy Squat': 'Weighted_Sissy_Squat',
  'Weighted Sit-Ups - With Bands': 'Weighted_Sit-Ups_-_With_Bands',
  'Wide-Grip Barbell Bench Press': 'Wide-Grip_Barbell_Bench_Press',
  'Wide-Grip Decline Barbell Bench Press': 'Wide-Grip_Decline_Barbell_Bench_Press',
  'Wide-Grip Decline Barbell Pullover': 'Wide-Grip_Decline_Barbell_Pullover',
  'Wide-Grip Lat Pulldown': 'Wide-Grip_Lat_Pulldown',
  'Wide-Grip Pulldown Behind The Neck': 'Wide-Grip_Pulldown_Behind_The_Neck',
  'Wide-Grip Rear Pull-Up': 'Wide-Grip_Rear_Pull-Up',
  'Wide-Grip Standing Barbell Curl': 'Wide-Grip_Standing_Barbell_Curl',
  'Wide Stance Barbell Squat': 'Wide_Stance_Barbell_Squat',
  'Wide Stance Stiff Legs': 'Wide_Stance_Stiff_Legs',
  'Wind Sprints': 'Wind_Sprints',
  Windmills: 'Windmills',
  "World's Greatest Stretch": 'Worlds_Greatest_Stretch',
  'Wrist Circles': 'Wrist_Circles',
  'Wrist Roller': 'Wrist_Roller',
  'Wrist Rotations with Straight Bar': 'Wrist_Rotations_with_Straight_Bar',
  'Yoke Walk': 'Yoke_Walk',
  'Zercher Squats': 'Zercher_Squats',
  'Zottman Curl': 'Zottman_Curl',
  'Zottman Preacher Curl': 'Zottman_Preacher_Curl',
  'One-Arm Push-up': 'Single-Arm_Push-Up',
  'Single Leg Romanian Deadlift': 'Romanian_Deadlift',
  'Single Leg Romanian Deadlift Reach': 'Kettlebell_One-Legged_Deadlift',
  'Tempo Push-up': 'Pushups',
  'Weighted Push-up': 'Pushups',
  'Wall Push-up': 'Pushups',
  'Knee Push-up': 'Pushups',
  'Standard Push-up': 'Pushups',
  'Wide Push-up': 'Push-Up_Wide',
  'Diamond Push-up': 'Push-Ups_-_Close_Triceps_Position',
  'Pike Push-up': 'Handstand_Push-Ups',
  'Clap Push-up': 'Plyo_Push-up',
  'Hindu Push-up': 'Pushups',
  'Archer Push-up': 'Pushups',
  'Spiderman Push-up': 'Push_Up_to_Side_Plank',
  'Typewriter Push-up': 'Pushups',
  'Pseudo Planche Push-up': 'Pushups',
  'Scapular Push-up': 'Pushups',
  'Plank to Push-up': 'Pushups',
  'Deficit Push-up': 'Push-Ups_With_Feet_Elevated',
  'Dive Bomber Push-up': 'Pushups',
  'Diamond Cutter Push-up': 'Push-Ups_-_Close_Triceps_Position',
  'Ring Push-up': 'Suspended_Push-Up',
  'Close Grip Chin-up': 'Chin-Up',
  'Neutral Grip Pull-up': 'Pullups',
  'Wide Grip Pull-up': 'Wide-Grip_Rear_Pull-Up',
  'Dead Hang': 'One_Handed_Hang',
  'Active Hang': 'One_Handed_Hang',
  'Bar Dead-hang': 'One_Handed_Hang',
  'Active Hang Scapular Elevations': 'Scapular_Pull-Up',
  'Muscle-up Negative': 'Muscle_Up',
  'Strict Muscle-up': 'Muscle_Up',
  'Commando Pull-up': 'Pullups',
  'Archer Pull-up': 'Pullups',
  'L-Sit Pull-up': 'Pullups',
  'One-Arm Pull-up Progression': 'Pullups',
  'Ring Row': 'Bodyweight_Mid_Row',
  'Renegade Row': 'Alternating_Renegade_Row',
  'Front Lever Progression': 'Pullups',
  'Front Lever Row': 'Pullups',
  'Back Lever Progression': 'Pullups',
  'Back Lever Hold': 'Pullups',
  'Hanging Knee Raise': 'Hanging_Leg_Raise',
  'Toes-to-bar': 'Hanging_Leg_Raise',
  'Toes to Bar': 'Hanging_Leg_Raise',
  'Spinal Decompression Hang': 'One_Handed_Hang',
  Squat: 'Bodyweight_Squat',
  'Close-stance Squat': 'Bodyweight_Squat',
  'Jump Squat': 'Freehand_Jump_Squat',
  'Tempo Squat': 'Bodyweight_Squat',
  'Deep Squat Hold': 'Bodyweight_Squat',
  'Cossack Squat': 'Bodyweight_Squat',
  'Hindu Squat': 'Bodyweight_Squat',
  'Sumo Squat': 'Bodyweight_Squat',
  'Sumo Pulse': 'Bodyweight_Squat',
  'Squat to Stand': 'Bodyweight_Squat',
  'Squat to Press': 'Bodyweight_Squat',
  'Squat Jump 180': 'Freehand_Jump_Squat',
  'In and Out Squat Jump': 'Freehand_Jump_Squat',
  'Reactive Squat Jump': 'Freehand_Jump_Squat',
  'Shrimp Squat': 'Bodyweight_Squat',
  'Skater Squat': 'Bodyweight_Squat',
  'Sissy Squat': 'Weighted_Sissy_Squat',
  'Pistol Squat': 'Bodyweight_Squat',
  'Pistol Squat Progression': 'Bodyweight_Squat',
  'Pistol Box Squat': 'Box_Squat',
  'Bulgarian Split Squat': 'Elevated_Back_Lunge',
  'Wall Sit': 'Bodyweight_Squat',
  Lunge: 'Dumbbell_Lunges',
  'Walking Lunge': 'Bodyweight_Walking_Lunge',
  'Reverse Lunge': 'Dumbbell_Rear_Lunge',
  'Reverse Lunge Pattern': 'Dumbbell_Rear_Lunge',
  'Reverse Lunge Knee Drive': 'Dumbbell_Rear_Lunge',
  'Reverse Lunge Twist': 'Dumbbell_Rear_Lunge',
  'Alternating Lunge': 'Dumbbell_Lunges',
  'Curtsy Lunge': 'Crossover_Reverse_Lunge',
  'Curtsy Lunge Jump': 'Crossover_Reverse_Lunge',
  'Lateral Lunge': 'Dumbbell_Lunges',
  'Lateral Lunge with Reach': 'Dumbbell_Lunges',
  'Lunge Pulse': 'Dumbbell_Lunges',
  'Lunge with Twist': 'Lunge_Pass_Through',
  'Static Lunge Hold': 'Dumbbell_Lunges',
  'Step Through Lunge': 'Dumbbell_Lunges',
  'Reaching Lunge': 'Dumbbell_Lunges',
  'Knee Hug to Lunge': 'Dumbbell_Lunges',
  'Weighted Lunge': 'Barbell_Lunge',
  'Step-up': 'Dumbbell_Step_Ups',
  'Lateral Step-Up': 'Dumbbell_Step_Ups',
  'Box Jump': 'Box_Jump_Multiple_Response',
  'Box Jump for Speed': 'Box_Jump_Multiple_Response',
  'Single Leg Box Jump': 'Box_Jump_Multiple_Response',
  'Calf Raise': 'Standing_Calf_Raises',
  'Single-leg Calf Raise': 'Standing_Dumbbell_Calf_Raise',
  'Single Leg Calf Raise Balance': 'Standing_Dumbbell_Calf_Raise',
  'Single-leg Deadlift': 'Kettlebell_One-Legged_Deadlift',
  'Single Leg Deadlift': 'Kettlebell_One-Legged_Deadlift',
  'Single Leg Deadlift Balance': 'Kettlebell_One-Legged_Deadlift',
  'Single Leg Hip Hinge': 'Kettlebell_One-Legged_Deadlift',
  'Single Leg Hip Thrust': 'Pelvic_Tilt_Into_Bridge',
  'Single Leg Squat to Chair': 'Chair_Squat',
  'Single Leg Press': 'Leg_Press',
  'Single Leg Reach': 'Kettlebell_One-Legged_Deadlift',
  'Single Leg Row': 'Bodyweight_Mid_Row',
  'Single Leg Stand': 'Tree_Pose',
  'Single Leg Stand Eyes Closed': 'Tree_Pose',
  'Nordic Curl': 'Natural_Glute_Ham_Raise',
  'Nordic Hamstring Curl': 'Natural_Glute_Ham_Raise',
  'Deadlift Pattern': 'Barbell_Deadlift',
  'Suitcase Deadlift': 'Barbell_Deadlift',
  'Side Plank': 'Side_Bridge',
  'Side Plank Dip': 'Side_Bridge',
  'Side-plank Hip Dip': 'Side_Bridge',
  'Reverse Plank': 'Upward_Plank_Pose',
  'High Plank Shoulder Tap': 'Plank',
  'Plank Shoulder Tap': 'Plank',
  'Plank Jack': 'Mountain_Climbers',
  'Plank Up Down': 'Plank',
  'Knee to Elbow Plank': 'Mountain_Climbers',
  'V-up': 'Jackknife_Sit-Up',
  'V-Up Jacks': 'Jackknife_Sit-Up',
  'Hollow-body Rock': 'Jackknife_Sit-Up',
  'Hollow Body Hold': 'Plank',
  'Leg Raise': 'Flat_Bench_Lying_Leg_Raise',
  'Bicycle Crunch': 'Air_Bike',
  'Dragon Flag': 'Hanging_Leg_Raise',
  'Dragon Flag Progression': 'Hanging_Leg_Raise',
  'Ab Wheel Rollout': 'Ab_Roller',
  'Superman Hold': 'Superman',
  'Reverse Snow Angel': 'Superman',
  'Windshield Wiper': 'Windmills',
  'Dead Bug for Posture': 'Dead_Bug',
  'Bird Dog': 'Superman',
  'Mountain Climber (fast)': 'Mountain_Climbers',
  'Mountain Climber Twist': 'Mountain_Climbers',
  'Cross-body Reach': 'Cross-Body_Crunch',
  'Cross Body Toe Touch': 'Cross-Body_Crunch',
  'Crab Toe Touch': 'Cross-Body_Crunch',
  Woodchop: 'Standing_Cable_Wood_Chop',
  'Pallof Press with Band': 'Pallof_Press',
  'Glute Bridge': 'Barbell_Glute_Bridge',
  'Glute Bridge for Posture': 'Barbell_Glute_Bridge',
  'Donkey Kick': 'Glute_Kickback',
  'Fire Hydrant': 'IT_Band_and_Glute_Stretch',
  Clamshell: 'Lying_Glute',
  'Hip Circle': 'Hip_Circles_prone',
  'Hip Hinge': 'Barbell_Deadlift',
  'Hip Hinge Pattern': 'Barbell_Deadlift',
  'Hip Hinge Drill (Good Morning)': 'Good_Morning',
  'Hip Flexor March': 'Kneeling_Hip_Flexor',
  'Hip Flexor Lunge Stretch': 'Kneeling_Hip_Flexor',
  'Hip Flexor Lunge for Posture': 'Kneeling_Hip_Flexor',
  'Quadruped Hip Circles': 'Hip_Circles_prone',
  'Standing Knee Drive': 'Knee_Tuck_Jump',
  'Standing Figure Four': 'Ankle_On_The_Knee',
  'Seated Figure Four': 'Ankle_On_The_Knee',
  'Shin Box Switch': 'Groin_and_Back_Stretch',
  'Handstand Wall Hold': 'Handstand',
  'Frog Stand': 'Crane_Crow_Pose',
  'L-sit (Parallettes)': 'Scale_Pose',
  'L-Sit': 'Scale_Pose',
  'L-Sit Hold': 'Scale_Pose',
  'Stork Stand': 'Tree_Pose',
  'Flamingo Stand': 'Tree_Pose',
  'BOSU Ball Stand': 'Bosu_Ball_Cable_Crunch_With_Side_Bends',
  'Eyes Closed Balance': 'Tree_Pose',
  'Tandem Stand': 'Mountain_Pose',
  'Airplane Balance': 'Kettlebell_One-Legged_Deadlift',
  'Warrior III': 'Warrior_III_Pose',
  'Clock Reach': 'Kettlebell_One-Legged_Deadlift',
  'Compass Reach': 'Kettlebell_One-Legged_Deadlift',
  'Planche Lean': 'Pushups',
  'Weighted Dip': 'Dips_-_Chest_Version',
  Dip: 'Dips_-_Chest_Version',
  'Bench Dip': 'Bench_Dips',
  Burpee: 'Freehand_Jump_Squat',
  'Burpee with Tuck Jump': 'Knee_Tuck_Jump',
  'Half Burpee': 'Freehand_Jump_Squat',
  'Squat Thrust': 'Freehand_Jump_Squat',
  Sprawl: 'Freehand_Jump_Squat',
  'Bear Crawl': 'Bear_Crawl_Sled_Drags',
  'Bear Crawl Sprint': 'Bear_Crawl_Sled_Drags',
  'Crab Walk': 'Bear_Crawl_Sled_Drags',
  'Gecko Walk': 'Bear_Crawl_Sled_Drags',
  'Lizard Walk': 'Inchworm',
  'Crawl Pattern': 'Bear_Crawl_Sled_Drags',
  'High Knees': 'Jogging_Treadmill',
  'High-knee Sprint on Spot': 'Jogging_Treadmill',
  'Jumping Jack': 'Star_Jump',
  'Jumping Jacks': 'Star_Jump',
  'Cross Jacks': 'Star_Jump',
  'Seal Jack': 'Star_Jump',
  'Power Jack': 'Star_Jump',
  'Tuck Jump': 'Knee_Tuck_Jump',
  'Broad Jump': 'Frog_Hops',
  'Forward Bound': 'Frog_Hops',
  'Frog Jump': 'Frog_Hops',
  'Triple Hop': 'Frog_Hops',
  'Pogo Jump': 'Rope_Jumping',
  'Rotational Jump': 'Freehand_Jump_Squat',
  'Lateral Shuffle': 'Side_to_Side_Box_Shuffle',
  Skaters: 'Side_to_Side_Box_Shuffle',
  'Speed Skater': 'Side_to_Side_Box_Shuffle',
  'Shuffle Cut': 'Side_to_Side_Box_Shuffle',
  'A-Skip': 'Jogging_Treadmill',
  'A-skip': 'Jogging_Treadmill',
  'B-skip': 'Jogging_Treadmill',
  'Power Skip': 'Jogging_Treadmill',
  'Butt-kick Sprint': 'Double_Leg_Butt_Kick',
  'Butt Kicks': 'Double_Leg_Butt_Kick',
  'Sprint Intervals': 'Wind_Sprints',
  'Sprint in Place': 'Wind_Sprints',
  'Sprint Start': 'Wind_Sprints',
  'Sand Sprint': 'Wind_Sprints',
  'Hill Sprint': 'Wind_Sprints',
  'Tabata Sprint': 'Wind_Sprints',
  'Zigzag Sprint': 'Wind_Sprints',
  'Backpedal Sprint': 'Wind_Sprints',
  'Frankenstein Walk': 'Bodyweight_Walking_Lunge',
  'Jump Rope': 'Rope_Jumping',
  'Single Leg Hop': 'Rope_Jumping',
  'Lateral Hop and Stick': 'Rope_Jumping',
  'Line Hop': 'Rope_Jumping',
  'Reactive Start': 'Wind_Sprints',
  'Runner Touch': 'Runners_Stretch',
  'Carioca Drill': 'Side_to_Side_Box_Shuffle',
  'Crossover Step': 'Side_to_Side_Box_Shuffle',
  'Cone Drill': 'Wind_Sprints',
  'Pro Agility Shuttle': 'Wind_Sprints',
  'Agility T-Drill': 'Wind_Sprints',
  'L-Drill': 'Wind_Sprints',
  'Fast Feet Drill': 'Wind_Sprints',
  'Defensive Shuffle': 'Side_to_Side_Box_Shuffle',
  'Defensive Slides': 'Side_to_Side_Box_Shuffle',
  'Touchdown Shuffle': 'Side_to_Side_Box_Shuffle',
  'Drop Step': 'Wind_Sprints',
  'Vertical Jump Training': 'Freehand_Jump_Squat',
  'Front Kick': 'Knee_Tuck_Jump',
  'Side Kick': 'Knee_Tuck_Jump',
  'Cross Punch': 'Chest_Push_with_Run_Release',
  Uppercut: 'Chest_Push_with_Run_Release',
  'Knee Strike': 'Knee_Tuck_Jump',
  'Throwing Motion': 'One-Arm_Medicine_Ball_Slam',
  'Medicine Ball Rotation Pass': 'Medicine_Ball_Full_Twist',
  'Rotational Press': 'Alternating_Kettlebell_Press',
  'Farmers Carry': 'Farmers_Walk',
  'Suitcase Carry': 'Farmers_Walk',
  'Overhead Carry': 'Farmers_Walk',
  'Rack Carry': 'Farmers_Walk',
  'Cross Carry': 'Farmers_Walk',
  'Waiter Carry': 'Farmers_Walk',
  'Cobra Stretch': 'Cobra_Pose',
  'Cat-Camel': 'Cat_Stretch',
  'Cat-Cow Stretch': 'Cat_Stretch',
  'Thoracic Rotation': 'Cat_Stretch',
  'Thoracic Spine Rotation': 'Cat_Stretch',
  'Kneeling Thoracic Rotation': 'Cat_Stretch',
  'Standing Thoracic Rotation': 'Cat_Stretch',
  'Quadruped Thoracic Extension': 'Cat_Stretch',
  'T-Spine Book Opener': 'Cat_Stretch',
  'Thread the Needle': 'Cat_Stretch',
  'Thread the Needle Stretch': 'Cat_Stretch',
  'Thoracic Extension': 'Cat_Stretch',
  'Thoracic Extension (Foam Roller)': 'Cat_Stretch',
  'Thoracic Extension Over Roller': 'Cat_Stretch',
  'Standing Forward Fold': 'Standing_Toe_Touches',
  'Seated Forward Fold': 'Seated_Floor_Hamstring_Stretch',
  'Seated Straddle Stretch': 'Seated_Floor_Hamstring_Stretch',
  'Seated Twist': 'Seated_Floor_Hamstring_Stretch',
  'Standing Quad Stretch': 'All_Fours_Quad_Stretch',
  'Standing Quad Pull': 'All_Fours_Quad_Stretch',
  'Standing Quad Pull Balance': 'All_Fours_Quad_Stretch',
  'Reclined Butterfly': 'Butterfly',
  'Reclining Butterfly': 'Butterfly',
  'Butterfly Stretch': 'Butterfly',
  'Butterfly Stretch Deep': 'Butterfly',
  'Happy Baby': 'Butterfly',
  'Scorpion Stretch': 'Groin_and_Back_Stretch',
  'King Arthur Stretch': 'All_Fours_Quad_Stretch',
  'Front Split (Half-split)': 'Groin_and_Back_Stretch',
  'Side Split (Middle Split)': 'Groin_and_Back_Stretch',
  'Frog Stretch': 'Groin_and_Back_Stretch',
  'Gate Stretch': 'Groin_and_Back_Stretch',
  'Bretzel Stretch': 'Groin_and_Back_Stretch',
  'Downward Dog': 'Downward_Facing_Balance',
  'Upward Dog': 'Downward_Facing_Balance',
  'Neck Rolls': 'Neck_Press',
  'Neck Side Stretch': 'Neck_Press',
  'Lateral Neck Stretch': 'Neck_Press',
  'Neck Retraction': 'Neck_Press',
  'Chin Tucks': 'Chin_To_Chest_Stretch',
  'Chin Tuck Against Wall': 'Chin_To_Chest_Stretch',
  'Ankle Alphabet': 'Ankle_Circles',
  'Wrist Circles and Stretches': 'Wrist_Circles',
  'Wrist Flexion Extension': 'Wrist_Circles',
  'Shoulder Cross-Body Stretch': 'Shoulder_Stretch',
  'Sleeper Stretch': 'Shoulder_Stretch',
  'Chest Opener Stretch': 'Chest_Stretch_on_Stability_Ball',
  'Chest Doorway Stretch': 'Chest_Stretch_on_Stability_Ball',
  'Doorway Chest Stretch': 'Chest_Stretch_on_Stability_Ball',
  'Wall Chest Stretch': 'Chest_Stretch_on_Stability_Ball',
  'Hip Flexor Stretch': 'Kneeling_Hip_Flexor',
  'Wall Hip Flexor Stretch': 'Kneeling_Hip_Flexor',
  'Knee-to-chest Supine': 'One_Knee_To_Chest',
  'Supine Knee to Chest': 'Hug_Knees_To_Chest',
  'Knee Hug': 'Hug_Knees_To_Chest',
  'Jefferson Curl': 'Standing_Forward_Bend',
  'Jefferson Curl (Light)': 'Standing_Forward_Bend',
  'Wall Angels': 'One_Arm_Against_Wall',
  'Wall Slide Recovery': 'One_Arm_Against_Wall',
  'Lat Stretch': 'Close-Grip_Front_Lat_Pulldown',
  'Cow Face Arms': 'Shoulder_Stretch',
  'Prone Press Up': 'Cobra_Pose',
  'Prayer Stretch': 'Cat_Stretch',
  'Reclined Hero Pose': 'All_Fours_Quad_Stretch',
  'Supported Fish Pose': 'Cat_Stretch',
  'Dynamic Arm Swings': 'Dynamic_Chest_Stretch',
  'Dynamic Leg Swing Forward': 'Standing_Toe_Touches',
  'Dynamic Leg Swing Lateral': 'Dumbbell_Lunges',
  'Lying Spinal Twist': 'Groin_and_Back_Stretch',
  'Supine Spinal Twist': 'Groin_and_Back_Stretch',
  'Supine Spinal Twist Stretch': 'Groin_and_Back_Stretch',
  'Spinal Wave': 'Cat_Stretch',
  'Spine Twist': 'Groin_and_Back_Stretch',
  'Standing Side Bend': 'Dumbbell_Side_Bend',
  'Legs Up Wall': 'Flat_Bench_Lying_Leg_Raise',
  'Reverse Table': 'Upward_Plank_Pose',
  'Prone T Raise': 'Superman',
  'Prone T Raise Hold': 'Superman',
  'Prone W Raise': 'Superman',
  'Prone W Raise Hold': 'Superman',
  'Prone Y Raise': 'Superman',
  'Prone Y Raise Hold': 'Superman',
  'I-Y-T Raise': 'Superman',
  'Scapular Squeeze': 'Superman',
  'Band Pull-apart': 'Band_Pull_Apart',
  'Face Pull with Band': 'Face_Pull',
  'Seated Row': 'Seated_Cable_Rows',
  'Row Pattern': 'Seated_Cable_Rows',
  'Push-Pull Pattern': 'Pushups',
  'Overhead Press Pattern': 'Shoulder_Press_-_With_Bands',
  'Side Bend': 'Barbell_Side_Bend',
  'Banded Good Morning': 'Band_Good_Morning',
  'Half-kneeling Chop': 'Standing_Cable_Wood_Chop',
  'Foam Rolling': 'IT_Band_and_Glute_Stretch',
  'Foam Roll Adductors': 'IT_Band_and_Glute_Stretch',
  'Foam Roll Calves': 'IT_Band_and_Glute_Stretch',
  'Foam Roll Chest': 'IT_Band_and_Glute_Stretch',
  'Foam Roll Glutes': 'IT_Band_and_Glute_Stretch',
  'Foam Roll Hamstrings': 'IT_Band_and_Glute_Stretch',
  'Foam Roll IT Band': 'IT_Band_and_Glute_Stretch',
  'Foam Roll Lats': 'IT_Band_and_Glute_Stretch',
  'Foam Roll Quads': 'IT_Band_and_Glute_Stretch',
  'Foam Roll TFL': 'IT_Band_and_Glute_Stretch',
  'Foam Roll Upper Back': 'IT_Band_and_Glute_Stretch',
  'Lacrosse Ball Foot Roll': 'IT_Band_and_Glute_Stretch',
  'Lacrosse Ball Glute Release': 'IT_Band_and_Glute_Stretch',
  'Lacrosse Ball Shoulder Release': 'IT_Band_and_Glute_Stretch',
  'Ball Trap Release': 'IT_Band_and_Glute_Stretch',
  'Active Recovery Walk': 'Bodyweight_Walking_Lunge',
  'Supine Twist Recovery': 'Groin_and_Back_Stretch',
  'Tension Release Shake': 'Star_Jump',
  'Gentle Flow Sequence': 'Cat_Stretch',
  'Get Up from Floor': 'Dumbbell_Squat',
  'Turkish Get-Up': 'Kettlebell_Turkish_Get-Up_Lunge_style',
  'Box Breathing': 'Stomach_Vacuum',
  'Power Breathing': 'Stomach_Vacuum',
  'Breath Work': 'Stomach_Vacuum',
  '4-7-8 Breathing': 'Stomach_Vacuum',
  'Diaphragmatic Breathing': 'Stomach_Vacuum',
  'Crocodile Breath': 'Stomach_Vacuum',
  'Alternate Nostril Breathing': 'Stomach_Vacuum',
  'Extended Exhale Breathing': 'Stomach_Vacuum',
  'Cold Exposure Breathing': 'Stomach_Vacuum',
  'Focus Breathing 5-5-5': 'Stomach_Vacuum',
  'Body Scan Meditation': 'Stomach_Vacuum',
  'Seated Meditation': 'Stomach_Vacuum',
  'Walking Meditation': 'Bodyweight_Walking_Lunge',
  'Loving-Kindness Meditation': 'Stomach_Vacuum',
  'Mindful Movement': 'Stomach_Vacuum',
  'Focus Drill': 'Stomach_Vacuum',
  'Concentration Circuit': 'Stomach_Vacuum',
  Meditation: 'Stomach_Vacuum',
  Visualization: 'Stomach_Vacuum',
  'Progressive Muscle Relaxation': 'Stomach_Vacuum',
  'Gratitude Practice': 'Stomach_Vacuum',
  'Grounding Exercise 5-4-3-2-1': 'Stomach_Vacuum',
  'Bilateral Tapping': 'Stomach_Vacuum',
  'Laughing Yoga': 'Stomach_Vacuum',
  'Yoga Nidra': 'Stomach_Vacuum',
  'Tai Chi Flow': 'Stomach_Vacuum',
  'Mobility Flow': 'Groin_and_Back_Stretch',
  'Joint Circles': 'Ankle_Circles',
  'Dynamic Stretching': 'Groin_and_Back_Stretch',
  'PNF Stretching': 'Groin_and_Back_Stretch',
  'Loaded Stretch': 'Groin_and_Back_Stretch',
  'Active Flexibility': 'Groin_and_Back_Stretch',
  'Passive Flexibility': 'Groin_and_Back_Stretch',
  '90/90 Hip Stretch': '90_90_Hamstring',
  'Heel to Toe Walk': 'Bodyweight_Walking_Lunge',
  'Heel-toe Walk': 'Bodyweight_Walking_Lunge',
  'Tandem Walk': 'Bodyweight_Walking_Lunge',
  'Duck Walk': 'Bodyweight_Squat',
  Cartwheel: 'Star_Jump',
  "Child\\'s Pose": 'Cat_Stretch',
  "Child'\\s Pose": 'Cat_Stretch',
  'Child\\': 'Cat_Stretch',
  "World\\'s Greatest Stretch": 'Groin_and_Back_Stretch',
  'World\\': 'Groin_and_Back_Stretch',
  'Cross-Body Shoulder Stretch': 'Shoulder_Stretch',
  'Depth Jump': 'Depth_Jump_Leap',
  'Hip Circles': 'Standing_Hip_Circles',
  'Kneeling Hip Flexor Stretch': 'Kneeling_Hip_Flexor',
  'Medicine Ball Slam': 'One-Arm_Medicine_Ball_Slam',
  'Plank Run': 'Mountain_Climbers',
  'Prone Quad Stretch': 'On-Your-Back_Quad_Stretch',
  'Standing Hamstring Stretch': 'Standing_Hamstring_and_Calf_Stretch',
  'Tricep Overhead Stretch': 'Triceps_Stretch',
  'Revolved Side Angle Pose': 'Revolved_Side_Angle_Pose',
  'Cat Pose': 'Cat_Pose',
  'Cat Cow Pose': 'Cat_Cow_Pose',
  'Cow Pose': 'Cow_Pose',
  'Fish Pose': 'Fish_Pose',
  'Gate Pose': 'Gate_Pose',
  'Heron Pose': 'Heron_Pose',
  'Hero Pose': 'Hero_Pose',
  'Lion Pose': 'Lion_Pose',
  'Easy Pose': 'Easy_Pose',
  'Fire Log Pose': 'Fire_Log_Pose',
  'Thunderbolt Pose': 'Thunderbolt_Pose',
  'Wild Thing': 'Wild_Thing',
  Handstand: 'Handstand',
  'Dolphin Plank Pose': 'Dolphin_Plank_Pose',
  'Side Plank Pose': 'Side_Plank_Pose',
  'Feathered Peacock Pose': 'Feathered_Peacock_Pose',
  'Scorpion Pose': 'Scorpion_Pose',
  'Standing Split': 'Standing_Split',
  'Standing Half Forward Bend': 'Standing_Half_Forward_Bend',
  'Upward Salute': 'Upward_Salute',
  'Low Lunge': 'Low_Lunge',
  'High Lunge': 'High_Lunge',
};

/**
 * Resolve an exercise name to its image folder.
 * Tries: exact match → normalized match → fuzzy match → null
 */
export function resolveExerciseImageFolder(exerciseName: string): string | null {
  // 1. Direct lookup
  if (EXERCISE_IMAGE_MAP[exerciseName]) return EXERCISE_IMAGE_MAP[exerciseName];

  // 2. Case-insensitive lookup
  const lower = exerciseName.toLowerCase();
  for (const [name, folder] of Object.entries(EXERCISE_IMAGE_MAP)) {
    if (name.toLowerCase() === lower) return folder;
  }

  // 3. Strip variation prefixes and try again
  const prefixes = [
    'Tempo ',
    'Slow ',
    'Fast ',
    'Pause ',
    'Paused ',
    'Isometric ',
    'Explosive ',
    'Plyometric ',
    'Single-leg ',
    'Single-arm ',
    'Elevated ',
    'Weighted ',
    'Unilateral ',
    'One-Arm ',
    'One-Leg ',
    'Banded ',
  ];
  for (const prefix of prefixes) {
    if (exerciseName.startsWith(prefix)) {
      const base = exerciseName.slice(prefix.length);
      if (EXERCISE_IMAGE_MAP[base]) return EXERCISE_IMAGE_MAP[base];
    }
  }

  // 4. Strip parenthetical suffixes
  const stripped = exerciseName.replace(/\s*\([^)]+\)\s*$/, '').trim();
  if (stripped !== exerciseName && EXERCISE_IMAGE_MAP[stripped]) {
    return EXERCISE_IMAGE_MAP[stripped];
  }

  // 5. Try underscore version as folder name directly
  const underscored = exerciseName.replace(/[\s]+/g, '_').replace(/[(),']/g, '');
  // Return underscored as potential folder (ExerciseImage will verify existence)
  // If folder doesn't exist, ExerciseImage shows placeholder
  return underscored || null;
}
