name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what you'd like to see!
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the use case for this feature.
      placeholder: Why would this feature be useful?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
