/**
 * FitQuest Workout Screen
 * Premium glass UI with animated transitions
 */

import React, { useEffect, useState, useRef, useCallback } from 'react';
import { View, StyleSheet, ActivityIndicator, Alert, AppState, Vibration } from 'react-native';
import Animated, { FadeIn, FadeInDown, FadeInUp, ZoomIn } from 'react-native-reanimated';
import { ScreenContainer } from '../src/components/ui/primitives';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useTheme } from '../src/context/ThemeContext';
import { useLanguage } from '../src/context/LanguageContext';
import { useDatabase } from '../src/context/DatabaseContext';
import { useSubscription } from '../src/purchases/SubscriptionContext';
import { useFitQuestWorkout, WorkoutCompletionData } from '../src/hooks/useFitQuestWorkout';
import WorkoutSummaryView from '../src/components/WorkoutSummaryView';
import { useTimer } from '../src/hooks/useTimer';
import { useFitquestViewModel } from '../src/viewmodels/useFitquestViewModel';
import { GlassCard, GradientButton } from '../src/components/ui/GlassUI';
import { ScreenErrorBoundary } from '../src/components/ScreenErrorBoundary';
import ConfettiBurst from '../src/components/ConfettiBurst';
import { haptic } from '../src/utils/haptics';
import { useToast } from '../src/context/ToastContext';
import ThemedText from '../src/components/ThemedText';
import { useRouter, useLocalSearchParams } from 'expo-router';
import ScreenTutorial from '../src/components/ScreenTutorial';
import PremiumGate from '../src/components/PremiumGate';
import { typography, spacing } from '../src/design/theme-system';
import WorkoutReadyView from '../src/components/workout/WorkoutReadyView';
import WorkoutActiveView from '../src/components/workout/WorkoutActiveView';

// Module-level cooldown — survives unmount/remount across navigation cycles.
// Prevents re-generation when user navigates away and back within 10 seconds.
let lastAutoGeneratedAt = 0;
const AUTO_GEN_COOLDOWN_MS = 10_000;

function FitQuestScreenInner() {
  const { theme } = useTheme();
  const { t } = useLanguage();
  const { showToast } = useToast();
  const { autostart } = useLocalSearchParams<{ autostart?: string }>();
  const _router = useRouter();
  const { isReady, isLoading: dbLoading, error: dbError, userProfile, resetAll } = useDatabase();
  const {
    status,
    workout,
    currentExercise,
    currentExerciseIndex,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    progressPercentage,
    error,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    fatigueSnapshot,
    deloadStatus,
    generateNewWorkout,
    recoverActiveSession,
    startWorkout,
    completeExercise,
    skipExercise,
    finishWorkout,
    cancelWorkout,
  } = useFitQuestWorkout();

  const [completionResult, setCompletionResult] = useState<WorkoutCompletionData | null>(null);
  const [showConfetti, setShowConfetti] = useState(false);

  // ViewModel: audio management, trial gating, workout persistence
  const vm = useFitquestViewModel();

  // Timer integration
  const {
    restTimer,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    sessionTimer,
    startRest,
    skipRest,
    extendRest,
    startSession,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    endSession,
    pauseAll,
    resumeAll,
    stopAll,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    isActive: timerActive,
  } = useTimer();

  // Session clock (elapsed time)
  const sessionStartRef = useRef<number | null>(null);

  // Pause timers when app goes to background, resume on foreground
  useEffect(() => {
    const sub = AppState.addEventListener('change', (nextState) => {
      if (nextState === 'background' || nextState === 'inactive') {
        pauseAll();
      } else if (nextState === 'active') {
        resumeAll();
      }
    });
    return () => sub.remove();
  }, [pauseAll, resumeAll]);

  // Speak exercise instructions when transitioning to new exercise (VM handles narration chain)
  useEffect(() => {
    if (status === 'in_progress' && currentExercise && vm.voiceEnabled) {
      vm.speakExercise(currentExercise);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- currentExercise narrowed to .id intentionally
  }, [status, currentExercise?.id, vm.voiceEnabled]);

  // Stable ref for generateNewWorkout to prevent re-triggering on identity changes
  const generateNewWorkoutRef = useRef(generateNewWorkout);
  generateNewWorkoutRef.current = generateNewWorkout;
  const autoGeneratedRef = useRef(false);

  // Load trial snapshot for feature gating
  const { accessState } = useSubscription();
  const isSubscribed = accessState === 'SUBSCRIBED';
  useEffect(() => {
    if (isReady) {
      vm.loadTrialSnapshot(isSubscribed);
    }
  }, [isReady, isSubscribed, vm.loadTrialSnapshot]);

  // Auto-generate on mount if ready and idle (once per screen visit, with global cooldown)
  // First attempts to recover an interrupted session; only generates fresh if no recovery.
  useEffect(() => {
    if (isReady && userProfile && status === 'idle' && !completionResult && !autoGeneratedRef.current) {
      // Global cooldown: prevent re-generation across navigation cycles
      if (Date.now() - lastAutoGeneratedAt < AUTO_GEN_COOLDOWN_MS) {
        if (__DEV__) console.warn('[FitQuest] Auto-gen skipped (cooldown active)');
        return;
      }
      autoGeneratedRef.current = true;
      lastAutoGeneratedAt = Date.now();

      // Try to recover a crashed/interrupted session first
      let cancelled = false;
      recoverActiveSession().then((recovered) => {
        if (cancelled) return;
        if (!recovered) {
          if (__DEV__) console.warn('[FitQuest] No session to recover — generating new workout');
          const timer = setTimeout(() => generateNewWorkoutRef.current(), 500);
          // Note: cleanup below only covers the outer effect; inner timeout is short-lived
          return () => clearTimeout(timer);
        }
        if (__DEV__) console.warn('[FitQuest] Recovered interrupted session — skipping generation');
      });
      return () => {
        cancelled = true;
      };
    }
  }, [isReady, userProfile, status, completionResult, recoverActiveSession]);

  // Auto-start: when navigated from dashboard with ?autostart=1, immediately begin
  // the workout once it's been generated (status transitions idle → generated → in_progress)
  const autostartedRef = useRef(false);
  useEffect(() => {
    if (autostart === '1' && status === 'ready' && workout && !autostartedRef.current) {
      autostartedRef.current = true;
      haptic('workoutStart');
      startWorkout();
      startSession(60);
      sessionStartRef.current = Date.now();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- startWorkout/startSession stable via hook identity; including them would re-trigger on every render
  }, [autostart, status, workout]);

  // Workout rating state (shown after completion)
  const [workoutRating, setWorkoutRating] = useState<number | null>(null);

  // Stop audio whenever we leave in_progress state (safety net)
  useEffect(() => {
    if (status !== 'in_progress') {
      vm.cancelNarration();
    }
  }, [status, vm.cancelNarration]);

  const handleFinish = useCallback(async () => {
    if (__DEV__) console.warn('[FitQuest] handleFinish called — processing workout completion');
    vm.cancelNarration();
    vm.resetNarrationState();

    let result: WorkoutCompletionData | null = null;
    try {
      result = await finishWorkout();
    } catch (e) {
      if (__DEV__) console.error('[FitQuest] finishWorkout threw (non-fatal):', e);
    }

    if (result) {
      haptic('workoutComplete');
      if (__DEV__) console.warn('[FitQuest] Workout finished successfully — showing completion screen');
      setCompletionResult(result);
      setWorkoutRating(null);

      // Toast XP gain + level up
      const xpMsg = result.levelUp ? `+${result.xpEarned} XP — Level ${result.newLevel}!` : `+${result.xpEarned} XP`;
      showToast({ message: xpMsg, type: 'success', vibrate: true, duration: 4000 });

      // Narrator compliments the user with context-aware praise (non-blocking)
      vm.playWorkoutCompliment({
        completedCount: result.completedCount,
        totalCount: result.totalCount,
        durationSeconds: result.durationSeconds,
        streakDays: result.streak?.current ?? 0,
        xpEarned: result.xpEarned,
        levelUp: result.levelUp,
        newLevel: result.newLevel,
        progressions: result.progressions,
        exerciseNames: result.exerciseNames,
      });

      // Store last workout summary so AI Coach can reference it
      vm.storeLastWorkout(result);
    } else {
      if (__DEV__) console.warn('[FitQuest] finishWorkout returned null — may have already been called');
    }
  }, [finishWorkout, vm.cancelNarration, vm.resetNarrationState, vm.playWorkoutCompliment, vm.storeLastWorkout]);

  // Auto-trigger finish when workout reaches completed status
  const finishTriggeredRef = useRef(false);
  useEffect(() => {
    if (status === 'completed' && workout && !completionResult && !finishTriggeredRef.current) {
      finishTriggeredRef.current = true;
      vm.cancelNarration();
      handleFinish().finally(() => {
        finishTriggeredRef.current = false;
      });
    }
  }, [status, workout, completionResult, handleFinish]);

  const wantsNewWorkoutRef = useRef(false);
  const handleNewWorkout = () => {
    setCompletionResult(null);
    setWorkoutRating(null);
    vm.resetNarrationState();
    autoGeneratedRef.current = true; // Prevent auto-gen from also firing
    wantsNewWorkoutRef.current = true;
    cancelWorkout(); // Reset hook state to idle — triggers re-render with status='idle'
  };

  // Reactive: generate when status returns to idle after user requested new workout
  useEffect(() => {
    if (wantsNewWorkoutRef.current && status === 'idle') {
      wantsNewWorkoutRef.current = false;
      lastAutoGeneratedAt = Date.now(); // Refresh cooldown
      generateNewWorkout();
    }
  }, [status, generateNewWorkout]);

  const handleReset = () => {
    Alert.alert(t('fitquest.reset.title'), t('fitquest.reset.body'), [
      { text: t('common.cancel'), style: 'cancel' },
      { text: t('fitquest.reset.confirm'), style: 'destructive', onPress: resetAll },
    ]);
  };

  // ===== LOADING STATE =====
  if (dbLoading) {
    return (
      <ScreenContainer>
        <View style={styles.centered}>
          <Animated.View entering={ZoomIn.duration(150)}>
            <View style={[styles.loadingIcon, { backgroundColor: theme.colors.accent + '15' }]}>
              <ActivityIndicator size="large" color={theme.colors.accent} />
            </View>
          </Animated.View>
          <Animated.Text
            entering={FadeIn.delay(50).duration(150)}
            style={[styles.loadingText, { color: theme.colors.textSecondary }]}
          >
            {t('fitquest.initializing')}
          </Animated.Text>
        </View>
      </ScreenContainer>
    );
  }

  // ===== ERROR STATE =====
  if (dbError || error) {
    return (
      <ScreenContainer>
        <View style={styles.centered}>
          <Animated.View entering={ZoomIn.duration(150)}>
            <MaterialCommunityIcons name="alert-circle" size={64} color={theme.colors.error} />
          </Animated.View>
          <ThemedText style={[styles.errorTitle, { color: theme.colors.text }]}>{t('fitquest.errorTitle')}</ThemedText>
          <ThemedText style={[styles.errorSub, { color: theme.colors.textSecondary }]}>{dbError || error}</ThemedText>
          <GradientButton
            title={t('fitquest.resetAndRetry')}
            icon="refresh"
            onPress={handleReset}
            colors={[theme.colors.error, theme.colors.error]}
          />
        </View>
      </ScreenContainer>
    );
  }

  // ===== DB NOT READY YET (retry in progress) =====
  if (!isReady) {
    return (
      <ScreenContainer>
        <View style={styles.centered}>
          <Animated.View entering={ZoomIn.duration(150)}>
            <View style={[styles.loadingIcon, { backgroundColor: theme.colors.accent + '15' }]}>
              <ActivityIndicator size="large" color={theme.colors.accent} />
            </View>
          </Animated.View>
          <Animated.Text
            entering={FadeIn.delay(50).duration(150)}
            style={[styles.loadingText, { color: theme.colors.textSecondary }]}
          >
            {t('fitquest.initializing')}
          </Animated.Text>
        </View>
      </ScreenContainer>
    );
  }

  // ===== COMPLETION STATE =====
  if (completionResult) {
    return (
      <>
        <ConfettiBurst active={showConfetti} onComplete={() => setShowConfetti(false)} />
        <WorkoutSummaryView
          data={completionResult}
          rating={workoutRating}
          onRate={setWorkoutRating}
          onNewWorkout={handleNewWorkout}
        />
      </>
    );
  }

  // ===== GENERATING STATE =====
  if (status === 'generating') {
    return (
      <ScreenContainer>
        <View style={styles.centered}>
          <Animated.View entering={ZoomIn.duration(150)}>
            <View style={[styles.loadingIcon, { backgroundColor: theme.colors.accent + '15' }]}>
              <ActivityIndicator size="large" color={theme.colors.accent} />
            </View>
          </Animated.View>
          <Animated.Text
            entering={FadeIn.delay(50).duration(150)}
            style={[styles.genTitle, { color: theme.colors.text }]}
          >
            {t('fitquest.craftingWorkout')}
          </Animated.Text>
          <Animated.Text
            entering={FadeIn.delay(80).duration(150)}
            style={[styles.genSub, { color: theme.colors.textMuted }]}
          >
            {t('fitquest.craftingSub')}
          </Animated.Text>
        </View>
      </ScreenContainer>
    );
  }

  // ===== READY STATE (Preview) =====
  if (status === 'ready' && workout) {
    return (
      <WorkoutReadyView
        workout={workout}
        deloadStatus={deloadStatus}
        trialSnapshot={vm.trialSnapshot}
        onStart={() => {
          haptic('workoutStart');
          startWorkout();
          startSession(60);
          sessionStartRef.current = Date.now();
        }}
        onRegenerate={generateNewWorkout}
      />
    );
  }

  // ===== IN PROGRESS STATE =====
  if (status === 'in_progress' && workout && currentExercise) {
    return (
      <WorkoutActiveView
        workout={workout}
        currentExercise={currentExercise}
        currentExerciseIndex={currentExerciseIndex}
        sessionStartRef={sessionStartRef}
        restTimer={restTimer}
        startRest={startRest}
        skipRest={skipRest}
        extendRest={extendRest}
        stopAll={stopAll}
        completeExercise={completeExercise}
        skipExercise={skipExercise}
        cancelWorkout={cancelWorkout}
        onLastExerciseFinish={() => {
          haptic('workoutComplete');
          setShowConfetti(true);
          vm.cancelNarration();
          Vibration.vibrate([0, 100, 80, 100, 80, 200]);
        }}
        vm={{
          voiceEnabled: vm.voiceEnabled,
          isSpeaking: vm.isSpeaking,
          toggleVoice: vm.toggleVoice,
          cancelNarration: vm.cancelNarration,
          speakExercise: vm.speakExercise,
          playTransitionAudio: vm.playTransitionAudio,
        }}
      />
    );
  }

  // ===== COMPLETED STATE (before processing) =====
  if (status === 'completed' && workout) {
    return (
      <ScreenContainer>
        <View style={styles.centered}>
          <Animated.View entering={ZoomIn.duration(150)}>
            <View style={[styles.loadingIcon, { backgroundColor: theme.colors.success + '15' }]}>
              <ActivityIndicator size="large" color={theme.colors.success} />
            </View>
          </Animated.View>
          <ThemedText style={[styles.genTitle, { color: theme.colors.text }]}>
            {t('fitquest.recordingProgress')}
          </ThemedText>
        </View>
      </ScreenContainer>
    );
  }

  // ===== DEFAULT/IDLE STATE =====
  return (
    <ScreenContainer>
      <View style={styles.centered}>
        <Animated.View entering={ZoomIn.duration(150)}>
          <View style={[styles.idleIconWrap, { backgroundColor: theme.colors.accent + '12' }]}>
            <MaterialCommunityIcons name="dumbbell" size={56} color={theme.colors.accent} />
          </View>
        </Animated.View>
        <Animated.Text
          entering={FadeInUp.delay(150).duration(150)}
          style={[styles.idleTitle, { color: theme.colors.text }]}
        >
          FitQuest
        </Animated.Text>
        <Animated.Text
          entering={FadeIn.delay(300).duration(150)}
          style={[styles.idleSub, { color: theme.colors.textSecondary }]}
        >
          {t('fitquest.idleSub')}
        </Animated.Text>

        {!!userProfile && (
          <Animated.View entering={FadeInDown.delay(400).duration(150)} style={{ width: '100%', maxWidth: 280 }}>
            <GlassCard style={{ alignItems: 'center', padding: spacing[4], marginTop: spacing[5] }}>
              <ThemedText style={[styles.profileLabel, { color: theme.colors.textSecondary }]}>
                {t('fitquest.currentProfile')}
              </ThemedText>
              <ThemedText style={[styles.profileGoal, { color: theme.colors.text }]}>{userProfile.goal}</ThemedText>
              <ThemedText style={[styles.profileMeta, { color: theme.colors.textSecondary }]}>
                {userProfile.experience} · {userProfile.time_per_session_minutes}
                {t('fitquest.minShort')} {t('fitquest.sessions')}
              </ThemedText>
            </GlassCard>
          </Animated.View>
        )}

        <Animated.View
          entering={FadeInUp.delay(500).duration(150)}
          style={{ marginTop: spacing[6], width: '100%', maxWidth: 280 }}
        >
          <GradientButton title={t('fitquest.generateWorkout')} icon="lightning-bolt" onPress={generateNewWorkout} />
        </Animated.View>
      </View>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: spacing[6] },
  loadingIcon: { width: 80, height: 80, borderRadius: 24, justifyContent: 'center', alignItems: 'center' },
  loadingText: { marginTop: spacing[4], fontSize: typography.sizes.bodySmall },
  errorTitle: { fontSize: typography.sizes.h3, fontWeight: '600', marginTop: spacing[4], textAlign: 'center' },
  errorSub: { fontSize: typography.sizes.bodySmall, marginTop: spacing[2], textAlign: 'center' },
  genTitle: { fontSize: typography.sizes.h4, fontWeight: '600', marginTop: spacing[4], textAlign: 'center' },
  genSub: { fontSize: typography.sizes.label, marginTop: spacing[1.5], textAlign: 'center' },
  idleIconWrap: { width: 140, height: 140, borderRadius: 48, justifyContent: 'center', alignItems: 'center' },
  idleTitle: { fontSize: typography.sizes.h1, fontWeight: '800', marginTop: spacing[6] },
  idleSub: { fontSize: typography.sizes.bodySmall, textAlign: 'center', marginTop: spacing[2], lineHeight: 21 },
  profileLabel: { fontSize: typography.sizes.caption },
  profileGoal: { fontSize: typography.sizes.body, fontWeight: '600', marginTop: spacing[1] },
  profileMeta: { fontSize: typography.sizes.caption, marginTop: spacing[0.5] },
});

export default function FitQuestScreen() {
  const router = useRouter();
  return (
    <ScreenErrorBoundary
      screenName="FitQuest"
      onGoBack={() => (router.canGoBack() ? router.back() : router.replace('/dashboard'))}
    >
      <PremiumGate featureName="AI Workout Generator">
        <ScreenTutorial
          screenKey="fitquest"
          icon="sword-cross"
          title="FitQuest Training"
          description="Your personalized workout generator. Tap 'Generate Workout' to get an AI-tailored exercise session based on your goals, equipment, and recovery status."
        />
        <FitQuestScreenInner />
      </PremiumGate>
    </ScreenErrorBoundary>
  );
}
