/**
 * FitQuest Workout Screen
 * Premium glass UI with animated transitions
 */

import React, { useEffect, useState, useRef, useCallback } from 'react';
import {
  View,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  AppState,
  Vibration,
  useWindowDimensions,
} from 'react-native';
import Animated, { FadeIn, FadeInDown, FadeInUp, FadeInRight, ZoomIn } from 'react-native-reanimated';
import { ScreenContainer } from '../src/components/ui/primitives';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useTheme } from '../src/context/ThemeContext';
import { useLanguage } from '../src/context/LanguageContext';
import { useDatabase } from '../src/context/DatabaseContext';
import { useSubscription } from '../src/purchases/SubscriptionContext';
import { useFitQuestWorkout, WorkoutExerciseDisplay, WorkoutCompletionData } from '../src/hooks/useFitQuestWorkout';
import WorkoutSummaryView from '../src/components/WorkoutSummaryView';
import { useTimer } from '../src/hooks/useTimer';
import { useFitquestViewModel } from '../src/viewmodels/useFitquestViewModel';
import { GlassCard, GradientButton, PulseDot, SectionHeader } from '../src/components/ui/GlassUI';
import { ScreenErrorBoundary } from '../src/components/ScreenErrorBoundary';
import ExerciseImage from '../src/components/ExerciseImage';
import RestTimerOverlay from '../src/components/RestTimerOverlay';
import GetReadyOverlay from '../src/components/GetReadyOverlay';
import ConfettiBurst from '../src/components/ConfettiBurst';
import ExerciseCompleteBadge from '../src/components/ExerciseCompleteBadge';
import { evaluatePostWorkoutReward } from '../src/services/microRewards';
import { getUserProgress } from '../src/database/service';
import MindExerciseView from '../src/components/MindExerciseView';
import { haptic } from '../src/utils/haptics';
import { useToast } from '../src/context/ToastContext';
import ThemedText from '../src/components/ThemedText';
import { useRouter, useLocalSearchParams } from 'expo-router';
import ScreenTutorial from '../src/components/ScreenTutorial';
import PremiumGate from '../src/components/PremiumGate';
import { typography, spacing, radius } from '../src/design/theme-system';

// Module-level cooldown — survives unmount/remount across navigation cycles.
// Prevents re-generation when user navigates away and back within 10 seconds.
let lastAutoGeneratedAt = 0;
const AUTO_GEN_COOLDOWN_MS = 10_000;

/** Self-contained session clock — re-renders only itself every second */
function SessionClock({
  startRef,
  active,
  style,
}: {
  startRef: React.MutableRefObject<number | null>;
  active: boolean;
  style: any;
}) {
  const [elapsed, setElapsed] = useState(0);
  useEffect(() => {
    if (!active || !startRef.current) {
      setElapsed(0);
      return;
    }
    const interval = setInterval(() => {
      setElapsed(Math.floor((Date.now() - startRef.current!) / 1000));
    }, 1000);
    return () => clearInterval(interval);
  }, [active, startRef]);
  const m = Math.floor(elapsed / 60);
  const s = elapsed % 60;
  return <ThemedText style={style}>{`${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`}</ThemedText>;
}

function FitQuestScreenInner() {
  const { width } = useWindowDimensions();
  const { theme } = useTheme();
  const { t } = useLanguage();
  const { showToast } = useToast();
  const { autostart } = useLocalSearchParams<{ autostart?: string }>();
  const router = useRouter();
  const { isReady, isLoading: dbLoading, error: dbError, userProfile, resetAll } = useDatabase();
  const {
    status,
    workout,
    currentExercise,
    currentExerciseIndex,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    progressPercentage,
    error,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    fatigueSnapshot,
    deloadStatus,
    generateNewWorkout,
    recoverActiveSession,
    startWorkout,
    completeExercise,
    skipExercise,
    finishWorkout,
    cancelWorkout,
  } = useFitQuestWorkout();

  const [completionResult, setCompletionResult] = useState<WorkoutCompletionData | null>(null);
  const [showConfetti, setShowConfetti] = useState(false);
  const [showCompleteBadge, setShowCompleteBadge] = useState(false);
  const [showInsight, setShowInsight] = useState(false);
  const [showMemory, setShowMemory] = useState(false);

  // ViewModel: audio management, trial gating, workout persistence
  const vm = useFitquestViewModel();

  // Timer integration
  const {
    restTimer,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    sessionTimer,
    startRest,
    skipRest,
    extendRest,
    startSession,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    endSession,
    pauseAll,
    resumeAll,
    stopAll,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    isActive: timerActive,
  } = useTimer();

  // Session clock (elapsed time)
  const sessionStartRef = useRef<number | null>(null);
  const isCompactScreen = width < 390;

  // Pause timers when app goes to background, resume on foreground
  useEffect(() => {
    const sub = AppState.addEventListener('change', (nextState) => {
      if (nextState === 'background' || nextState === 'inactive') {
        pauseAll();
      } else if (nextState === 'active') {
        resumeAll();
      }
    });
    return () => sub.remove();
  }, [pauseAll, resumeAll]);

  // Speak exercise instructions when transitioning to new exercise (VM handles narration chain)
  useEffect(() => {
    if (status === 'in_progress' && currentExercise && vm.voiceEnabled) {
      vm.speakExercise(currentExercise);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- currentExercise narrowed to .id intentionally
  }, [status, currentExercise?.id, vm.voiceEnabled]);

  // Rest timer state
  const [isResting, setIsResting] = useState(false);
  const pendingExerciseAdvanceRef = useRef(false);
  // Get-Ready overlay state (P3: exercise transitions)
  const [isGetReady, setIsGetReady] = useState(false);
  const [getReadyExercise, setGetReadyExercise] = useState<{
    exerciseId: string;
    name: string;
    category: string;
    sets: number;
    reps: string;
    setupCue?: string;
    audioSetup?: string;
    equipmentChanged?: boolean;
  } | null>(null);
  // Collapsible instructions
  const [showAllInstructions, setShowAllInstructions] = useState(false);

  // Stable ref for generateNewWorkout to prevent re-triggering on identity changes
  const generateNewWorkoutRef = useRef(generateNewWorkout);
  generateNewWorkoutRef.current = generateNewWorkout;
  const autoGeneratedRef = useRef(false);
  const badgeTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Clear badge animation timer on unmount
  useEffect(() => () => { if (badgeTimerRef.current) clearTimeout(badgeTimerRef.current); }, []);

  // Load trial snapshot for feature gating
  const { accessState } = useSubscription();
  const isSubscribed = accessState === 'SUBSCRIBED';
  useEffect(() => {
    if (isReady) {
      vm.loadTrialSnapshot(isSubscribed);
    }
  }, [isReady, isSubscribed, vm.loadTrialSnapshot]);

  // Auto-generate on mount if ready and idle (once per screen visit, with global cooldown)
  // First attempts to recover an interrupted session; only generates fresh if no recovery.
  useEffect(() => {
    if (isReady && userProfile && status === 'idle' && !completionResult && !autoGeneratedRef.current) {
      // Global cooldown: prevent re-generation across navigation cycles
      if (Date.now() - lastAutoGeneratedAt < AUTO_GEN_COOLDOWN_MS) {
        if (__DEV__) console.warn('[FitQuest] Auto-gen skipped (cooldown active)');
        return;
      }
      autoGeneratedRef.current = true;
      lastAutoGeneratedAt = Date.now();

      // Try to recover a crashed/interrupted session first
      let cancelled = false;
      recoverActiveSession().then((recovered) => {
        if (cancelled) return;
        if (!recovered) {
          if (__DEV__) console.warn('[FitQuest] No session to recover — generating new workout');
          const timer = setTimeout(() => generateNewWorkoutRef.current(), 500);
          // Note: cleanup below only covers the outer effect; inner timeout is short-lived
          return () => clearTimeout(timer);
        }
        if (__DEV__) console.warn('[FitQuest] Recovered interrupted session — skipping generation');
      });
      return () => { cancelled = true; };
    }
  }, [isReady, userProfile, status, completionResult, recoverActiveSession]);

  // Auto-start: when navigated from dashboard with ?autostart=1, immediately begin
  // the workout once it's been generated (status transitions idle → generated → in_progress)
  const autostartedRef = useRef(false);
  useEffect(() => {
    if (autostart === '1' && status === 'ready' && workout && !autostartedRef.current) {
      autostartedRef.current = true;
      haptic('workoutStart');
      startWorkout();
      startSession(60);
      sessionStartRef.current = Date.now();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- startWorkout/startSession stable via hook identity; including them would re-trigger on every render
  }, [autostart, status, workout]);

  // Workout rating state (shown after completion)
  const [workoutRating, setWorkoutRating] = useState<number | null>(null);

  // Stop audio whenever we leave in_progress state (safety net)
  useEffect(() => {
    if (status !== 'in_progress') {
      vm.cancelNarration();
    }
  }, [status, vm.cancelNarration]);

  const advanceAfterRest = useCallback(
    async (reason: 'timer' | 'skip') => {
      if (!pendingExerciseAdvanceRef.current) return;
      pendingExerciseAdvanceRef.current = false;
      skipRest();
      setIsResting(false);
      setShowAllInstructions(false);

      const nextIdx = currentExerciseIndex + 1;
      const hasNext = nextIdx < (workout?.exercises.length ?? 0);

      if (reason === 'timer' && hasNext) {
        const next = workout!.exercises[nextIdx];
        const curr = workout!.exercises[currentExerciseIndex];
        const currentPhase = curr?.phase || 'main';

        // Warmup/cooldown: skip Get-Ready overlay — just advance immediately for pace
        if (currentPhase === 'warmup' || currentPhase === 'cooldown') {
          completeExercise(5);
          Vibration.vibrate(20);
          if (__DEV__) console.warn(`[FitQuest] ${currentPhase} rest ended — quick advance`, { next: next?.name });
          return;
        }

        // Main exercises: full Get-Ready countdown before next exercise
        if (!next) {
          completeExercise(5);
          return;
        }
        const categoryChanged = curr && curr.category !== next.category;
        setGetReadyExercise({
          exerciseId: next.exerciseId,
          name: next.name,
          category: next.category,
          sets: next.sets,
          reps: next.reps,
          setupCue: next.instructions?.[0],
          audioSetup: next.audioSetup,
          equipmentChanged: !!categoryChanged,
        });
        setIsGetReady(true);
        if (__DEV__)
          console.warn('[FitQuest] Rest ended — showing Get Ready', { nextExercise: next.name, categoryChanged });
      } else {
        // Skipped rest or no next exercise → advance immediately
        completeExercise(5);
        Vibration.vibrate(20);
        if (__DEV__) console.warn('[FitQuest] Rest ended — advancing immediately', { reason });
      }
    },
    [currentExerciseIndex, workout, skipRest, completeExercise],
  );

  const handleGetReadyDone = useCallback(() => {
    setIsGetReady(false);
    setGetReadyExercise(null);
    completeExercise(5);
    Vibration.vibrate(20);
    if (__DEV__) console.warn('[FitQuest] Get-Ready done — next exercise');
  }, [completeExercise]);

  const handleExtendRest = useCallback(
    (seconds: number) => {
      extendRest(seconds);
      if (__DEV__) console.warn('[FitQuest] Rest extended +' + seconds + 's');
    },
    [extendRest],
  );

  const handleFinish = useCallback(async () => {
    if (__DEV__) console.warn('[FitQuest] handleFinish called — processing workout completion');
    vm.cancelNarration();
    vm.resetNarrationState();

    let result: WorkoutCompletionData | null = null;
    try {
      result = await finishWorkout();
    } catch (e) {
      if (__DEV__) console.error('[FitQuest] finishWorkout threw (non-fatal):', e);
    }

    if (result) {
      haptic('workoutComplete');
      if (__DEV__) console.warn('[FitQuest] Workout finished successfully — showing completion screen');
      setCompletionResult(result);
      setWorkoutRating(null);

      // Toast XP gain + level up
      const xpMsg = result.levelUp
        ? `+${result.xpEarned} XP — Level ${result.newLevel}!`
        : `+${result.xpEarned} XP`;
      showToast({ message: xpMsg, type: 'success', vibrate: true, duration: 4000 });

      // Micro-reward: milestone / streak / goal completion toast (non-blocking)
      (async () => {
        try {
          const totalCompleted = (await getUserProgress().catch(() => null))?.completed_workouts ?? 0;
          const reward = await evaluatePostWorkoutReward(
            totalCompleted,
            result.streak?.current ?? 0,
          );
          if (reward.type !== 'NONE' && reward.type !== 'WORKOUT_DONE') {
            // Delay slightly so it doesn't overlap with XP toast
            setTimeout(() => {
              showToast({ message: reward.message, type: reward.variant === 'success' ? 'success' : 'info', duration: 5000 });
            }, 4500);
          }
        } catch {}
      })();

      // Narrator compliments the user with context-aware praise (non-blocking)
      vm.playWorkoutCompliment({
        completedCount: result.completedCount,
        totalCount: result.totalCount,
        durationSeconds: result.durationSeconds,
        streakDays: result.streak?.current ?? 0,
        xpEarned: result.xpEarned,
        levelUp: result.levelUp,
        newLevel: result.newLevel,
        progressions: result.progressions,
        exerciseNames: result.exerciseNames,
      });

      // Store last workout summary so AI Coach can reference it
      vm.storeLastWorkout(result);
    } else {
      if (__DEV__) console.warn('[FitQuest] finishWorkout returned null — may have already been called');
    }
  }, [finishWorkout, vm.cancelNarration, vm.resetNarrationState, vm.playWorkoutCompliment, vm.storeLastWorkout]);

  // Auto-trigger finish when workout reaches completed status
  const finishTriggeredRef = useRef(false);
  useEffect(() => {
    if (status === 'completed' && workout && !completionResult && !finishTriggeredRef.current) {
      finishTriggeredRef.current = true;
      vm.cancelNarration();
      handleFinish().finally(() => {
        finishTriggeredRef.current = false;
      });
    }
  }, [status, workout, completionResult, handleFinish]);

  // Auto-advance when rest timer completes (replaces setTimeout backup)
  useEffect(() => {
    if (isResting && pendingExerciseAdvanceRef.current && restTimer.state === 'completed') {
      void advanceAfterRest('timer');
    }
  }, [isResting, restTimer.state, advanceAfterRest]);

  const wantsNewWorkoutRef = useRef(false);
  const handleNewWorkout = () => {
    setCompletionResult(null);
    setWorkoutRating(null);
    vm.resetNarrationState();
    autoGeneratedRef.current = true; // Prevent auto-gen from also firing
    wantsNewWorkoutRef.current = true;
    cancelWorkout(); // Reset hook state to idle — triggers re-render with status='idle'
  };

  // Reactive: generate when status returns to idle after user requested new workout
  useEffect(() => {
    if (wantsNewWorkoutRef.current && status === 'idle') {
      wantsNewWorkoutRef.current = false;
      lastAutoGeneratedAt = Date.now(); // Refresh cooldown
      generateNewWorkout();
    }
  }, [status, generateNewWorkout]);

  const handleReset = () => {
    Alert.alert(t('fitquest.reset.title'), t('fitquest.reset.body'), [
      { text: t('common.cancel'), style: 'cancel' },
      { text: t('fitquest.reset.confirm'), style: 'destructive', onPress: resetAll },
    ]);
  };

  // ===== LOADING STATE =====
  if (dbLoading) {
    return (
      <ScreenContainer>
        <View style={styles.centered}>
          <Animated.View entering={ZoomIn.duration(150)}>
            <View style={[styles.loadingIcon, { backgroundColor: theme.colors.accent + '15' }]}>
              <ActivityIndicator size="large" color={theme.colors.accent} />
            </View>
          </Animated.View>
          <Animated.Text
            entering={FadeIn.delay(50).duration(150)}
            style={[styles.loadingText, { color: theme.colors.textSecondary }]}
          >
            {t('fitquest.initializing')}
          </Animated.Text>
        </View>
      </ScreenContainer>
    );
  }

  // ===== ERROR STATE =====
  if (dbError || error) {
    return (
      <ScreenContainer>
        <View style={styles.centered}>
          <Animated.View entering={ZoomIn.duration(150)}>
            <MaterialCommunityIcons name="alert-circle" size={64} color={theme.colors.error} />
          </Animated.View>
          <ThemedText style={[styles.errorTitle, { color: theme.colors.text }]}>{t('fitquest.errorTitle')}</ThemedText>
          <ThemedText style={[styles.errorSub, { color: theme.colors.textSecondary }]}>{dbError || error}</ThemedText>
          <GradientButton
            title={t('fitquest.resetAndRetry')}
            icon="refresh"
            onPress={handleReset}
            colors={[theme.colors.error, theme.colors.error]}
          />
        </View>
      </ScreenContainer>
    );
  }

  // ===== DB NOT READY YET (retry in progress) =====
  if (!isReady) {
    return (
      <ScreenContainer>
        <View style={styles.centered}>
          <Animated.View entering={ZoomIn.duration(150)}>
            <View style={[styles.loadingIcon, { backgroundColor: theme.colors.accent + '15' }]}>
              <ActivityIndicator size="large" color={theme.colors.accent} />
            </View>
          </Animated.View>
          <Animated.Text
            entering={FadeIn.delay(50).duration(150)}
            style={[styles.loadingText, { color: theme.colors.textSecondary }]}
          >
            {t('fitquest.initializing')}
          </Animated.Text>
        </View>
      </ScreenContainer>
    );
  }

  // ===== COMPLETION STATE =====
  if (completionResult) {
    return (
      <>
        <ConfettiBurst active={showConfetti} onComplete={() => setShowConfetti(false)} />
        <WorkoutSummaryView
          data={completionResult}
          rating={workoutRating}
          onRate={setWorkoutRating}
          onNewWorkout={handleNewWorkout}
        />
      </>
    );
  }

  // ===== GENERATING STATE =====
  if (status === 'generating') {
    return (
      <ScreenContainer>
        <View style={styles.centered}>
          <Animated.View entering={ZoomIn.duration(150)}>
            <View style={[styles.loadingIcon, { backgroundColor: theme.colors.accent + '15' }]}>
              <ActivityIndicator size="large" color={theme.colors.accent} />
            </View>
          </Animated.View>
          <Animated.Text
            entering={FadeIn.delay(50).duration(150)}
            style={[styles.genTitle, { color: theme.colors.text }]}
          >
            {t('fitquest.craftingWorkout')}
          </Animated.Text>
          <Animated.Text
            entering={FadeIn.delay(80).duration(150)}
            style={[styles.genSub, { color: theme.colors.textMuted }]}
          >
            {t('fitquest.craftingSub')}
          </Animated.Text>
        </View>
      </ScreenContainer>
    );
  }

  // ===== READY STATE (Preview) =====
  if (status === 'ready' && workout) {
    return (
      <ScreenContainer>
        <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
          {/* Header */}
          <Animated.View entering={FadeIn.duration(150)}>
            <View
              style={[
                styles.readyHeader,
                {
                  backgroundColor: theme.isDark ? theme.colors.surfaceVariant : theme.colors.surface,
                  borderBottomWidth: 1,
                  borderBottomColor: theme.colors.border,
                },
              ]}
            >
              <View style={styles.readyHeaderRow}>
                <ThemedText style={[styles.readyTitle, { color: theme.colors.text }]}>{t('fitquest.todaysWorkout')}</ThemedText>
                {!!workout.isDeload && (
                  <View style={[styles.deloadBadge, { backgroundColor: theme.colors.warning }]}>
                    <ThemedText style={[styles.deloadBadgeText, { color: theme.colors.text }]}>{t('fitquest.deload')}</ThemedText>
                  </View>
                )}
              </View>
            </View>
          </Animated.View>

          {/* Explanation */}
          <Animated.View entering={FadeInDown.delay(100).duration(150)}>
            <GlassCard style={{ marginHorizontal: spacing[4], flexDirection: 'row', alignItems: 'center', gap: spacing[3] }}>
              <View style={[styles.hintIcon, { backgroundColor: theme.colors.accent + '12' }]}>
                <MaterialCommunityIcons name="lightbulb-outline" size={20} color={theme.colors.accent} />
              </View>
              <ThemedText style={[styles.explanationText, { color: theme.colors.textSecondary }]}>{workout.explanation}</ThemedText>
            </GlassCard>
          </Animated.View>

          {/* AI Workout Insight — expandable reasoning panel (gated by subscription) */}
          {workout.aiInsight && vm.trialSnapshot?.hasIntelligence !== false && (
            <Animated.View entering={FadeInDown.delay(120).duration(150)}>
              <TouchableOpacity
                activeOpacity={0.7}
                onPress={() => setShowInsight((v) => !v)}
                style={{ marginHorizontal: spacing[4], marginTop: spacing[2] }}
                accessibilityRole="button"
                accessibilityLabel={`AI workout insight${showInsight ? ', expanded' : ''}`}
              >
                <GlassCard style={{ padding: spacing[0] }}>
                  <View style={styles.insightHeader}>
                    <View style={[styles.hintIcon, { backgroundColor: theme.colors.blue + '15' }]}>
                      <MaterialCommunityIcons name="brain" size={18} color={theme.colors.blue} />
                    </View>
                    <View style={{ flex: 1 }}>
                      <ThemedText style={[styles.insightTitle, { color: theme.colors.text }]}>
                        {t('fitquest.aiInsight') || 'AI Workout Intelligence'}
                      </ThemedText>
                      <ThemedText style={[styles.insightSub, { color: theme.colors.textMuted }]}>
                        {workout.aiInsight.session_reason}
                      </ThemedText>
                    </View>
                    <MaterialCommunityIcons
                      name={showInsight ? 'chevron-up' : 'chevron-down'}
                      size={22}
                      color={theme.colors.textMuted}
                    />
                  </View>
                  {/* Preview panel — locked AI Insight (post-trial, not subscribed) */}
                  {workout.aiInsight &&
                    vm.trialSnapshot &&
                    !vm.trialSnapshot.hasIntelligence &&
                    vm.trialSnapshot.previewAvailable && (
                      <Animated.View entering={FadeInDown.delay(120).duration(150)}>
                        <TouchableOpacity
                          activeOpacity={0.7}
                          onPress={() => router.push('/paywall')}
                          style={{ marginHorizontal: spacing[4], marginTop: spacing[2] }}
                          accessibilityRole="button"
                          accessibilityLabel="Unlock AI workout insight"
                        >
                          <GlassCard style={{ padding: spacing[0] }}>
                            <View style={styles.insightHeader}>
                              <View style={[styles.hintIcon, { backgroundColor: theme.colors.blue + '15' }]}>
                                <MaterialCommunityIcons name="brain" size={18} color={theme.colors.blue} />
                              </View>
                              <View style={{ flex: 1 }}>
                                <ThemedText style={[styles.insightTitle, { color: theme.colors.textMuted }]}>
                                  AI Workout Intelligence
                                </ThemedText>
                                <ThemedText style={[styles.insightSub, { color: theme.colors.textMuted }]}>
                                  Advanced intelligence requires subscription.
                                </ThemedText>
                              </View>
                              <MaterialCommunityIcons name="lock-outline" size={20} color={theme.colors.textMuted} />
                            </View>
                          </GlassCard>
                        </TouchableOpacity>
                      </Animated.View>
                    )}
                  {showInsight && (
                    <View style={styles.insightBody}>
                      {/* Volume reasoning */}
                      <View style={styles.insightRow}>
                        <MaterialCommunityIcons name="chart-bar" size={16} color={theme.colors.accent} />
                        <ThemedText style={[styles.insightRowText, { color: theme.colors.textSecondary }]}>
                          {workout.aiInsight.volume_reason}
                        </ThemedText>
                      </View>
                      {/* Per-exercise reasoning */}
                      {workout.aiInsight.exercise_reasons.map((er, idx) => (
                        <View key={er.exercise_id || idx} style={styles.insightRow}>
                          <MaterialCommunityIcons name="dumbbell" size={14} color={theme.colors.textMuted} />
                          <View style={{ flex: 1 }}>
                            <ThemedText style={[styles.insightExName, { color: theme.colors.text }]}>{er.exercise_name}</ThemedText>
                            <ThemedText style={[styles.insightExReason, { color: theme.colors.textMuted }]}>{er.reason}</ThemedText>
                            {er.score_breakdown && (
                              <View style={styles.insightChips}>
                                <View style={[styles.insightChip, { backgroundColor: theme.colors.accent + '15' }]}>
                                  <ThemedText style={[styles.insightChipText, { color: theme.colors.accent }]}>
                                    {er.score_breakdown.freshness}
                                  </ThemedText>
                                </View>
                                <View style={[styles.insightChip, { backgroundColor: theme.colors.blue + '15' }]}>
                                  <ThemedText style={[styles.insightChipText, { color: theme.colors.blue }]}>
                                    {er.score_breakdown.goal_alignment}
                                  </ThemedText>
                                </View>
                                <View style={[styles.insightChip, { backgroundColor: theme.colors.warning + '15' }]}>
                                  <ThemedText style={[styles.insightChipText, { color: theme.colors.warning }]}>
                                    {er.score_breakdown.pattern_balance}
                                  </ThemedText>
                                </View>
                              </View>
                            )}
                          </View>
                        </View>
                      ))}
                      {/* General notes */}
                      {workout.aiInsight.general_notes.map((note, idx) => (
                        <View key={idx} style={styles.insightRow}>
                          <MaterialCommunityIcons name="information-outline" size={14} color={theme.colors.warning} />
                          <ThemedText style={[styles.insightRowText, { color: theme.colors.warning }]}>{note}</ThemedText>
                        </View>
                      ))}
                    </View>
                  )}
                </GlassCard>
              </TouchableOpacity>
            </Animated.View>
          )}

          {/* Adaptive Memory — Session comparison + progression context (gated by subscription) */}
          {(workout.lastImpact?.hasHistory || workout.workoutDelta?.hasChanges) &&
            vm.trialSnapshot?.hasMemory !== false && (
              <Animated.View entering={FadeInDown.delay(140).duration(150)}>
                <TouchableOpacity
                  activeOpacity={0.7}
                  onPress={() => setShowMemory((v) => !v)}
                  style={{ marginHorizontal: spacing[4], marginTop: spacing[2] }}
                  accessibilityRole="button"
                  accessibilityLabel={`Session memory${showMemory ? ', expanded' : ''}`}
                >
                  <GlassCard style={{ padding: spacing[0] }}>
                    <View style={styles.insightHeader}>
                      <View style={[styles.hintIcon, { backgroundColor: theme.colors.accent + '15' }]}>
                        <MaterialCommunityIcons name="memory" size={18} color={theme.colors.accent} />
                      </View>
                      <View style={{ flex: 1 }}>
                        <ThemedText style={[styles.insightTitle, { color: theme.colors.text }]}>
                          {t('fitquest.adaptiveMemory') || 'Session Memory'}
                        </ThemedText>
                        <ThemedText style={[styles.insightSub, { color: theme.colors.textMuted }]} numberOfLines={1}>
                          {workout.workoutDelta?.headline || workout.lastImpact?.headline || ''}
                        </ThemedText>
                      </View>
                      <MaterialCommunityIcons
                        name={showMemory ? 'chevron-up' : 'chevron-down'}
                        size={22}
                        color={theme.colors.textMuted}
                      />
                    </View>
                    {showMemory && (
                      <View style={styles.insightBody}>
                        {/* Last session impact */}
                        {workout.lastImpact?.hasHistory && (
                          <>
                            <View style={styles.insightRow}>
                              <MaterialCommunityIcons name="history" size={15} color={theme.colors.accent} />
                              <View style={{ flex: 1 }}>
                                <ThemedText style={[styles.memoryLabel, { color: theme.colors.text }]}>Last Session</ThemedText>
                                <ThemedText style={[styles.insightExReason, { color: theme.colors.textMuted }]}>
                                  {workout.lastImpact.headline}
                                </ThemedText>
                              </View>
                              <ThemedText style={[styles.memoryTime, { color: theme.colors.textMuted }]}>
                                {workout.lastImpact.timeSince}
                              </ThemedText>
                            </View>
                            <View style={styles.insightRow}>
                              <MaterialCommunityIcons
                                name={
                                  workout.lastImpact.trend === 'improving'
                                    ? 'trending-up'
                                    : workout.lastImpact.trend === 'declining'
                                      ? 'trending-down'
                                      : 'trending-neutral'
                                }
                                size={15}
                                color={
                                  workout.lastImpact.trend === 'improving'
                                    ? theme.colors.success
                                    : workout.lastImpact.trend === 'declining'
                                      ? theme.colors.warning
                                      : theme.colors.textMuted
                                }
                              />
                              <ThemedText style={[styles.insightRowText, { color: theme.colors.textSecondary }]}>
                                {workout.lastImpact.trendStatement}
                              </ThemedText>
                            </View>
                          </>
                        )}
                        {/* Workout delta */}
                        {workout.workoutDelta?.hasChanges && (
                          <View style={styles.insightRow}>
                            <MaterialCommunityIcons name="swap-horizontal" size={15} color={theme.colors.blue} />
                            <View style={{ flex: 1 }}>
                              <ThemedText style={[styles.memoryLabel, { color: theme.colors.text }]}>Changes</ThemedText>
                              <ThemedText style={[styles.insightExReason, { color: theme.colors.textMuted }]}>
                                {workout.workoutDelta.headline}
                              </ThemedText>
                              {workout.workoutDelta.removed.length > 0 && (
                                <View style={styles.insightChips}>
                                  {workout.workoutDelta.removed.slice(0, 3).map((name, i) => (
                                    <View
                                      key={i}
                                      style={[styles.insightChip, { backgroundColor: theme.colors.error + '12' }]}
                                    >
                                      <ThemedText style={[styles.insightChipText, { color: theme.colors.error }]}>
                                        - {name}
                                      </ThemedText>
                                    </View>
                                  ))}
                                </View>
                              )}
                            </View>
                          </View>
                        )}
                        {/* Progression narratives — top 3 */}
                        {workout.progressionNarratives.length > 0 && (
                          <>
                            <View style={[styles.insightRow, { marginTop: spacing[1] }]}>
                              <MaterialCommunityIcons name="chart-line" size={15} color={theme.colors.accent} />
                              <ThemedText style={[styles.memoryLabel, { color: theme.colors.text }]}>Progression</ThemedText>
                            </View>
                            {workout.progressionNarratives.slice(0, 4).map((pn) => (
                              <View key={pn.exerciseId} style={[styles.insightRow, { paddingLeft: spacing[2] }]}>
                                <View
                                  style={[
                                    styles.momentumDot,
                                    {
                                      backgroundColor:
                                        pn.trend === 'improving'
                                          ? theme.colors.success
                                          : pn.trend === 'declining'
                                            ? theme.colors.warning
                                            : theme.colors.textMuted,
                                    },
                                  ]}
                                />
                                <View style={{ flex: 1 }}>
                                  <ThemedText style={[styles.insightExName, { color: theme.colors.text }]}>
                                    {pn.exerciseName}
                                  </ThemedText>
                                  <ThemedText style={[styles.insightExReason, { color: theme.colors.textMuted }]}>
                                    {pn.narrative}
                                  </ThemedText>
                                </View>
                              </View>
                            ))}
                          </>
                        )}
                      </View>
                    )}
                  </GlassCard>
                </TouchableOpacity>
              </Animated.View>
            )}

          {/* Preview panel — locked Session Memory (post-trial, not subscribed) */}
          {(workout.lastImpact?.hasHistory || workout.workoutDelta?.hasChanges) &&
            vm.trialSnapshot &&
            !vm.trialSnapshot.hasMemory &&
            vm.trialSnapshot.previewAvailable && (
              <Animated.View entering={FadeInDown.delay(140).duration(150)}>
                <TouchableOpacity
                  activeOpacity={0.7}
                  onPress={() => router.push('/paywall')}
                  style={{ marginHorizontal: spacing[4], marginTop: spacing[2] }}
                  accessibilityRole="button"
                  accessibilityLabel="Unlock session memory"
                >
                  <GlassCard style={{ padding: spacing[0] }}>
                    <View style={styles.insightHeader}>
                      <View style={[styles.hintIcon, { backgroundColor: theme.colors.accent + '15' }]}>
                        <MaterialCommunityIcons name="memory" size={18} color={theme.colors.accent} />
                      </View>
                      <View style={{ flex: 1 }}>
                        <ThemedText style={[styles.insightTitle, { color: theme.colors.textMuted }]}>Session Memory</ThemedText>
                        <ThemedText style={[styles.insightSub, { color: theme.colors.textMuted }]}>
                          Advanced intelligence requires subscription.
                        </ThemedText>
                      </View>
                      <MaterialCommunityIcons name="lock-outline" size={20} color={theme.colors.textMuted} />
                    </View>
                  </GlassCard>
                </TouchableOpacity>
              </Animated.View>
            )}

          {/* Warnings */}
          {workout.warnings?.length > 0 && (
            <Animated.View
              entering={FadeInDown.delay(150).duration(150)}
              accessibilityRole="alert"
              accessibilityLabel="Workout warnings"
            >
              <GlassCard style={{ marginHorizontal: spacing[4], marginTop: spacing[2] }}>
                {workout.warnings.map((warning: string, idx: number) => (
                  <ThemedText key={idx} style={[styles.warningText, { color: theme.colors.warning }]}>
                    ⚠️ {warning}
                  </ThemedText>
                ))}
              </GlassCard>
            </Animated.View>
          )}

          {/* Deload Status */}
          {!!deloadStatus && (
            <Animated.View entering={FadeInDown.delay(200).duration(150)}>
              <GlassCard
                style={{ marginHorizontal: spacing[4], marginTop: spacing[2], flexDirection: 'row', alignItems: 'center', gap: spacing[3] }}
              >
                <MaterialCommunityIcons
                  name={deloadStatus.needed ? 'battery-low' : 'battery-high'}
                  size={24}
                  color={deloadStatus.needed ? theme.colors.warning : theme.colors.success}
                />
                <View>
                  <ThemedText style={[styles.recoveryLabel, { color: theme.colors.text }]}>
                    {t('fitquest.recoveryStatus')}
                  </ThemedText>
                  <ThemedText style={[styles.recoverySub, { color: theme.colors.textMuted }]}>{deloadStatus.reason}</ThemedText>
                </View>
              </GlassCard>
            </Animated.View>
          )}

          {/* Exercise Count */}
          <SectionHeader
            title={`${(workout.exercises ?? []).filter((e) => e.phase === 'main' || !e.phase).length} ${t('library.exercises')} · ~${workout.totalDuration} ${t('fitquest.minShort')}`}
            delay={250}
          />

          {/* Warm-Up Section (P6) */}
          {workout.warmup && workout.warmup.length > 0 && (
            <>
              <Animated.View
                entering={FadeInDown.delay(260).duration(150)}
                style={{ paddingHorizontal: spacing[4], marginBottom: spacing[1] }}
              >
                <View style={[styles.phaseTag, { backgroundColor: theme.colors.success + '18' }]}>
                  <MaterialCommunityIcons name="fire" size={16} color={theme.colors.success} />
                  <ThemedText style={[styles.phaseTagText, { color: theme.colors.success }]}>
                    {t('fitquest.warmUp') || 'Warm Up'} · {workout.warmup.length} {t('library.exercises')}
                  </ThemedText>
                </View>
              </Animated.View>
              {workout.warmup.map((exercise: WorkoutExerciseDisplay, index: number) => (
                <Animated.View
                  key={exercise.id}
                  entering={FadeInRight.delay(270 + index * 30).duration(120)}
                  style={{ paddingHorizontal: spacing[4], marginBottom: spacing[2] }}
                >
                  <View
                    style={[
                      styles.exercisePreviewCard,
                      { backgroundColor: theme.colors.surfaceVariant, borderColor: theme.colors.success + '30' },
                    ]}
                  >
                    <ExerciseImage exerciseId={exercise.exerciseId} category={exercise.category} variant="thumbnail" />
                    <View style={{ flex: 1, marginLeft: spacing[3] }}>
                      <ThemedText style={[styles.exercisePreviewName, { color: theme.colors.text }]}>{exercise.name}</ThemedText>
                      <ThemedText style={[styles.exercisePreviewMeta, { color: theme.colors.textMuted }]}>
                        {exercise.sets}× ({exercise.reps})
                      </ThemedText>
                    </View>
                  </View>
                </Animated.View>
              ))}
            </>
          )}

          {/* Main Workout Section Header */}
          {workout.warmup && workout.warmup.length > 0 && (
            <Animated.View
              entering={FadeInDown.delay(300).duration(150)}
              style={{ paddingHorizontal: spacing[4], marginTop: spacing[1], marginBottom: spacing[1] }}
            >
              <View style={[styles.phaseTag, { backgroundColor: theme.colors.accent + '18' }]}>
                <MaterialCommunityIcons name="dumbbell" size={16} color={theme.colors.accent} />
                <ThemedText style={[styles.phaseTagText, { color: theme.colors.accent }]}>
                  {t('fitquest.mainWorkout') || 'Main Workout'}
                </ThemedText>
              </View>
            </Animated.View>
          )}

          {/* Exercise List (main exercises only — warmup/cooldown shown above/below) */}
          {(workout.exercises ?? [])
            .filter((e) => e.phase === 'main' || !e.phase)
            .map((exercise: WorkoutExerciseDisplay, index: number) => (
              <Animated.View
                key={exercise.id}
                entering={FadeInRight.delay(250 + index * 40).duration(150)}
                style={{ paddingHorizontal: spacing[4], marginBottom: spacing[2] }}
              >
                <View
                  style={[
                    styles.exercisePreviewCard,
                    {
                      backgroundColor: theme.colors.surfaceVariant,
                      borderColor: theme.colors.border,
                    },
                  ]}
                >
                  <ExerciseImage exerciseId={exercise.exerciseId} category={exercise.category} variant="thumbnail" />
                  <View style={{ flex: 1, marginLeft: spacing[3] }}>
                    <ThemedText style={[styles.exercisePreviewName, { color: theme.colors.text }]}>{exercise.name}</ThemedText>
                    <ThemedText style={[styles.exercisePreviewMeta, { color: theme.colors.textMuted }]}>
                      {exercise.sets}× ({exercise.reps}) · {exercise.restSeconds}s
                    </ThemedText>
                  </View>
                </View>
              </Animated.View>
            ))}

          {/* Cool-Down Section (P6) */}
          {workout.cooldown && workout.cooldown.length > 0 && (
            <>
              <Animated.View
                entering={FadeInDown.delay(380).duration(150)}
                style={{ paddingHorizontal: spacing[4], marginTop: spacing[1], marginBottom: spacing[1] }}
              >
                <View style={[styles.phaseTag, { backgroundColor: theme.colors.blue + '18' }]}>
                  <MaterialCommunityIcons name="snowflake" size={16} color={theme.colors.blue} />
                  <ThemedText style={[styles.phaseTagText, { color: theme.colors.blue }]}>
                    {t('fitquest.coolDown') || 'Cool Down'} · {workout.cooldown.length} {t('library.exercises')}
                  </ThemedText>
                </View>
              </Animated.View>
              {workout.cooldown.map((exercise: WorkoutExerciseDisplay, index: number) => (
                <Animated.View
                  key={exercise.id}
                  entering={FadeInRight.delay(390 + index * 30).duration(120)}
                  style={{ paddingHorizontal: spacing[4], marginBottom: spacing[2] }}
                >
                  <View
                    style={[
                      styles.exercisePreviewCard,
                      { backgroundColor: theme.colors.surfaceVariant, borderColor: theme.colors.blue + '30' },
                    ]}
                  >
                    <ExerciseImage exerciseId={exercise.exerciseId} category={exercise.category} variant="thumbnail" />
                    <View style={{ flex: 1, marginLeft: spacing[3] }}>
                      <ThemedText style={[styles.exercisePreviewName, { color: theme.colors.text }]}>{exercise.name}</ThemedText>
                      <ThemedText style={[styles.exercisePreviewMeta, { color: theme.colors.textMuted }]}>
                        {exercise.sets}× ({exercise.reps})
                      </ThemedText>
                    </View>
                  </View>
                </Animated.View>
              ))}
            </>
          )}

          {/* Start Button */}
          <Animated.View entering={FadeInUp.delay(400).duration(150)} style={{ paddingHorizontal: spacing[4], marginTop: spacing[4] }}>
            <GradientButton
              title={t('train.startWorkout')}
              icon="play"
              onPress={() => {
                haptic('workoutStart');
                startWorkout();
                startSession(60);
                sessionStartRef.current = Date.now();
              }}
              variant="success"
              size="lg"
            />
          </Animated.View>

          {/* Regenerate */}
          <Animated.View entering={FadeIn.delay(450).duration(150)} style={{ paddingHorizontal: spacing[4], marginTop: spacing[2] }}>
            <TouchableOpacity
              style={[styles.regenBtn, { borderColor: theme.colors.border }]}
              onPress={generateNewWorkout}
              accessibilityRole="button"
              accessibilityLabel={t('fitquest.regenerate')}
            >
              <MaterialCommunityIcons name="refresh" size={18} color={theme.colors.text} />
              <ThemedText style={[styles.regenBtnText, { color: theme.colors.text }]}>{t('fitquest.regenerate')}</ThemedText>
            </TouchableOpacity>
          </Animated.View>

          <View style={{ height: 32 }} />
        </ScrollView>
      </ScreenContainer>
    );
  }

  // ===== IN PROGRESS STATE =====
  if (status === 'in_progress' && workout && currentExercise) {
    const isLastExercise = currentExerciseIndex === workout.exercises.length - 1;

    return (
      <ScreenContainer>
        {/* ═══ REST TIMER OVERLAY (P2) ═══ */}
        <RestTimerOverlay
          visible={!!isResting}
          progress={restTimer.progress}
          formattedRemaining={restTimer.formattedRemaining}
          remaining={restTimer.remaining}
          phase={currentExercise.phase || 'main'}
          nextExercise={(() => {
            const ne = workout.exercises[currentExerciseIndex + 1];
            return ne
              ? { exerciseId: ne.exerciseId, name: ne.name, category: ne.category, sets: ne.sets, reps: ne.reps }
              : undefined;
          })()}
          onSkip={() => {
            if (__DEV__) console.warn('[FitQuest] Rest skipped by user');
            haptic('restOver');
            void advanceAfterRest('skip');
          }}
          onExtend={handleExtendRest}
        />

        {/* ═══ GET READY OVERLAY (P3) ═══ */}
        <GetReadyOverlay
          visible={isGetReady}
          exercise={getReadyExercise}
          equipmentChanged={getReadyExercise?.equipmentChanged}
          onReady={handleGetReadyDone}
        />

        {/* Session Clock Bar */}
        <View
          style={[
            styles.sessionClockBar,
            {
              backgroundColor: theme.isDark ? theme.colors.surfaceVariant : theme.colors.surface,
              borderBottomColor: theme.colors.border,
            },
          ]}
        >
          <View style={styles.clockLeft}>
            <PulseDot color={theme.colors.success} size={5} active={true} />
            <SessionClock
              startRef={sessionStartRef}
              active={status === 'in_progress'}
              style={[styles.clockText, { color: theme.colors.accent }]}
            />
          </View>

          <View style={styles.clockCenter}>
            <TouchableOpacity
              onPress={vm.toggleVoice}
              accessibilityRole="switch"
              accessibilityLabel={vm.voiceEnabled ? 'Disable voice guidance' : 'Enable voice guidance'}
              accessibilityState={{ checked: vm.voiceEnabled }}
              style={[
                styles.voiceToggle,
                { backgroundColor: vm.voiceEnabled ? theme.colors.accent + '15' : theme.colors.textMuted + '10' },
              ]}
            >
              <MaterialCommunityIcons
                name={vm.voiceEnabled ? 'volume-high' : 'volume-off'}
                size={16}
                color={vm.voiceEnabled ? theme.colors.accent : theme.colors.textMuted}
              />
              {vm.isSpeaking && <PulseDot color={theme.colors.success} size={4} active={true} />}
            </TouchableOpacity>
          </View>

          <ThemedText style={[styles.clockExerciseCount, { color: theme.colors.textMuted }]}>
            {currentExerciseIndex + 1} / {workout.exercises.length}
            {currentExercise.phase === 'warmup'
              ? ' · Warm Up'
              : currentExercise.phase === 'cooldown'
                ? ' · Cool Down'
                : ''}
          </ThemedText>
        </View>

        {/* Segmented Progress Bar (warmup → main → cooldown) */}
        {(() => {
          const warmupCount = workout.exercises.filter((e) => e.phase === 'warmup').length;
          const mainCount = workout.exercises.filter((e) => e.phase === 'main' || !e.phase).length;
          const cooldownCount = workout.exercises.filter((e) => e.phase === 'cooldown').length;
          const total = workout.exercises.length;
          const completedInPhase = (phase: string) =>
            workout.exercises.filter((e) => (e.phase || 'main') === phase && e.completed).length;
          const phaseTotal = (phase: string) => workout.exercises.filter((e) => (e.phase || 'main') === phase).length;

          // Current exercise counts as "in progress" — show partial fill
          const currentPhase = currentExercise.phase || 'main';
          const isInPhase = (phase: string) => currentPhase === phase;

          return (
            <View style={styles.segmentedBarWrap}>
              {warmupCount > 0 && (
                <View style={[styles.segmentedBarSegment, { flex: warmupCount / total }]}>
                  <View
                    style={[
                      styles.segmentedBarFill,
                      {
                        width: `${phaseTotal('warmup') > 0 ? (completedInPhase('warmup') / phaseTotal('warmup')) * 100 : 0}%`,
                        backgroundColor: theme.colors.success,
                        borderRadius: completedInPhase('warmup') === phaseTotal('warmup') ? 0 : 2,
                      },
                    ]}
                  />
                  {isInPhase('warmup') && !workout.exercises[currentExerciseIndex]?.completed && (
                    <View style={[styles.segmentedBarPulse, { backgroundColor: theme.colors.success + '60' }]} />
                  )}
                </View>
              )}
              {mainCount > 0 && (
                <View style={[styles.segmentedBarSegment, { flex: mainCount / total }]}>
                  <View
                    style={[
                      styles.segmentedBarFill,
                      {
                        width: `${phaseTotal('main') > 0 ? (completedInPhase('main') / phaseTotal('main')) * 100 : 0}%`,
                        backgroundColor: theme.colors.accent,
                      },
                    ]}
                  />
                  {isInPhase('main') && !workout.exercises[currentExerciseIndex]?.completed && (
                    <View style={[styles.segmentedBarPulse, { backgroundColor: theme.colors.accent + '60' }]} />
                  )}
                </View>
              )}
              {cooldownCount > 0 && (
                <View style={[styles.segmentedBarSegment, { flex: cooldownCount / total }]}>
                  <View
                    style={[
                      styles.segmentedBarFill,
                      {
                        width: `${phaseTotal('cooldown') > 0 ? (completedInPhase('cooldown') / phaseTotal('cooldown')) * 100 : 0}%`,
                        backgroundColor: theme.colors.blue,
                      },
                    ]}
                  />
                  {isInPhase('cooldown') && !workout.exercises[currentExerciseIndex]?.completed && (
                    <View style={[styles.segmentedBarPulse, { backgroundColor: theme.colors.blue + '60' }]} />
                  )}
                </View>
              )}
            </View>
          );
        })()}

        {/* Exercise Complete Badge (P7) */}
        <ExerciseCompleteBadge
          visible={showCompleteBadge}
          message={
            currentExercise.phase === 'warmup'
              ? '🔥 Warmed Up!'
              : currentExercise.phase === 'cooldown'
                ? '❄️ Recovery!'
                : ['Nice!', 'Strong!', 'Crushed it!', 'Beast mode!', 'Solid!'][currentExerciseIndex % 5]
          }
          color={
            currentExercise.phase === 'warmup'
              ? theme.colors.success
              : currentExercise.phase === 'cooldown'
                ? theme.colors.blue
                : theme.colors.success
          }
        />

        {/* ═══ MIND EXERCISE: completely different experience ═══ */}
        {currentExercise.mindTimeline ? (
          <MindExerciseView
            exerciseName={currentExercise.name}
            timeline={currentExercise.mindTimeline}
            voiceEnabled={vm.voiceEnabled}
            onComplete={() => {
              if (__DEV__) console.warn('[FitQuest] Mind exercise completed:', currentExercise.name);
              haptic('exerciseComplete');
              setShowCompleteBadge(true);
              if (badgeTimerRef.current) clearTimeout(badgeTimerRef.current);
              badgeTimerRef.current = setTimeout(() => setShowCompleteBadge(false), 1300);
              completeExercise(5);
            }}
            onCancel={() => {
              vm.cancelNarration();
              Alert.alert('End Mind Session?', 'Your progress for this exercise will be saved.', [
                { text: 'Continue', style: 'cancel' },
                {
                  text: 'End',
                  style: 'destructive',
                  onPress: () => {
                    completeExercise(5);
                  },
                },
              ]);
            }}
          />
        ) : (
          <ScrollView
            contentContainerStyle={[styles.exerciseContent, isCompactScreen && styles.exerciseContentCompact]}
            showsVerticalScrollIndicator={false}
          >
            {/* Phase Banner for warmup/cooldown — shows phase + position within phase */}
            {currentExercise.phase === 'warmup' &&
              (() => {
                const warmups = workout.exercises.filter((e) => e.phase === 'warmup');
                const posInPhase = warmups.findIndex((e) => e.id === currentExercise.id) + 1;
                return (
                  <Animated.View entering={FadeIn.duration(150)} style={{ paddingHorizontal: spacing[4], marginBottom: spacing[2] }}>
                    <View
                      style={[styles.phaseTag, { backgroundColor: theme.colors.success + '18', alignSelf: 'center' }]}
                    >
                      <MaterialCommunityIcons name="fire" size={16} color={theme.colors.success} />
                      <ThemedText style={[styles.phaseTagText, { color: theme.colors.success }]}>
                        {t('fitquest.warmUp') || 'Warm Up'} {posInPhase}/{warmups.length}
                      </ThemedText>
                    </View>
                  </Animated.View>
                );
              })()}
            {currentExercise.phase === 'cooldown' &&
              (() => {
                const cooldowns = workout.exercises.filter((e) => e.phase === 'cooldown');
                const posInPhase = cooldowns.findIndex((e) => e.id === currentExercise.id) + 1;
                return (
                  <Animated.View entering={FadeIn.duration(150)} style={{ paddingHorizontal: spacing[4], marginBottom: spacing[2] }}>
                    <View style={[styles.phaseTag, { backgroundColor: theme.colors.blue + '18', alignSelf: 'center' }]}>
                      <MaterialCommunityIcons name="snowflake" size={16} color={theme.colors.blue} />
                      <ThemedText style={[styles.phaseTagText, { color: theme.colors.blue }]}>
                        {t('fitquest.coolDown') || 'Cool Down'} {posInPhase}/{cooldowns.length}
                      </ThemedText>
                    </View>
                  </Animated.View>
                );
              })()}

            {/* Current Exercise */}
            <Animated.View entering={FadeIn.duration(150)} style={styles.currentExercise}>
              {/* Exercise Image — auto-alternating between start/end position */}
              <Animated.View entering={ZoomIn.duration(200)} style={{ alignItems: 'center', marginBottom: spacing[4] }}>
                <ExerciseImage
                  exerciseId={currentExercise.exerciseId}
                  category={currentExercise.category}
                  variant="detail"
                  animate={true}
                />
              </Animated.View>

              <Animated.View entering={ZoomIn.duration(150)}>
                <ThemedText style={[styles.currentExName, { color: theme.colors.text }]}>{currentExercise.name}</ThemedText>
              </Animated.View>

              <View style={styles.prescriptionRow}>
                {[
                  { val: currentExercise.sets, label: t('fitquest.sets') },
                  { val: currentExercise.reps, label: t('fitquest.reps') },
                  { val: `${currentExercise.restSeconds}s`, label: t('train.rest') },
                ].map((p, i) => (
                  <Animated.View
                    key={p.label}
                    entering={FadeInUp.delay(i * 60).duration(150)}
                    style={styles.prescriptionItem}
                  >
                    <ThemedText style={[styles.prescriptionVal, { color: theme.colors.text }]}>{p.val}</ThemedText>
                    <ThemedText style={[styles.prescriptionLabel, { color: theme.colors.textMuted }]}>{p.label}</ThemedText>
                  </Animated.View>
                ))}
              </View>

              {/* Instructions (show first 3, collapsible) */}
              {currentExercise.instructions.length > 0 && (
                <Animated.View entering={FadeInDown.delay(200).duration(150)} style={{ width: '100%', marginTop: spacing[6] }}>
                  <GlassCard>
                    <ThemedText style={[styles.instTitle, { color: theme.colors.text }]}>{t('fitquest.formTips')}</ThemedText>
                    {currentExercise.instructions
                      .slice(0, showAllInstructions ? undefined : 3)
                      .map((inst: string, idx: number) => (
                        <ThemedText key={idx} style={[styles.instStep, { color: theme.colors.textSecondary }]}>
                          {idx + 1}. {inst}
                        </ThemedText>
                      ))}
                    {currentExercise.instructions.length > 3 && (
                      <TouchableOpacity
                        onPress={() => setShowAllInstructions(!showAllInstructions)}
                        style={{ marginTop: spacing[2] }}
                        accessibilityRole="button"
                        accessibilityLabel={showAllInstructions ? 'Show less instructions' : 'Show all instructions'}
                      >
                        <ThemedText style={{ color: theme.colors.accent, fontSize: typography.sizes.caption, fontWeight: '600' }}>
                          {showAllInstructions
                            ? t('fitquest.showLess')
                            : `+${currentExercise.instructions.length - 3} ${t('fitquest.more')}`}
                        </ThemedText>
                      </TouchableOpacity>
                    )}
                  </GlassCard>
                </Animated.View>
              )}
            </Animated.View>

            {/* Action Buttons — always visible, no RPE interruption */}
            <View style={[styles.actionRow, isCompactScreen && styles.actionRowCompact]}>
              <TouchableOpacity
                style={[
                  styles.skipButton,
                  isCompactScreen && styles.skipButtonCompact,
                  { borderColor: theme.colors.border },
                ]}
                accessibilityRole="button"
                accessibilityLabel={t('train.skip')}
                onPress={() => {
                  vm.cancelNarration();
                  stopAll();
                  setShowAllInstructions(false);
                  skipExercise();
                }}
              >
                <ThemedText style={{ color: theme.colors.textSecondary, fontWeight: '600' }}>{t('train.skip')}</ThemedText>
              </TouchableOpacity>

              <View style={{ flex: 1 }}>
                <GradientButton
                  title={
                    isLastExercise
                      ? t('fitquest.finishWorkout')
                      : currentExercise.phase === 'warmup' || currentExercise.phase === 'cooldown'
                        ? 'Done →'
                        : t('fitquest.completeSet')
                  }
                  icon={
                    isLastExercise
                      ? 'check-all'
                      : currentExercise.phase === 'warmup' || currentExercise.phase === 'cooldown'
                        ? 'arrow-right'
                        : 'check'
                  }
                  onPress={async () => {
                    if (isResting) return;
                    if (__DEV__) {
                      console.warn('[FitQuest] Action:complete_or_next', {
                        isLastExercise,
                        index: currentExerciseIndex,
                        total: workout.exercises.length,
                      });
                    }
                    vm.cancelNarration();
                    stopAll();
                    setShowAllInstructions(false);

                    if (isLastExercise) {
                      // Complete with default difficulty (skip RPE — user rates at the end)
                      completeExercise(5);
                      haptic('workoutComplete');
                      setShowConfetti(true);
                      // Stop ALL narration immediately — no yapping on completion
                      vm.cancelNarration();
                      // Light completion: just vibration, no voice (user requested instant silence)
                      Vibration.vibrate([0, 100, 80, 100, 80, 200]);
                      if (__DEV__)
                        console.warn(
                          '[FitQuest] Last exercise completed — waiting for useEffect to trigger handleFinish',
                        );
                    } else {
                      const currentPhase = currentExercise.phase || 'main';
                      const nextExercise = workout.exercises[currentExerciseIndex + 1];

                      // Warmup & Cooldown: lighter flow — quick transition, no heavy rest
                      if (currentPhase === 'warmup' || currentPhase === 'cooldown') {
                        haptic(currentPhase === 'warmup' ? 'warmupComplete' : 'cooldownComplete');
                        setShowCompleteBadge(true);
                        if (badgeTimerRef.current) clearTimeout(badgeTimerRef.current);
                        badgeTimerRef.current = setTimeout(() => setShowCompleteBadge(false), 1300);

                        // Detect phase boundary (warmup→main or main→cooldown)
                        const nextPhase = nextExercise?.phase || 'main';
                        const phaseChanging = nextPhase !== currentPhase;

                        if (phaseChanging) {
                          // Phase transition: brief pause then auto-advance (phase announcement handles narration)
                          completeExercise(5);
                          haptic('phaseTransition');
                        } else if (nextExercise) {
                          // Same phase: quick 2-second "Get Ready" then advance
                          setGetReadyExercise({
                            exerciseId: nextExercise.exerciseId,
                            name: nextExercise.name,
                            category: nextExercise.category,
                            sets: nextExercise.sets,
                            reps: nextExercise.reps,
                            setupCue: nextExercise.instructions?.[0],
                            audioSetup: nextExercise.audioSetup,
                            equipmentChanged: false,
                          });
                          pendingExerciseAdvanceRef.current = true;
                          // Short auto-rest for warmup/cooldown (keeps pace up)
                          setIsResting(true);
                          startRest(currentPhase === 'warmup' ? 10 : 8);
                        }
                        if (__DEV__) {
                          console.warn(`[FitQuest] ${currentPhase} exercise done`, {
                            phaseChanging,
                            nextPhase,
                            next: nextExercise?.name,
                          });
                        }
                      } else {
                        // Main exercises: full rest timer with breathing guide
                        // Play transition narration (rich: "Well done! Rest for Xs. Up next: Y")
                        await vm.playTransitionAudio(currentExercise);
                        if (__DEV__) {
                          console.warn('[FitQuest] Set complete — entering rest overlay immediately', {
                            currentExercise: currentExercise.name,
                            nextExercise: nextExercise?.name,
                          });
                        }
                        haptic('exerciseComplete');
                        setShowCompleteBadge(true);
                        if (badgeTimerRef.current) clearTimeout(badgeTimerRef.current);
                        badgeTimerRef.current = setTimeout(() => setShowCompleteBadge(false), 1300);
                        pendingExerciseAdvanceRef.current = true;
                        setIsResting(true);
                        const restDuration = currentExercise.restSeconds || 60;
                        startRest(restDuration);
                      }
                    }
                  }}
                  variant={isLastExercise ? 'success' : 'primary'}
                />
              </View>
            </View>

            {/* Cancel */}
            <TouchableOpacity
              style={{ marginTop: spacing[6], alignItems: 'center' }}
              onPress={() => {
                Alert.alert(t('fitquest.cancelTitle'), t('fitquest.cancelBody'), [
                  { text: t('fitquest.keepGoing'), style: 'cancel' },
                  {
                    text: t('common.cancel'),
                    style: 'destructive',
                    onPress: () => {
                      vm.cancelNarration();
                      stopAll();
                      cancelWorkout();
                    },
                  },
                ]);
              }}
              accessibilityRole="button"
              accessibilityLabel="Cancel workout"
            >
              <ThemedText style={{ color: theme.colors.textMuted, fontSize: typography.sizes.label }}>{t('fitquest.cancelWorkout')}</ThemedText>
            </TouchableOpacity>
          </ScrollView>
        )}
      </ScreenContainer>
    );
  }

  // ===== COMPLETED STATE (before processing) =====
  if (status === 'completed' && workout) {
    return (
      <ScreenContainer>
        <View style={styles.centered}>
          <Animated.View entering={ZoomIn.duration(150)}>
            <View style={[styles.loadingIcon, { backgroundColor: theme.colors.success + '15' }]}>
              <ActivityIndicator size="large" color={theme.colors.success} />
            </View>
          </Animated.View>
          <ThemedText style={[styles.genTitle, { color: theme.colors.text }]}>{t('fitquest.recordingProgress')}</ThemedText>
        </View>
      </ScreenContainer>
    );
  }

  // ===== DEFAULT/IDLE STATE =====
  return (
    <ScreenContainer>
      <View style={styles.centered}>
        <Animated.View entering={ZoomIn.duration(150)}>
          <View style={[styles.idleIconWrap, { backgroundColor: theme.colors.accent + '12' }]}>
            <MaterialCommunityIcons name="dumbbell" size={56} color={theme.colors.accent} />
          </View>
        </Animated.View>
        <Animated.Text
          entering={FadeInUp.delay(150).duration(150)}
          style={[styles.idleTitle, { color: theme.colors.text }]}
        >
          FitQuest
        </Animated.Text>
        <Animated.Text
          entering={FadeIn.delay(300).duration(150)}
          style={[styles.idleSub, { color: theme.colors.textSecondary }]}
        >
          {t('fitquest.idleSub')}
        </Animated.Text>

        {!!userProfile && (
          <Animated.View entering={FadeInDown.delay(400).duration(150)} style={{ width: '100%', maxWidth: 280 }}>
            <GlassCard style={{ alignItems: 'center', padding: spacing[4], marginTop: spacing[5] }}>
              <ThemedText style={[styles.profileLabel, { color: theme.colors.textSecondary }]}>
                {t('fitquest.currentProfile')}
              </ThemedText>
              <ThemedText style={[styles.profileGoal, { color: theme.colors.text }]}>{userProfile.goal}</ThemedText>
              <ThemedText style={[styles.profileMeta, { color: theme.colors.textSecondary }]}>
                {userProfile.experience} · {userProfile.time_per_session_minutes}
                {t('fitquest.minShort')} {t('fitquest.sessions')}
              </ThemedText>
            </GlassCard>
          </Animated.View>
        )}

        <Animated.View
          entering={FadeInUp.delay(500).duration(150)}
          style={{ marginTop: spacing[6], width: '100%', maxWidth: 280 }}
        >
          <GradientButton title={t('fitquest.generateWorkout')} icon="lightning-bolt" onPress={generateNewWorkout} />
        </Animated.View>
      </View>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: spacing[6] },
  scrollContent: { paddingBottom: spacing[25] },
  loadingIcon: { width: 80, height: 80, borderRadius: 24, justifyContent: 'center', alignItems: 'center' },
  loadingText: { marginTop: spacing[4], fontSize: typography.sizes.bodySmall },
  errorTitle: { fontSize: typography.sizes.h3, fontWeight: '600', marginTop: spacing[4], textAlign: 'center' },
  errorSub: { fontSize: typography.sizes.bodySmall, marginTop: spacing[2], textAlign: 'center' },
  genTitle: { fontSize: typography.sizes.h4, fontWeight: '600', marginTop: spacing[4], textAlign: 'center' },
  genSub: { fontSize: typography.sizes.label, marginTop: spacing[1.5], textAlign: 'center' },
  readyHeader: { paddingHorizontal: spacing[5], paddingTop: spacing[3], paddingBottom: spacing[2] },
  readyHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  readyTitle: { fontSize: typography.sizes.h2, fontWeight: '700' },
  deloadBadge: { paddingHorizontal: spacing[3], paddingVertical: spacing[1.25], borderRadius: radius.md },
  deloadBadgeText: { fontSize: typography.sizes.captionSm, fontWeight: '700' },
  hintIcon: { width: 36, height: 36, borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  explanationText: { flex: 1, fontSize: typography.sizes.bodySmall, lineHeight: 21 },
  warningText: { fontSize: typography.sizes.label, marginBottom: spacing[1] },
  recoveryLabel: { fontSize: typography.sizes.bodySmall, fontWeight: '500' },
  recoverySub: { fontSize: typography.sizes.caption, marginTop: spacing[0.5], lineHeight: 17 },
  exercisePreviewCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing[3.5],
    borderRadius: 14,
    borderWidth: 1,
  },
  exerciseNum: { width: 30, height: 30, borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  exerciseNumText: { fontWeight: '700', fontSize: typography.sizes.bodySmall },
  exercisePreviewName: { fontSize: typography.sizes.bodyMid, fontWeight: '600' },
  exercisePreviewMeta: { fontSize: typography.sizes.caption, marginTop: spacing[0.75], fontWeight: '400' },
  catBadge: { paddingHorizontal: spacing[2], paddingVertical: spacing[1], borderRadius: 6 },
  catBadgeText: { fontSize: typography.sizes.xs, fontWeight: '600' },
  regenBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing[3.5],
    borderRadius: radius.lg,
    borderWidth: 1,
    gap: spacing[2],
  },
  regenBtnText: { fontSize: typography.sizes.bodyMid, fontWeight: '600' },
  insightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    padding: spacing[3.5],
  },
  insightTitle: { fontSize: typography.sizes.bodySmall, fontWeight: '600' },
  insightSub: { fontSize: typography.sizes.caption, marginTop: spacing[0.5], lineHeight: 17 },
  insightBody: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(128,128,128,0.15)',
    paddingHorizontal: spacing[3.5],
    paddingTop: spacing[2.5],
    paddingBottom: spacing[3.5],
    gap: spacing[2.5],
  },
  insightRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing[2.5] },
  insightRowText: { flex: 1, fontSize: typography.sizes.label, lineHeight: 19 },
  insightExName: { fontSize: typography.sizes.label, fontWeight: '600' },
  insightExReason: { fontSize: typography.sizes.caption, lineHeight: 17, marginTop: spacing['px'] },
  insightChips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[1], marginTop: spacing[1] },
  insightChip: { paddingHorizontal: spacing[2], paddingVertical: spacing[0.5], borderRadius: 6 },
  insightChipText: { fontSize: typography.sizes.xs, fontWeight: '600' },
  memoryLabel: { fontSize: typography.sizes.label, fontWeight: '700' },
  memoryTime: { fontSize: typography.sizes.captionSm, fontWeight: '500' },
  momentumDot: { width: 6, height: 6, borderRadius: 3, marginTop: spacing[1.5] },
  phaseTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1.5],
    paddingVertical: spacing[1.5],
    paddingHorizontal: spacing[2.5],
    borderRadius: radius.md,
    alignSelf: 'flex-start',
    marginBottom: spacing[1],
  },
  phaseTagText: { fontSize: typography.sizes.label, fontWeight: '600' },
  sessionClockBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2.5],
    borderBottomWidth: 1,
  },
  clockLeft: { flexDirection: 'row', alignItems: 'center', gap: spacing[2] },
  clockCenter: { flexDirection: 'row', alignItems: 'center', gap: spacing[1.5] },
  clockText: { fontSize: typography.sizes.h3, fontWeight: '700', fontVariant: ['tabular-nums'] as any },
  clockExerciseCount: { fontSize: typography.sizes.label, fontWeight: '500' },
  voiceToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
    paddingHorizontal: spacing[2.5],
    paddingVertical: spacing[1.5],
    borderRadius: radius.lg,
  },
  progressBarWrap: {
    height: 4,
    backgroundColor: 'rgba(128,128,128,0.15)',
    overflow: 'hidden',
  },
  progressBarFill: { height: 4, borderRadius: 2 },
  segmentedBarWrap: {
    flexDirection: 'row',
    height: 5,
    gap: spacing[0.5],
    paddingHorizontal: spacing[0],
  },
  segmentedBarSegment: {
    height: 5,
    backgroundColor: 'rgba(128,128,128,0.12)',
    borderRadius: 3,
    overflow: 'hidden',
    position: 'relative',
  },
  segmentedBarFill: {
    height: 5,
    borderRadius: 3,
  },
  segmentedBarPulse: {
    position: 'absolute',
    right: 0,
    top: 0,
    width: 8,
    height: 5,
    borderRadius: 3,
  },
  exerciseContent: { padding: spacing[4], paddingBottom: spacing[25] },
  exerciseContentCompact: { paddingBottom: spacing[25] },
  // ═══ REST / GET-READY overlays are in separate components ═══
  restTimerCard: { alignItems: 'center', padding: spacing[6], marginBottom: spacing[4], gap: spacing[1.5] },
  restTimerValue: { fontSize: typography.sizes.h1, fontWeight: '700', fontVariant: ['tabular-nums'] as any },
  restTimerLabel: { fontSize: typography.sizes.label },
  skipRestButton: { marginTop: spacing[3], paddingHorizontal: spacing[5], paddingVertical: spacing[2], borderRadius: radius.md, borderWidth: 1 },
  currentExercise: { alignItems: 'center', marginTop: spacing[6] },
  currentExName: { fontSize: typography.sizes.h2, fontWeight: '700', textAlign: 'center' },
  prescriptionRow: { flexDirection: 'row', justifyContent: 'space-around', width: '100%', marginTop: spacing[7] },
  prescriptionItem: { alignItems: 'center' },
  prescriptionVal: { fontSize: typography.sizes.h1Sm, fontWeight: '700' },
  prescriptionLabel: { fontSize: typography.sizes.caption, marginTop: spacing[1], fontWeight: '400' },
  instTitle: { fontSize: typography.sizes.bodySmall, fontWeight: '600', marginBottom: spacing[2] },
  instStep: { fontSize: typography.sizes.bodySmall, marginBottom: spacing[1], lineHeight: 20 },
  diffPrompt: { textAlign: 'center', marginTop: spacing[6], fontSize: typography.sizes.label },
  difficultyRow: { flexDirection: 'row', justifyContent: 'center', gap: spacing[2.5], marginTop: spacing[2.5] },
  difficultyButton: { width: 46, height: 46, borderRadius: 23, justifyContent: 'center', alignItems: 'center' },
  difficultyText: { fontWeight: '700', fontSize: typography.sizes.bodyMid },
  actionRow: { flexDirection: 'row', gap: spacing[4], marginTop: spacing[10], paddingHorizontal: spacing[3] },
  actionRowCompact: { flexDirection: 'column-reverse', gap: spacing[2.5], marginTop: spacing[7], paddingHorizontal: spacing[0] },
  skipButton: {
    width: 80,
    height: 56,
    borderRadius: 28, // Circular/Pill shape
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  skipButtonCompact: {
    width: '100%',
    borderRadius: 14,
    height: 48,
  },
  idleIconWrap: { width: 140, height: 140, borderRadius: 48, justifyContent: 'center', alignItems: 'center' },
  idleTitle: { fontSize: typography.sizes.h1, fontWeight: '800', marginTop: spacing[6] },
  idleSub: { fontSize: typography.sizes.bodySmall, textAlign: 'center', marginTop: spacing[2], lineHeight: 21 },
  profileLabel: { fontSize: typography.sizes.caption },
  profileGoal: { fontSize: typography.sizes.body, fontWeight: '600', marginTop: spacing[1] },
  profileMeta: { fontSize: typography.sizes.caption, marginTop: spacing[0.5] },
});

export default function FitQuestScreen() {
  const router = useRouter();
  return (
    <ScreenErrorBoundary
      screenName="FitQuest"
      onGoBack={() => (router.canGoBack() ? router.back() : router.replace('/dashboard'))}
    >
      <PremiumGate featureName="AI Workout Generator">
        <ScreenTutorial
          screenKey="fitquest"
          icon="sword-cross"
          title="FitQuest Training"
          description="Your personalized workout generator. Tap 'Generate Workout' to get an AI-tailored exercise session based on your goals, equipment, and recovery status."
        />
        <FitQuestScreenInner />
      </PremiumGate>
    </ScreenErrorBoundary>
  );
}
