/**
 * External Exercise Database Seed
 *
 * Seeds 868 exercises from the free-exercise-db into FitQuest.
 * Only runs once - checks for existing external exercises before seeding.
 * Removes duplicates that match core exercises by normalized name.
 *
 * Generated from: workspace-repos/exercise-content/free-exercise-db
 */

import { getDatabase } from './schema';

// Known duplicates between core and external (normalized name matches)
// These external exercises will be skipped to prefer curated core versions
const DUPLICATE_EXTERNAL_IDS = [
  'fed_plank',
  'fed_star_jump',
  'fed_dead_bug',
  'fed_incline_push_up',
  'fed_single_leg_glute_bridge',
];

// Check if external exercises have already been seeded
export async function hasExternalExercises(): Promise<boolean> {
  const db = await getDatabase();
  const result = await db.getFirstAsync<{ count: number }>(
    `SELECT COUNT(*) as count FROM exercises WHERE external_id IS NOT NULL`,
  );
  return (result?.count ?? 0) > 0;
}

// Get count of external exercises
export async function getExternalExerciseCount(): Promise<number> {
  const db = await getDatabase();
  const result = await db.getFirstAsync<{ count: number }>(
    `SELECT COUNT(*) as count FROM exercises WHERE external_id IS NOT NULL`,
  );
  return result?.count ?? 0;
}

/** Normalize exercise name for dedup comparison */
function normalizeName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[-\s]+/g, '')
    .replace(/[^a-z0-9]/g, '');
}

/**
 * Remove external exercises that duplicate core exercises.
 * Uses both hardcoded IDs and name-based matching to catch all duplicates.
 */
async function removeDuplicateExercises(): Promise<number> {
  const db = await getDatabase();
  let removed = 0;

  // 1. Remove hardcoded duplicate IDs
  for (const extId of DUPLICATE_EXTERNAL_IDS) {
    await db.runAsync(`DELETE FROM exercise_images WHERE exercise_id = ?`, [extId]);
    await db.runAsync(`DELETE FROM exercise_training_types WHERE exercise_id = ?`, [extId]);
    await db.runAsync(`DELETE FROM exercise_equipment WHERE exercise_id = ?`, [extId]);
    await db.runAsync(`DELETE FROM exercise_muscles WHERE exercise_id = ?`, [extId]);
    await db.runAsync(`DELETE FROM exercises WHERE id = ?`, [extId]);
  }
  removed += DUPLICATE_EXTERNAL_IDS.length;

  // 2. Name-based dedup: find external exercises whose normalized name matches a core exercise
  const coreExercises = await db.getAllAsync<{ name: string }>(`SELECT name FROM exercises WHERE external_id IS NULL`);
  const coreNames = new Set(coreExercises.map((e) => normalizeName(e.name)));

  const externalExercises = await db.getAllAsync<{ id: string; name: string }>(
    `SELECT id, name FROM exercises WHERE external_id IS NOT NULL`,
  );

  const duplicateIds = externalExercises.filter((e) => coreNames.has(normalizeName(e.name))).map((e) => e.id);

  for (const extId of duplicateIds) {
    await db.runAsync(`DELETE FROM exercise_images WHERE exercise_id = ?`, [extId]);
    await db.runAsync(`DELETE FROM exercise_training_types WHERE exercise_id = ?`, [extId]);
    await db.runAsync(`DELETE FROM exercise_equipment WHERE exercise_id = ?`, [extId]);
    await db.runAsync(`DELETE FROM exercise_muscles WHERE exercise_id = ?`, [extId]);
    await db.runAsync(`DELETE FROM exercises WHERE id = ?`, [extId]);
  }
  removed += duplicateIds.length;

  if (__DEV__ && duplicateIds.length > 0) {
    console.warn(`[ExternalSeed] Name-based dedup removed ${duplicateIds.length} additional duplicates`);
  }

  return removed;
}

/**
 * Seed external exercises from free-exercise-db
 *
 * Note: This runs the pre-generated SQL file content.
 * In production, this would be bundled with the app.
 * For development, we read from the generated SQL file.
 */
export async function seedExternalExercises(): Promise<void> {
  // Check if already seeded
  if (await hasExternalExercises()) {
    if (__DEV__) console.warn('[ExternalSeed] External exercises already seeded, skipping');
    return;
  }

  if (__DEV__) console.warn('[ExternalSeed] Seeding 868 external exercises...');

  const db = await getDatabase();

  try {
    // Import the bundled seed data
    // This is generated by scripts/import-external-exercises.ts
    const { EXTERNAL_EXERCISE_SQL } = await import('./external-exercises-data');

    // Execute the SQL batch
    await db.execAsync(EXTERNAL_EXERCISE_SQL);

    // Remove duplicates that match core exercises
    const removed = await removeDuplicateExercises();
    if (__DEV__) console.warn(`[ExternalSeed] Removed ${removed} duplicate exercises`);

    // Verify the seed
    const count = await getExternalExerciseCount();
    if (__DEV__) console.warn(`[ExternalSeed] Seeded ${count} external exercises (after dedup)`);

    // Log category breakdown
    const categoryBreakdown = await db.getAllAsync<{ category: string; count: number }>(
      `SELECT category, COUNT(*) as count FROM exercises WHERE external_id IS NOT NULL GROUP BY category ORDER BY count DESC`,
    );
    if (__DEV__) console.warn('[ExternalSeed] Category breakdown:', JSON.stringify(categoryBreakdown));
  } catch (error) {
    if (__DEV__) console.error('[ExternalSeed] Failed to seed external exercises:', error);
    // Non-fatal - app can work without external exercises
  }
}
