/**
 * External Exercise Database Seed
 * 
 * Seeds 868 exercises from the free-exercise-db into FitQuest.
 * Only runs once - checks for existing external exercises before seeding.
 * Removes duplicates that match core exercises by normalized name.
 * 
 * Generated from: workspace-repos/exercise-content/free-exercise-db
 */

import { getDatabase } from './schema';

// Known duplicates between core and external (normalized name matches)
// These external exercises will be skipped to prefer curated core versions
const DUPLICATE_EXTERNAL_IDS = [
  'fed_plank',
  'fed_star_jump', 
  'fed_dead_bug',
  'fed_incline_push_up',
  'fed_single_leg_glute_bridge',
];

// Check if external exercises have already been seeded
export async function hasExternalExercises(): Promise<boolean> {
  const db = await getDatabase();
  const result = await db.getFirstAsync<{ count: number }>(
    `SELECT COUNT(*) as count FROM exercises WHERE external_id IS NOT NULL`
  );
  return (result?.count ?? 0) > 0;
}

// Get count of external exercises
export async function getExternalExerciseCount(): Promise<number> {
  const db = await getDatabase();
  const result = await db.getFirstAsync<{ count: number }>(
    `SELECT COUNT(*) as count FROM exercises WHERE external_id IS NOT NULL`
  );
  return result?.count ?? 0;
}

/**
 * Remove external exercises that duplicate core exercises
 */
async function removeDuplicateExercises(): Promise<number> {
  const db = await getDatabase();
  
  // Delete from junction tables first (foreign key integrity)
  for (const extId of DUPLICATE_EXTERNAL_IDS) {
    await db.runAsync(`DELETE FROM exercise_images WHERE exercise_id = ?`, [extId]);
    await db.runAsync(`DELETE FROM exercise_training_types WHERE exercise_id = ?`, [extId]);
    await db.runAsync(`DELETE FROM exercise_equipment WHERE exercise_id = ?`, [extId]);
    await db.runAsync(`DELETE FROM exercise_muscles WHERE exercise_id = ?`, [extId]);
    await db.runAsync(`DELETE FROM exercises WHERE id = ?`, [extId]);
  }
  
  return DUPLICATE_EXTERNAL_IDS.length;
}

/**
 * Seed external exercises from free-exercise-db
 * 
 * Note: This runs the pre-generated SQL file content.
 * In production, this would be bundled with the app.
 * For development, we read from the generated SQL file.
 */
export async function seedExternalExercises(): Promise<void> {
  // Check if already seeded
  if (await hasExternalExercises()) {
    console.log('[ExternalSeed] External exercises already seeded, skipping');
    return;
  }

  console.log('[ExternalSeed] Seeding 868 external exercises...');

  const db = await getDatabase();
  
  try {
    // Import the bundled seed data
    // This is generated by scripts/import-external-exercises.ts
    const { EXTERNAL_EXERCISE_SQL } = await import('./external-exercises-data');
    
    // Execute the SQL batch
    await db.execAsync(EXTERNAL_EXERCISE_SQL);
    
    // Remove duplicates that match core exercises
    const removed = await removeDuplicateExercises();
    console.log(`[ExternalSeed] Removed ${removed} duplicate exercises`);
    
    // Verify the seed
    const count = await getExternalExerciseCount();
    console.log(`[ExternalSeed] Seeded ${count} external exercises (after dedup)`);
    
    // Log category breakdown
    const categoryBreakdown = await db.getAllAsync<{ category: string; count: number }>(
      `SELECT category, COUNT(*) as count FROM exercises WHERE external_id IS NOT NULL GROUP BY category ORDER BY count DESC`
    );
    console.log('[ExternalSeed] Category breakdown:', JSON.stringify(categoryBreakdown));
    
  } catch (error) {
    console.error('[ExternalSeed] Failed to seed external exercises:', error);
    // Non-fatal - app can work without external exercises
  }
}
