import { StyleSheet } from 'react-native';
import { typography, spacing, radius } from '../../design/theme-system';

export const createWorkoutStyles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing[4],
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3.5],
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2.5],
    borderRadius: radius.md,
    borderWidth: 1,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing[4],
    gap: spacing[2.5],
    marginBottom: spacing[3],
  },
  filterButton: {
    width: 44,
    height: 44,
    borderRadius: radius.md,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 18,
    height: 18,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterBadgeText: {
    fontSize: typography.sizes.xs,
    fontWeight: '600',
  },
  filtersPanel: {
    marginHorizontal: spacing[4],
    marginBottom: spacing[3],
    padding: spacing[3.5],
    borderRadius: radius.lg,
    borderWidth: 1,
  },
  filterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  filterChip: {
    paddingHorizontal: spacing[3.5],
    paddingVertical: spacing[2],
    borderRadius: radius.md,
    borderWidth: 1,
    marginRight: spacing[2],
  },
  searchInput: {
    flex: 1,
    marginLeft: spacing[2],
    fontSize: typography.sizes.bodySmall,
  },
  categoryScroll: {
    flexGrow: 0,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2],
    marginBottom: spacing[2],
  },
  categoryChip: {
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2.5],
    borderRadius: radius.xl,
    borderWidth: 1,
    marginRight: spacing[2.5],
    minWidth: 70,
    alignItems: 'center',
  },
  exerciseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing[3.5],
    borderRadius: radius.md,
    borderWidth: 1,
    marginBottom: spacing[2],
  },
  checkCircle: {
    width: 24,
    height: 24,
    borderRadius: radius.lg,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  diffBadge: {
    paddingHorizontal: spacing[2],
    paddingVertical: spacing[1],
    borderRadius: radius.sm,
  },
  nameInput: {
    marginHorizontal: spacing[4],
    marginBottom: spacing[2],
    borderWidth: 1,
    borderRadius: radius.md,
    paddingHorizontal: spacing[3.5],
    paddingVertical: spacing[3],
  },
  nameField: {
    fontSize: typography.sizes.bodyMid,
  },
  configCard: {
    padding: spacing[4],
    marginBottom: spacing[3],
  },
  configHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing[3],
  },
  configActions: {
    flexDirection: 'row',
    gap: spacing[2],
  },
  configRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing[3],
  },
  configField: {
    flex: 1,
    alignItems: 'center',
  },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing[1],
  },
  repsInput: {
    borderWidth: 1,
    borderRadius: radius.md,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1.5],
    textAlign: 'center',
    fontSize: typography.sizes.bodySmall,
    marginTop: spacing[1],
    width: '100%',
  },
  summaryCard: {
    padding: spacing[5],
    marginBottom: spacing[4],
    alignItems: 'center',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacing[6],
    marginTop: spacing[3],
  },
  summaryItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  previewExercise: {
    padding: spacing[3.5],
    marginBottom: spacing[2],
  },
  previewRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  orderBadge: {
    width: 28,
    height: 28,
    borderRadius: radius.lg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing[4.5],
    borderRadius: radius.lg,
    marginTop: spacing[4],
    gap: spacing[2.5],
  },
  saveButtonText: {
    fontSize: typography.sizes.body,
    fontWeight: '600',
  },
  instructionToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing[3],
    paddingTop: spacing[2.5],
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  instructionBox: {
    marginTop: spacing[2.5],
    padding: spacing[3],
    borderRadius: radius.md,
    borderWidth: 1,
  },
  instructionStep: {
    flexDirection: 'row',
    marginBottom: spacing[2],
  },
  narrateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing[2],
    borderRadius: radius.md,
    marginTop: spacing[2],
  },
});
