-- ============================================================
-- Phase 27: Trust Alerts Table
-- Stores admin-reviewable alerts generated by threshold breaches
-- and trust score degradation events.
-- ============================================================

CREATE TABLE IF NOT EXISTS trust_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id TEXT,
  alert_type TEXT NOT NULL,
  severity TEXT NOT NULL CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  trust_score_at_alert NUMERIC NOT NULL,
  anomaly_count INTEGER NOT NULL DEFAULT 0,
  anomaly_summary JSONB DEFAULT '{}',
  metadata JSONB DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'ESCALATED')),
  resolved_by TEXT,
  resolved_at TIMESTAMP,
  resolution_notes TEXT,
  created_at TIMESTAMP DEFAULT now()
);

-- Query active alerts by status + severity
CREATE INDEX IF NOT EXISTS idx_trust_alerts_status
  ON trust_alerts (status, severity, created_at DESC);

-- Per-user alert timeline
CREATE INDEX IF NOT EXISTS idx_trust_alerts_user
  ON trust_alerts (user_id, created_at DESC);

-- Dedup: recent OPEN alerts per user + type
CREATE INDEX IF NOT EXISTS idx_trust_alerts_dedup
  ON trust_alerts (user_id, alert_type, status, created_at DESC);

ALTER TABLE trust_alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS trust_alerts_service_only ON trust_alerts;
CREATE POLICY trust_alerts_service_only ON trust_alerts
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');
